// Cambridge-style Error Correction exercises
// sentence = the sentence WITH the error
// answer = the corrected sentence
// base_word = the incorrect word/phrase
// context_sentence = the correct word/phrase (what it should be)

export interface ErrorCorrectionSeedItem {
  id: string;
  sentence: string;         // Sentence with error
  answer: string;            // Full corrected sentence
  options: string | null;
  explanation: string;
  explanation_es: string;
  cefr_level: string;
  category: string;
  difficulty: number;
  base_word: string;         // The error (wrong word/phrase)
  context_sentence: string;  // The correction (right word/phrase)
  answer_es?: string;
}

export const ERROR_CORRECTION_EXERCISES: ErrorCorrectionSeedItem[] = [
  // ── B1 (difficulty 1) — Common Spanish speaker errors ──
  {
    id: 'ec_001',
    sentence: 'She suggested me to go to the doctor.',
    answer: 'She suggested I go to the doctor.',
    base_word: 'me to go',
    context_sentence: 'I go',
    options: '["me to go","to go me","me going","I go"]',
    explanation: '"Suggest" doesn\'t use "suggest sb to do". Use: suggest + (that) + subject + bare infinitive.',
    explanation_es: '"Suggest" no lleva "suggest sb to do". Se usa: suggest + (that) + sujeto + infinitivo sin to.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Sugirió que solicitara el trabajo.',
  },
  {
    id: 'ec_002',
    sentence: 'I am agree with you.',
    answer: 'I agree with you.',
    base_word: 'am agree',
    context_sentence: 'agree',
    options: '["am agree","am agreed","do agree","agree"]',
    explanation: '"Agree" is a verb, not an adjective. Don\'t use "be" before it.',
    explanation_es: '"Agree" es un verbo, no un adjetivo. No se usa "be" delante.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Tengo muchas ganas de verte en la conferencia.',
  },
  {
    id: 'ec_003',
    sentence: 'He said me that he was tired.',
    answer: 'He told me that he was tired.',
    base_word: 'said me',
    context_sentence: 'told me',
    options: '["said me","said to me","told me","say me"]',
    explanation: '"Say" doesn\'t take an indirect object directly. Use "tell sb" or "say to sb".',
    explanation_es: '"Say" no lleva objeto indirecto directo. Usa "tell sb" o "say to sb".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Le dijo que estaba cansado.',
  },
  {
    id: 'ec_004',
    sentence: 'I have been to London the last year.',
    answer: 'I went to London last year.',
    base_word: 'have been',
    context_sentence: 'went',
    options: '["have been","had been","was been","went"]',
    explanation: '"Last year" is a finished time → use past simple, not present perfect.',
    explanation_es: '"Last year" es un tiempo terminado → se usa pasado simple, no presente perfecto.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Fui de compras ayer.',
  },
  {
    id: 'ec_005',
    sentence: 'The news are very shocking.',
    answer: 'The news is very shocking.',
    base_word: 'are',
    context_sentence: 'is',
    options: '["are","is","were","has"]',
    explanation: '"News" is uncountable and takes a singular verb.',
    explanation_es: '"News" es incontable y lleva verbo en singular.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Estuve en Londres el año pasado.',
  },
  {
    id: 'ec_006',
    sentence: 'She is married with a doctor.',
    answer: 'She is married to a doctor.',
    base_word: 'with',
    context_sentence: 'to',
    options: '["with","to","by","for"]',
    explanation: 'The correct preposition is "married to", not "married with".',
    explanation_es: 'La preposición correcta es "married to", no "married with".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Disfruto jugando al tenis los fines de semana.',
  },
  {
    id: 'ec_007',
    sentence: 'I am living here since 2015.',
    answer: 'I have been living here since 2015.',
    base_word: 'am living',
    context_sentence: 'have been living',
    options: '["am living","have been living","was living","had lived"]',
    explanation: '"Since 2015" (until now) requires present perfect continuous, not present continuous.',
    explanation_es: '"Since 2015" (hasta ahora) requiere presente perfecto continuo, no presente continuo.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Ella depende de sus padres económicamente.',
  },
  {
    id: 'ec_008',
    sentence: 'He can to speak three languages.',
    answer: 'He can speak three languages.',
    base_word: 'can to speak',
    context_sentence: 'can speak',
    options: '["can to speak","can speak","can speaking","is able speak"]',
    explanation: 'Modal verbs (can, must, should) are followed by bare infinitive — no "to".',
    explanation_es: 'Los verbos modales (can, must, should) van seguidos de infinitivo sin "to".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Depende del tiempo.',
  },
  {
    id: 'ec_009',
    sentence: 'I went to the shopping yesterday.',
    answer: 'I went shopping yesterday.',
    base_word: 'to the shopping',
    context_sentence: 'shopping',
    options: '["to the shopping","shopping","to shopping","for shopping"]',
    explanation: '"Go shopping" is a fixed expression — no article or preposition needed.',
    explanation_es: '"Go shopping" es una expresión fija — no necesita artículo ni preposición.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Ella me dio un consejo muy útil.',
  },
  {
    id: 'ec_010',
    sentence: 'She explained me the problem.',
    answer: 'She explained the problem to me.',
    base_word: 'explained me',
    context_sentence: 'explained the problem to me',
    options: '["explained me","explained to me","explained me about","explained the problem to me"]',
    explanation: '"Explain" requires "explain sth to sb", not "explain sb sth".',
    explanation_es: '"Explain" necesita "explain sth to sb", no "explain sb sth".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Ella está casada con un médico.',
  },
  // ── B2 (difficulty 2) ──
  {
    id: 'ec_011',
    sentence: 'Despite of the rain, we went out.',
    answer: 'Despite the rain, we went out.',
    base_word: 'Despite of',
    context_sentence: 'Despite',
    options: '["Despite of","Despite","In despite of","Although of"]',
    explanation: '"Despite" never takes "of". Use "despite + noun" or "in spite of + noun".',
    explanation_es: '"Despite" nunca lleva "of". Usa "despite + sustantivo" o "in spite of + sustantivo".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Estoy de acuerdo contigo.',
  },
  {
    id: 'ec_012',
    sentence: 'If I would have known, I would have helped.',
    answer: 'If I had known, I would have helped.',
    base_word: 'would have known',
    context_sentence: 'had known',
    options: '["would have known","had known","have known","did know"]',
    explanation: 'Third conditional: "If + past perfect, would + have + pp". Don\'t use "would" in the if-clause.',
    explanation_es: 'Tercer condicional: "If + pluscuamperfecto, would + have + pp". No usar "would" en la cláusula if.',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Llevo viviendo aquí desde 2010.',
  },
  {
    id: 'ec_013',
    sentence: 'I look forward to hear from you.',
    answer: 'I look forward to hearing from you.',
    base_word: 'to hear',
    context_sentence: 'to hearing',
    options: '["to hear","to hearing","for hearing","to have heard"]',
    explanation: '"Look forward to" — here "to" is a preposition, so it takes a gerund (-ing).',
    explanation_es: '"Look forward to" — aquí "to" es una preposición, así que lleva gerundio (-ing).',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Estoy de acuerdo en que deberíamos irnos pronto.',
  },
  {
    id: 'ec_014',
    sentence: 'The people is very friendly in this town.',
    answer: 'The people are very friendly in this town.',
    base_word: 'is',
    context_sentence: 'are',
    options: '["is","are","was been","has"]',
    explanation: '"People" is a plural noun and takes a plural verb.',
    explanation_es: '"People" es un sustantivo plural y lleva verbo en plural.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Tengo un trabajo muy bueno.',
  },
  {
    id: 'ec_015',
    sentence: 'I\'m not used to drive on the left.',
    answer: 'I\'m not used to driving on the left.',
    base_word: 'to drive',
    context_sentence: 'to driving',
    options: '["to drive","to driving","driving","for driving"]',
    explanation: '"Used to" (= accustomed to) — "to" is a preposition → gerund.',
    explanation_es: '"Used to" (= acostumbrado a) — "to" es preposición → gerundio.',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Necesito que me ayudes con esto.',
  },
  {
    id: 'ec_016',
    sentence: 'He denied to steal the money.',
    answer: 'He denied stealing the money.',
    base_word: 'to steal',
    context_sentence: 'stealing',
    options: '["to steal","stealing","to have stolen","steal"]',
    explanation: '"Deny" is followed by a gerund (-ing), not an infinitive.',
    explanation_es: '"Deny" va seguido de gerundio (-ing), no de infinitivo.',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Puede hablar tres idiomas.',
  },
  {
    id: 'ec_017',
    sentence: 'I have less friends than my sister.',
    answer: 'I have fewer friends than my sister.',
    base_word: 'less',
    context_sentence: 'fewer',
    options: '["less","fewer","lesser","least"]',
    explanation: '"Friends" is countable → use "fewer", not "less".',
    explanation_es: '"Friends" es contable → usa "fewer", no "less".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Negó haber robado el dinero.',
  },
  {
    id: 'ec_018',
    sentence: 'She insisted in paying the bill.',
    answer: 'She insisted on paying the bill.',
    base_word: 'in',
    context_sentence: 'on',
    options: '["in","on","for","at"]',
    explanation: 'The correct collocation is "insist on", not "insist in".',
    explanation_es: 'La colocación correcta es "insist on", no "insist in".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Evitó contestar la pregunta.',
  },
  {
    id: 'ec_019',
    sentence: 'I wish I can speak Japanese.',
    answer: 'I wish I could speak Japanese.',
    base_word: 'can',
    context_sentence: 'could',
    options: '["can","could","would","should"]',
    explanation: '"Wish" + present situation requires past tense: "wish + could".',
    explanation_es: '"Wish" + situación presente requiere pasado: "wish + could".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Ella se quejó de tener demasiado trabajo.',
  },
  {
    id: 'ec_020',
    sentence: 'The teacher asked us don\'t use phones in class.',
    answer: 'The teacher asked us not to use phones in class.',
    base_word: "don't use",
    context_sentence: 'not to use',
    options: '["don\'t use","not to use","to not use","not using"]',
    explanation: 'Reported instructions: "ask sb not to do", not "ask sb don\'t do".',
    explanation_es: 'Instrucciones en estilo indirecto: "ask sb not to do", no "ask sb don\'t do".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Tiene edad suficiente para conducir.',
  },
  // ── B2–C1 (difficulty 3) ──
  {
    id: 'ec_021',
    sentence: 'Seldom I have seen such a beautiful sunset.',
    answer: 'Seldom have I seen such a beautiful sunset.',
    base_word: 'I have seen',
    context_sentence: 'have I seen',
    options: '["I have seen","have I seen","I saw","did I see"]',
    explanation: 'After negative adverbs (seldom, rarely, never) at the start → inversion: aux + subject.',
    explanation_es: 'Tras adverbios negativos al inicio (seldom, rarely, never) → inversión: aux + sujeto.',
    cefr_level: 'C1', category: 'error_correction', difficulty: 3,
    answer_es: 'Se disculpó por llegar tarde.',
  },
  {
    id: 'ec_022',
    sentence: 'He prevented me to leave the building.',
    answer: 'He prevented me from leaving the building.',
    base_word: 'to leave',
    context_sentence: 'from leaving',
    options: '["to leave","from leaving","of leaving","leaving"]',
    explanation: '"Prevent sb from + -ing" — not "prevent sb to do".',
    explanation_es: '"Prevent sb from + -ing" — no "prevent sb to do".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Insistió en pagar la cuenta.',
  },
  {
    id: 'ec_023',
    sentence: 'She is one of the student who passed.',
    answer: 'She is one of the students who passed.',
    base_word: 'student',
    context_sentence: 'students',
    options: '["student","students","student\'s","studenting"]',
    explanation: '"One of the + plural noun". Always plural after "one of the".',
    explanation_es: '"One of the + sustantivo plural". Siempre plural después de "one of the".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Ella es capaz de resolver el problema.',
  },
  {
    id: 'ec_024',
    sentence: 'Not only he passed the exam, but he also got top marks.',
    answer: 'Not only did he pass the exam, but he also got top marks.',
    base_word: 'he passed',
    context_sentence: 'did he pass',
    options: '["he passed","did he pass","he did pass","has he passed"]',
    explanation: '"Not only" at the start of a sentence triggers inversion.',
    explanation_es: '"Not only" al inicio de una oración activa la inversión.',
    cefr_level: 'C1', category: 'error_correction', difficulty: 3,
    answer_es: 'Me impidió salir del edificio.',
  },
  {
    id: 'ec_025',
    sentence: 'She\'s been working here during three years.',
    answer: 'She\'s been working here for three years.',
    base_word: 'during',
    context_sentence: 'for',
    options: '["during","for","since","from"]',
    explanation: '"During" + specific period (e.g., "during the summer"). For duration → use "for".',
    explanation_es: '"During" + periodo específico. Para duración → usa "for".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Si lo hubiera sabido, habría ayudado.',
  },
  {
    id: 'ec_026',
    sentence: 'He made me to wait for two hours.',
    answer: 'He made me wait for two hours.',
    base_word: 'to wait',
    context_sentence: 'wait',
    options: '["to wait","wait","waiting","waited"]',
    explanation: '"Make sb do" (active) uses bare infinitive — no "to".',
    explanation_es: '"Make sb do" (activa) usa infinitivo sin "to".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Me hizo esperar dos horas.',
  },
  {
    id: 'ec_027',
    sentence: 'I would rather to stay at home.',
    answer: 'I would rather stay at home.',
    base_word: 'to stay',
    context_sentence: 'stay',
    options: '["to stay","stay","staying","stayed"]',
    explanation: '"Would rather" + bare infinitive (no "to").',
    explanation_es: '"Would rather" + infinitivo sin "to".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Ella está acostumbrada a levantarse temprano.',
  },
  {
    id: 'ec_028',
    sentence: 'The police has arrested two suspects.',
    answer: 'The police have arrested two suspects.',
    base_word: 'has',
    context_sentence: 'have',
    options: '["has","have","had","having"]',
    explanation: '"Police" is a plural noun in English and takes a plural verb.',
    explanation_es: '"Police" es un sustantivo plural en inglés y lleva verbo en plural.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'A pesar de la lluvia, salimos.',
  },
  {
    id: 'ec_029',
    sentence: 'He apologised for arrive late.',
    answer: 'He apologised for arriving late.',
    base_word: 'arrive',
    context_sentence: 'arriving',
    options: '["arrive","arriving","to arrive","arrived"]',
    explanation: 'After preposition "for" → gerund (-ing form).',
    explanation_es: 'Tras la preposición "for" → gerundio (-ing).',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Desearía poder hablar japonés.',
  },
  {
    id: 'ec_030',
    sentence: 'I\'m thinking to change my job.',
    answer: 'I\'m thinking of changing my job.',
    base_word: 'to change',
    context_sentence: 'of changing',
    options: '["to change","of changing","about change","for changing"]',
    explanation: '"Think of/about + -ing" (considering). Not "think to do".',
    explanation_es: '"Think of/about + -ing" (considerar). No "think to do".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Preferiría quedarme en casa.',
  },
  // ── More Error Correction — common Spanish speaker errors ──
  {
    id: 'ec_031',
    sentence: 'I enjoy to play tennis at the weekends.',
    answer: 'I enjoy playing tennis at the weekends.',
    base_word: 'to play',
    context_sentence: 'playing',
    options: '["to play","playing","play","for playing"]',
    explanation: '"Enjoy" is followed by a gerund (-ing), not an infinitive.',
    explanation_es: '"Enjoy" va seguido de gerundio (-ing), no de infinitivo.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Cada alumno debe entregar su tarea.',
  },
  {
    id: 'ec_032',
    sentence: 'She depends of her parents for money.',
    answer: 'She depends on her parents for money.',
    base_word: 'of',
    context_sentence: 'on',
    options: '["of","on","from","in"]',
    explanation: 'Fixed collocation: depend ON (not "of" — influenced by Spanish "depender de").',
    explanation_es: 'Colocación fija: depend ON (no "of" — influencia del español "depender de").',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'El número de estudiantes ha aumentado.',
  },
  {
    id: 'ec_033',
    sentence: 'He suggested us to go to the cinema.',
    answer: 'He suggested we go to the cinema.',
    base_word: 'us to go',
    context_sentence: 'we go',
    options: '["us to go","we go","us going","to go us"]',
    explanation: '"Suggest" + (that) + subject + bare infinitive. Never "suggest sb to do".',
    explanation_es: '"Suggest" + (that) + sujeto + infinitivo sin to. Nunca "suggest sb to do".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Tengo menos amigos que mi hermana.',
  },
  {
    id: 'ec_034',
    sentence: 'I\'m boring of this film.',
    answer: 'I\'m bored with this film.',
    base_word: 'boring of',
    context_sentence: 'bored with',
    options: '["boring of","bored with","boring with","bored of"]',
    explanation: '"Bored" (-ed = feeling) not "boring" (-ing = causing boredom). Preposition: "bored with/of".',
    explanation_es: '"Bored" (-ed = sentimiento) no "boring" (-ing = que causa aburrimiento). Preposición: "bored with/of".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Rara vez he visto un atardecer tan bonito.',
  },
  {
    id: 'ec_035',
    sentence: 'The majority of people thinks the law should change.',
    answer: 'The majority of people think the law should change.',
    base_word: 'thinks',
    context_sentence: 'think',
    options: '["thinks","think","is thinking","thought"]',
    explanation: '"The majority of people" takes a plural verb.',
    explanation_es: '"The majority of people" lleva verbo en plural.',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Apenas había llegado cuando empezó la reunión.',
  },
  {
    id: 'ec_036',
    sentence: 'She has been to the hairdresser\'s yesterday.',
    answer: 'She went to the hairdresser\'s yesterday.',
    base_word: 'has been',
    context_sentence: 'went',
    options: '["has been","went","had been","was"]',
    explanation: '"Yesterday" = finished time → past simple, not present perfect.',
    explanation_es: '"Yesterday" = tiempo terminado → pasado simple, no presente perfecto.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'No solo aprobó el examen, sino que sacó la mejor nota.',
  },
  {
    id: 'ec_037',
    sentence: 'He\'s the more intelligent student in the class.',
    answer: 'He\'s the most intelligent student in the class.',
    base_word: 'more',
    context_sentence: 'most',
    options: '["more","most","much","very"]',
    explanation: 'Superlative of long adjectives: "the most + adj" (not "the more").',
    explanation_es: 'Superlativo de adjetivos largos: "the most + adj" (no "the more").',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Le dijo que se iba.',
  },
  {
    id: 'ec_038',
    sentence: 'I\'d like that you come to my party.',
    answer: 'I\'d like you to come to my party.',
    base_word: 'that you come',
    context_sentence: 'you to come',
    options: '["that you come","you to come","you coming","that you to come"]',
    explanation: '"Would like" + object + to-infinitive. Not "would like that...".',
    explanation_es: '"Would like" + objeto + to-infinitivo. No "would like that...".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Sugirió que fuéramos al cine.',
  },
  {
    id: 'ec_039',
    sentence: 'We discussed about the problem for hours.',
    answer: 'We discussed the problem for hours.',
    base_word: 'about',
    context_sentence: '',
    options: '["discussed about","discussed","discussed on","discussed for"]',
    explanation: '"Discuss" is transitive — no preposition needed. Not "discuss about".',
    explanation_es: '"Discuss" es transitivo — no necesita preposición. No "discuss about".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Espero tener noticias suyas.',
  },
  {
    id: 'ec_040',
    sentence: 'She\'s been living in London since five years.',
    answer: 'She\'s been living in London for five years.',
    base_word: 'since',
    context_sentence: 'for',
    options: '["since","for","during","from"]',
    explanation: '"Since" = point in time (2019). "For" = duration (five years).',
    explanation_es: '"Since" = punto en el tiempo (2019). "For" = duración (five years).',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Tengo muchas ganas de verte.',
  },
  {
    id: 'ec_041',
    sentence: 'It depends of the weather.',
    answer: 'It depends on the weather.',
    base_word: 'of',
    context_sentence: 'on',
    options: '["of","on","from","about"]',
    explanation: 'Fixed collocation: depend ON. Spanish interference: "depende de".',
    explanation_es: 'Colocación fija: depend ON. Interferencia del español: "depende de".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Está acostumbrada a levantarse temprano.',
  },
  {
    id: 'ec_042',
    sentence: 'He avoided to answer the question.',
    answer: 'He avoided answering the question.',
    base_word: 'to answer',
    context_sentence: 'answering',
    options: '["to answer","answering","answer","for answering"]',
    explanation: '"Avoid" is followed by a gerund (-ing), not an infinitive.',
    explanation_es: '"Avoid" va seguido de gerundio (-ing), no de infinitivo.',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'El número de estudiantes ha aumentado.',
  },
  {
    id: 'ec_043',
    sentence: 'I\'m interesting in modern art.',
    answer: 'I\'m interested in modern art.',
    base_word: 'interesting',
    context_sentence: 'interested',
    options: '["interesting","interested","interest","interestingly"]',
    explanation: '"Interested" (-ed = feeling) vs "interesting" (-ing = causing interest).',
    explanation_es: '"Interested" (-ed = sentimiento) vs "interesting" (-ing = que causa interés).',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Insistió en pagar la cena.',
  },
  {
    id: 'ec_044',
    sentence: 'She recommended me to read this book.',
    answer: 'She recommended that I read this book.',
    base_word: 'me to read',
    context_sentence: 'that I read',
    options: '["me to read","that I read","me reading","I to read"]',
    explanation: '"Recommend" + (that) + subject + bare infinitive. Not "recommend sb to do".',
    explanation_es: '"Recommend" + (that) + sujeto + infinitivo sin to. No "recommend sb to do".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Si hubiera sabido, habría venido antes.',
  },
  {
    id: 'ec_045',
    sentence: 'There was a lot of informations in the report.',
    answer: 'There was a lot of information in the report.',
    base_word: 'informations',
    context_sentence: 'information',
    options: '["informations","information","an information","the informations"]',
    explanation: '"Information" is uncountable in English — no plural form.',
    explanation_es: '"Information" es incontable en inglés — no tiene plural.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Me hizo esperar fuera una hora.',
  },
  {
    id: 'ec_046',
    sentence: 'He is enough old to drive.',
    answer: 'He is old enough to drive.',
    base_word: 'enough old',
    context_sentence: 'old enough',
    options: '["enough old","old enough","enough to old","old to enough"]',
    explanation: '"Enough" goes AFTER adjectives: "old enough", not "enough old".',
    explanation_es: '"Enough" va DESPUÉS de adjetivos: "old enough", no "enough old".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'A pesar del mal tiempo, el evento siguió adelante.',
  },
  {
    id: 'ec_047',
    sentence: 'I\'ve been waiting since two hours.',
    answer: 'I\'ve been waiting for two hours.',
    base_word: 'since',
    context_sentence: 'for',
    options: '["since","for","during","from"]',
    explanation: '"Since" + point in time. "For" + duration. "Two hours" is a duration.',
    explanation_es: '"Since" + punto. "For" + duración. "Two hours" es duración.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Me impidió salir de la habitación.',
  },
  {
    id: 'ec_048',
    sentence: 'She stopped to smoke last year.',
    answer: 'She stopped smoking last year.',
    base_word: 'to smoke',
    context_sentence: 'smoking',
    options: '["to smoke","smoking","smoke","for smoking"]',
    explanation: '"Stop + -ing" = quit. "Stop + to-inf" = stop in order to do something else.',
    explanation_es: '"Stop + -ing" = dejar de. "Stop + to-inf" = detenerse para hacer otra cosa.',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Ni el profesor ni los alumnos estaban contentos.',
  },
  {
    id: 'ec_049',
    sentence: 'I\'m agree that we should leave early.',
    answer: 'I agree that we should leave early.',
    base_word: "I'm agree",
    context_sentence: 'I agree',
    options: '["I\'m agree","I agree","I\'m agreed","I do agree"]',
    explanation: '"Agree" is a verb, not an adjective. Don\'t use "be" before it.',
    explanation_es: '"Agree" es un verbo, no un adjetivo. No se usa "be" delante.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Desearía poder hablar francés con fluidez.',
  },
  {
    id: 'ec_050',
    sentence: 'Each students must hand in their homework.',
    answer: 'Each student must hand in their homework.',
    base_word: 'students',
    context_sentence: 'student',
    options: '["students","student","a students","the students"]',
    explanation: '"Each" is followed by a singular noun: "each student".',
    explanation_es: '"Each" va seguido de sustantivo singular: "each student".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Admitió haber robado el dinero.',
  },
  {
    id: 'ec_051',
    sentence: 'She is capable to solve the problem.',
    answer: 'She is capable of solving the problem.',
    base_word: 'to solve',
    context_sentence: 'of solving',
    options: '["to solve","of solving","solving","for solving"]',
    explanation: '"Capable of + -ing" — not "capable to". Spanish interference: "capaz de".',
    explanation_es: '"Capable of + -ing" — no "capable to". Interferencia: "capaz de".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Rara vez he visto un atardecer tan bonito.',
  },
  {
    id: 'ec_052',
    sentence: 'I didn\'t used to like vegetables.',
    answer: 'I didn\'t use to like vegetables.',
    base_word: 'used',
    context_sentence: 'use',
    options: '["used","use","using","to use"]',
    explanation: 'After "didn\'t", use bare infinitive: "didn\'t use to" (not "didn\'t used to").',
    explanation_es: 'Tras "didn\'t", infinitivo sin to: "didn\'t use to" (no "didn\'t used to").',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Los muebles de la habitación son muy viejos.',
  },
  {
    id: 'ec_053',
    sentence: 'I need that you help me with this.',
    answer: 'I need you to help me with this.',
    base_word: 'that you help',
    context_sentence: 'you to help',
    options: '["that you help","you to help","you helping","that you to help"]',
    explanation: '"Need" + object + to-infinitive. Not "need that...".',
    explanation_es: '"Need" + objeto + to-infinitivo. No "need that...".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Me acusó de romper la ventana.',
  },
  {
    id: 'ec_054',
    sentence: 'We arrived to the airport just in time.',
    answer: 'We arrived at the airport just in time.',
    base_word: 'to',
    context_sentence: 'at',
    options: '["to","at","in","on"]',
    explanation: '"Arrive AT" a building/place. "Arrive IN" a city/country. Not "arrive to".',
    explanation_es: '"Arrive AT" un edificio/lugar. "Arrive IN" ciudad/país. No "arrive to".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Hay menos coches en la carretera hoy.',
  },
  {
    id: 'ec_055',
    sentence: 'She complained about to have too much work.',
    answer: 'She complained about having too much work.',
    base_word: 'to have',
    context_sentence: 'having',
    options: '["to have","having","have","to having"]',
    explanation: 'After preposition "about" → gerund. Not "about to have".',
    explanation_es: 'Tras preposición "about" → gerundio. No "about to have".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    answer_es: 'Me felicitó por aprobar el examen.',
  },
  {
    id: 'ec_056',
    sentence: 'I have a very good work.',
    answer: 'I have a very good job.',
    base_word: 'work',
    context_sentence: 'job',
    options: '["work","job","working","employment"]',
    explanation: '"Job" = a specific position (countable). "Work" = activity/effort (uncountable).',
    explanation_es: '"Job" = puesto específico (contable). "Work" = actividad/esfuerzo (incontable).',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Negó haber estado involucrado.',
  },
  {
    id: 'ec_057',
    sentence: 'He\'s lived here since a long time.',
    answer: 'He\'s lived here for a long time.',
    base_word: 'since',
    context_sentence: 'for',
    options: '["since","for","during","from"]',
    explanation: '"A long time" is a duration → "for". "Since" needs a point in time.',
    explanation_es: '"A long time" es duración → "for". "Since" necesita punto en el tiempo.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Preferiría quedarme en casa esta noche.',
  },
  {
    id: 'ec_058',
    sentence: 'He told to me that he was leaving.',
    answer: 'He told me that he was leaving.',
    base_word: 'told to me',
    context_sentence: 'told me',
    options: '["told to me","told me","said me","told for me"]',
    explanation: '"Tell" takes a direct object without "to": "tell me", not "tell to me".',
    explanation_es: '"Tell" lleva objeto directo sin "to": "tell me", no "tell to me".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Bajo ninguna circunstancia deberías abrir esta puerta.',
  },
  {
    id: 'ec_059',
    sentence: 'Hardly he had arrived when the meeting started.',
    answer: 'Hardly had he arrived when the meeting started.',
    base_word: 'he had',
    context_sentence: 'had he',
    options: '["he had","had he","he has","has he"]',
    explanation: '"Hardly" at the start → inversion: "Hardly had he...".',
    explanation_es: '"Hardly" al inicio → inversión: "Hardly had he...".',
    cefr_level: 'C1', category: 'error_correction', difficulty: 3,
    answer_es: 'Le dije que no lo hiciera.',
  },
  {
    id: 'ec_060',
    sentence: 'She gave me an useful advice.',
    answer: 'She gave me useful advice.',
    base_word: 'an useful advice',
    context_sentence: 'useful advice',
    options: '["an useful advice","useful advice","a useful advice","an useful advise"]',
    explanation: '"Advice" is uncountable — no article "a/an". Also: "useful" starts with /j/ → "a", not "an".',
    explanation_es: '"Advice" es incontable — sin artículo "a/an". Además: "useful" empieza con /j/ → "a", no "an".',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    answer_es: 'Ella me sugirió que fuera al médico.',
  },
];
