// Cambridge-style gap-fill exercises for connectors
// Options are real distractors from Cambridge Use of English (Part 1/2)
// sentence uses ___ as the gap placeholder

export interface GapFillSeedItem {
  id: string;
  sentence: string;
  answer: string;
  options: string; // JSON array of 4 options
  explanation: string;
  explanation_es: string;
  cefr_level: string;
  category: string;
  difficulty: number;
  answer_es?: string;
  base_word?: string; // frase completa para el chip (p.ej. "set up" en ejercicios de partícula)
}

export const GAP_FILL_CONNECTORS: GapFillSeedItem[] = [
  // ── B1 (difficulty 1) ──
  {
    id: 'gf_conn_001',
    sentence: 'I wanted to go out, ___ it was raining heavily.',
    answer: 'but',
    options: '["but","so","because","although"]',
    explanation: '"But" introduces a contrast between wanting to go out and the rain.',
    explanation_es: '"But" introduce un contraste entre querer salir y la lluvia.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'pero',
  },
  {
    id: 'gf_conn_002',
    sentence: 'She studied very hard, ___ she passed the exam easily.',
    answer: 'so',
    options: '["so","but","although","despite"]',
    explanation: '"So" shows the result of studying hard.',
    explanation_es: '"So" muestra el resultado de estudiar mucho.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'así que / por lo tanto',
  },
  {
    id: 'gf_conn_003',
    sentence: 'We went for a walk ___ the cold weather.',
    answer: 'despite',
    options: '["despite","although","because","however"]',
    explanation: '"Despite" + noun/gerund expresses contrast. "Although" needs a clause.',
    explanation_es: '"Despite" + sustantivo/gerundio expresa contraste. "Although" necesita una oración.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'a pesar de',
  },
  {
    id: 'gf_conn_004',
    sentence: 'I enjoy playing tennis. ___, I like swimming.',
    answer: 'Also',
    options: '["Also","However","Therefore","Instead"]',
    explanation: '"Also" adds similar information to the previous statement.',
    explanation_es: '"Also" añade información similar a la oración anterior.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'también',
  },
  {
    id: 'gf_conn_005',
    sentence: '___ it was late, we decided to continue working.',
    answer: 'Although',
    options: '["Although","Despite","However","Because"]',
    explanation: '"Although" + clause introduces a concession.',
    explanation_es: '"Although" + oración introduce una concesión.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'aunque',
  },
  {
    id: 'gf_conn_006',
    sentence: 'He didn\'t study. ___, he failed the test.',
    answer: 'Therefore',
    options: '["Therefore","However","Although","Moreover"]',
    explanation: '"Therefore" introduces a logical consequence.',
    explanation_es: '"Therefore" introduce una consecuencia lógica.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'por lo tanto',
  },
  {
    id: 'gf_conn_007',
    sentence: 'I\'ll go to the party ___ I finish my homework first.',
    answer: 'as long as',
    options: '["as long as","in spite of","even though","in addition"]',
    explanation: '"As long as" sets a condition that must be met.',
    explanation_es: '"As long as" establece una condición que debe cumplirse.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'siempre que / con tal de que',
  },
  {
    id: 'gf_conn_008',
    sentence: 'The restaurant was expensive. ___, the food was excellent.',
    answer: 'However',
    options: '["However","Therefore","Furthermore","Meanwhile"]',
    explanation: '"However" introduces a contrasting point.',
    explanation_es: '"However" introduce un punto de contraste.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'sin embargo',
  },
  {
    id: 'gf_conn_009',
    sentence: 'You can have tea ___ coffee. Which do you prefer?',
    answer: 'or',
    options: '["or","and","but","nor"]',
    explanation: '"Or" presents alternatives to choose from.',
    explanation_es: '"Or" presenta alternativas entre las que elegir.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'o',
  },
  {
    id: 'gf_conn_010',
    sentence: 'She speaks French ___ German fluently.',
    answer: 'and',
    options: '["and","but","or","yet"]',
    explanation: '"And" connects two equal items (both languages).',
    explanation_es: '"And" conecta dos elementos iguales (ambos idiomas).',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'y',
  },
  // ── B1–B2 (difficulty 2) ──
  {
    id: 'gf_conn_011',
    sentence: '___ the fact that he was tired, he kept running.',
    answer: 'Despite',
    options: '["Despite","Although","However","While"]',
    explanation: '"Despite the fact that" = "although" but uses despite + noun phrase.',
    explanation_es: '"Despite the fact that" = "although" pero usa despite + sintagma nominal.',
    cefr_level: 'B1', category: 'connector', difficulty: 2,
    answer_es: 'a pesar de',
  },
  {
    id: 'gf_conn_012',
    sentence: 'The hotel was lovely. ___, the location was perfect.',
    answer: 'Furthermore',
    options: '["Furthermore","However","Nevertheless","Instead"]',
    explanation: '"Furthermore" adds an extra positive point.',
    explanation_es: '"Furthermore" añade un punto positivo adicional.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'además',
  },
  {
    id: 'gf_conn_013',
    sentence: 'He didn\'t get the job. ___, he remained optimistic.',
    answer: 'Nevertheless',
    options: '["Nevertheless","Therefore","Consequently","Furthermore"]',
    explanation: '"Nevertheless" = despite that, introducing an unexpected continuation.',
    explanation_es: '"Nevertheless" = a pesar de eso, introduce una continuación inesperada.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'no obstante / sin embargo',
  },
  {
    id: 'gf_conn_014',
    sentence: 'The project was delayed ___ a lack of funding.',
    answer: 'due to',
    options: '["due to","although","however","in addition to"]',
    explanation: '"Due to" + noun gives the reason/cause.',
    explanation_es: '"Due to" + sustantivo da la razón/causa.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'debido a',
  },
  {
    id: 'gf_conn_015',
    sentence: 'She\'s very talented. ___, she works extremely hard.',
    answer: 'Moreover',
    options: '["Moreover","However","Otherwise","Instead"]',
    explanation: '"Moreover" adds emphasis to an additional point.',
    explanation_es: '"Moreover" añade énfasis a un punto adicional.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'además / es más',
  },
  {
    id: 'gf_conn_016',
    sentence: 'You should leave now; ___, you\'ll miss the train.',
    answer: 'otherwise',
    options: '["otherwise","furthermore","however","moreover"]',
    explanation: '"Otherwise" presents a negative consequence of not acting.',
    explanation_es: '"Otherwise" presenta una consecuencia negativa de no actuar.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'de lo contrario',
  },
  {
    id: 'gf_conn_017',
    sentence: 'I called several times. ___, nobody answered.',
    answer: 'However',
    options: '["However","Therefore","Moreover","As a result"]',
    explanation: '"However" signals an unexpected contrast.',
    explanation_es: '"However" señala un contraste inesperado.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'sin embargo',
  },
  {
    id: 'gf_conn_018',
    sentence: '___ he apologised, she refused to forgive him.',
    answer: 'Even though',
    options: '["Even though","Because","Since","Due to"]',
    explanation: '"Even though" + clause emphasises a strong concession.',
    explanation_es: '"Even though" + oración enfatiza una concesión fuerte.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'aunque / a pesar de que',
  },
  {
    id: 'gf_conn_019',
    sentence: 'I like living in the city. ___, I enjoy country walks.',
    answer: 'On the other hand',
    options: '["On the other hand","As a result","In addition","For instance"]',
    explanation: '"On the other hand" introduces an alternative viewpoint.',
    explanation_es: '"On the other hand" introduce un punto de vista alternativo.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'por otro lado',
  },
  {
    id: 'gf_conn_020',
    sentence: 'The weather was terrible. ___, we decided to stay indoors.',
    answer: 'As a result',
    options: '["As a result","On the other hand","In contrast","For example"]',
    explanation: '"As a result" introduces a consequence.',
    explanation_es: '"As a result" introduce una consecuencia.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'como resultado',
  },
  // ── B2 (difficulty 2) ──
  {
    id: 'gf_conn_021',
    sentence: 'Tom is very outgoing, ___ his brother is quite shy.',
    answer: 'whereas',
    options: '["whereas","moreover","therefore","likewise"]',
    explanation: '"Whereas" shows a direct contrast between two subjects.',
    explanation_es: '"Whereas" muestra un contraste directo entre dos sujetos.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'mientras que',
  },
  {
    id: 'gf_conn_022',
    sentence: '___ you study consistently, you won\'t improve.',
    answer: 'Unless',
    options: '["Unless","Although","While","Since"]',
    explanation: '"Unless" = if not. It sets a negative condition.',
    explanation_es: '"Unless" = si no. Establece una condición negativa.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'a menos que',
  },
  {
    id: 'gf_conn_023',
    sentence: 'The museum was closed. We visited the gallery ___.',
    answer: 'instead',
    options: '["instead","moreover","however","likewise"]',
    explanation: '"Instead" shows a substitution — one thing replaces another.',
    explanation_es: '"Instead" muestra una sustitución — una cosa reemplaza a otra.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'en su lugar / en vez de',
  },
  {
    id: 'gf_conn_024',
    sentence: 'She has many qualities; ___, she is very patient.',
    answer: 'for instance',
    options: '["for instance","however","on the contrary","as a result"]',
    explanation: '"For instance" introduces a specific example.',
    explanation_es: '"For instance" introduce un ejemplo específico.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'por ejemplo',
  },
  {
    id: 'gf_conn_025',
    sentence: 'He was promoted ___ his excellent performance.',
    answer: 'owing to',
    options: '["owing to","in spite of","regardless of","rather than"]',
    explanation: '"Owing to" + noun means "because of" (formal).',
    explanation_es: '"Owing to" + sustantivo significa "debido a" (formal).',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'debido a',
  },
  // ── B2–C1 (difficulty 3) ──
  {
    id: 'gf_conn_026',
    sentence: 'The plan failed, not because of poor execution, but ___ because it was flawed from the start.',
    answer: 'rather',
    options: '["rather","however","moreover","despite"]',
    explanation: '"Rather" corrects or refines a previous statement.',
    explanation_es: '"Rather" corrige o matiza una afirmación anterior.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'más bien',
  },
  {
    id: 'gf_conn_027',
    sentence: '___ of the weather conditions, the match will go ahead.',
    answer: 'Regardless',
    options: '["Regardless","In spite","Despite","Although"]',
    explanation: '"Regardless of" means it doesn\'t matter what the conditions are.',
    explanation_es: '"Regardless of" significa que no importan las condiciones.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'independientemente de',
  },
  {
    id: 'gf_conn_028',
    sentence: 'The company is expanding. ___, it plans to hire 200 new employees.',
    answer: 'Accordingly',
    options: '["Accordingly","Conversely","Alternatively","Notwithstanding"]',
    explanation: '"Accordingly" means "in response to that" or "therefore" (formal).',
    explanation_es: '"Accordingly" significa "en consecuencia" o "por tanto" (formal).',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'en consecuencia',
  },
  {
    id: 'gf_conn_029',
    sentence: 'Profits increased last quarter; ___, the number of customers declined.',
    answer: 'conversely',
    options: '["conversely","consequently","similarly","additionally"]',
    explanation: '"Conversely" introduces an opposite trend or situation.',
    explanation_es: '"Conversely" introduce una tendencia o situación opuesta.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'por el contrario',
  },
  {
    id: 'gf_conn_030',
    sentence: 'You may take the written exam. ___, you could do an oral presentation.',
    answer: 'Alternatively',
    options: '["Alternatively","Furthermore","Similarly","Consequently"]',
    explanation: '"Alternatively" presents another option.',
    explanation_es: '"Alternatively" presenta otra opción.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'alternativamente / como alternativa',
  },
  {
    id: 'gf_conn_031',
    sentence: 'The evidence was weak. ___, the jury found him guilty.',
    answer: 'Nonetheless',
    options: '["Nonetheless","Therefore","Consequently","Likewise"]',
    explanation: '"Nonetheless" = nevertheless, introduces an unexpected outcome.',
    explanation_es: '"Nonetheless" = sin embargo, introduce un resultado inesperado.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'no obstante',
  },
  {
    id: 'gf_conn_032',
    sentence: '___ having little experience, she impressed the interview panel.',
    answer: 'Despite',
    options: '["Despite","Although","However","Whereas"]',
    explanation: '"Despite" + gerund (-ing) expresses concession.',
    explanation_es: '"Despite" + gerundio (-ing) expresa concesión.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'a pesar de',
  },
  {
    id: 'gf_conn_033',
    sentence: 'The course was demanding. ___, I learnt a great deal.',
    answer: 'Nonetheless',
    options: '["Nonetheless","Therefore","As a result","In addition"]',
    explanation: '"Nonetheless" signals a positive outcome despite difficulty.',
    explanation_es: '"Nonetheless" señala un resultado positivo pese a la dificultad.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'no obstante',
  },
  {
    id: 'gf_conn_034',
    sentence: 'Both approaches are valid. ___, they have very different outcomes.',
    answer: 'However',
    options: '["However","Therefore","Similarly","Likewise"]',
    explanation: '"However" contrasts validity with different outcomes.',
    explanation_es: '"However" contrasta la validez con diferentes resultados.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'sin embargo',
  },
  {
    id: 'gf_conn_035',
    sentence: 'She moved to London ___ to find better career opportunities.',
    answer: 'in order',
    options: '["in order","as long as","in case","even though"]',
    explanation: '"In order to" expresses purpose.',
    explanation_es: '"In order to" expresa propósito.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'para / con el fin de',
  },
  {
    id: 'gf_conn_036',
    sentence: 'Take an umbrella ___ it rains later.',
    answer: 'in case',
    options: '["in case","unless","although","so that"]',
    explanation: '"In case" prepares for a possible future situation.',
    explanation_es: '"In case" prepara ante una posible situación futura.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'por si acaso',
  },
  {
    id: 'gf_conn_037',
    sentence: '___ the salary is low, the job offers great experience.',
    answer: 'While',
    options: '["While","Because","Since","As a result"]',
    explanation: '"While" introduces a concession (= although).',
    explanation_es: '"While" introduce una concesión (= although).',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'mientras / aunque',
  },
  {
    id: 'gf_conn_038',
    sentence: 'He trained every day. ___, he won the competition.',
    answer: 'Consequently',
    options: '["Consequently","Nevertheless","Alternatively","Conversely"]',
    explanation: '"Consequently" shows a direct cause-effect relationship.',
    explanation_es: '"Consequently" muestra una relación directa causa-efecto.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'en consecuencia',
  },
  {
    id: 'gf_conn_039',
    sentence: '___ to popular belief, bats are not blind.',
    answer: 'Contrary',
    options: '["Contrary","According","Due","Owing"]',
    explanation: '"Contrary to" means the opposite of what people think.',
    explanation_es: '"Contrary to" significa lo contrario de lo que la gente piensa.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'contrariamente',
  },
  {
    id: 'gf_conn_040',
    sentence: 'The experiment failed. ___, the data collected proved useful for future research.',
    answer: 'Nevertheless',
    options: '["Nevertheless","Therefore","Consequently","Furthermore"]',
    explanation: '"Nevertheless" introduces a positive contrast despite failure.',
    explanation_es: '"Nevertheless" introduce un contraste positivo pese al fracaso.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'no obstante / sin embargo',
  },
  // ── Additional connectors B1–C1 ──
  {
    id: 'gf_conn_041',
    sentence: 'She was exhausted. ___, she continued working until midnight.',
    answer: 'Even so',
    options: '["Even so","As a result","In addition","For instance"]',
    explanation: '"Even so" = despite that (concession).',
    explanation_es: '"Even so" = a pesar de eso (concesión).',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'aun así',
  },
  {
    id: 'gf_conn_042',
    sentence: 'The hotel was expensive. ___, the service was poor.',
    answer: 'What is more',
    options: '["What is more","On the other hand","As a result","In contrast"]',
    explanation: '"What is more" adds a further negative point (= moreover/furthermore).',
    explanation_es: '"What is more" añade un punto negativo adicional (= además).',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'es más / lo que es más',
  },
  {
    id: 'gf_conn_043',
    sentence: '___ we leave now, we will miss the last train.',
    answer: 'Unless',
    options: '["Unless","Although","Because","While"]',
    explanation: '"Unless" = if not. Negative condition.',
    explanation_es: '"Unless" = si no. Condición negativa.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'a menos que',
  },
  {
    id: 'gf_conn_044',
    sentence: 'The food was delicious. ___, the atmosphere was wonderful.',
    answer: 'Moreover',
    options: '["Moreover","However","Otherwise","Instead"]',
    explanation: '"Moreover" adds a further positive point.',
    explanation_es: '"Moreover" añade otro punto positivo.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'además / es más',
  },
  {
    id: 'gf_conn_045',
    sentence: 'He studied medicine ___ order to become a doctor.',
    answer: 'in',
    options: '["in","on","for","by"]',
    explanation: '"In order to" = purpose / so as to.',
    explanation_es: '"In order to" = para / con el fin de.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'en',
  },
  {
    id: 'gf_conn_046',
    sentence: 'She likes classical music, ___ her brother prefers jazz.',
    answer: 'whereas',
    options: '["whereas","therefore","moreover","consequently"]',
    explanation: '"Whereas" shows a direct contrast between two facts.',
    explanation_es: '"Whereas" muestra un contraste directo entre dos hechos.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'mientras que',
  },
  {
    id: 'gf_conn_047',
    sentence: 'I will lend you the money ___ condition that you pay me back.',
    answer: 'on',
    options: '["on","in","at","by"]',
    explanation: '"On condition that" = provided that / as long as.',
    explanation_es: '"On condition that" = siempre que / con la condición de que.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'gf_conn_048',
    sentence: 'The roads were icy. ___, several accidents occurred.',
    answer: 'As a result',
    options: '["As a result","In contrast","On the other hand","For example"]',
    explanation: '"As a result" introduces a consequence.',
    explanation_es: '"As a result" introduce una consecuencia.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'como resultado',
  },
  {
    id: 'gf_conn_049',
    sentence: 'She speaks three languages. ___, she has extensive travel experience.',
    answer: 'In addition',
    options: '["In addition","However","Otherwise","Instead"]',
    explanation: '"In addition" adds extra information.',
    explanation_es: '"In addition" añade información extra.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'además',
  },
  {
    id: 'gf_conn_050',
    sentence: 'He didn\'t study at all. ___, he failed the exam.',
    answer: 'Not surprisingly',
    options: '["Not surprisingly","Nevertheless","On the contrary","In spite of this"]',
    explanation: '"Not surprisingly" = as expected, given the circumstances.',
    explanation_es: '"Not surprisingly" = como era de esperar, dadas las circunstancias.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'como era de esperar',
  },
  {
    id: 'gf_conn_051',
    sentence: 'The city has many parks. ___, it has excellent public transport.',
    answer: 'Furthermore',
    options: '["Furthermore","Nevertheless","Otherwise","Conversely"]',
    explanation: '"Furthermore" adds more supporting information.',
    explanation_es: '"Furthermore" añade más información de apoyo.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'además',
  },
  {
    id: 'gf_conn_052',
    sentence: 'You should book early. ___, you might not get a seat.',
    answer: 'Otherwise',
    options: '["Otherwise","Furthermore","Moreover","Likewise"]',
    explanation: '"Otherwise" = if not / or else.',
    explanation_es: '"Otherwise" = si no / de lo contrario.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'de lo contrario',
  },
  {
    id: 'gf_conn_053',
    sentence: '___ the heavy traffic, we arrived on time.',
    answer: 'In spite of',
    options: '["In spite of","Because of","Due to","Owing to"]',
    explanation: '"In spite of" = despite (+ noun / -ing). Shows unexpected result.',
    explanation_es: '"In spite of" = a pesar de (+ sustantivo / -ing). Resultado inesperado.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'a pesar de',
  },
  {
    id: 'gf_conn_054',
    sentence: 'The plan seemed risky. ___, everyone agreed to go ahead.',
    answer: 'Nonetheless',
    options: '["Nonetheless","Therefore","Hence","Accordingly"]',
    explanation: '"Nonetheless" = nevertheless / despite that.',
    explanation_es: '"Nonetheless" = sin embargo / a pesar de eso.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'no obstante',
  },
  {
    id: 'gf_conn_055',
    sentence: 'She works part-time. ___, she volunteers at the hospital.',
    answer: 'Additionally',
    options: '["Additionally","However","Instead","Conversely"]',
    explanation: '"Additionally" = also / in addition.',
    explanation_es: '"Additionally" = también / además.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'adicionalmente / además',
  },
  {
    id: 'gf_conn_056',
    sentence: 'I\'d like to help. ___, I just don\'t have enough time.',
    answer: 'Unfortunately',
    options: '["Unfortunately","Furthermore","Consequently","Similarly"]',
    explanation: '"Unfortunately" = expressing regret about a situation.',
    explanation_es: '"Unfortunately" = lamentablemente.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'desafortunadamente',
  },
  {
    id: 'gf_conn_057',
    sentence: 'She is a talented musician. ___, she is an excellent painter.',
    answer: 'Likewise',
    options: '["Likewise","However","Therefore","Instead"]',
    explanation: '"Likewise" = in the same way / similarly.',
    explanation_es: '"Likewise" = del mismo modo / igualmente.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'igualmente / del mismo modo',
  },
  {
    id: 'gf_conn_058',
    sentence: 'He was offered a promotion. He turned it down, ___.',
    answer: 'though',
    options: '["though","therefore","moreover","hence"]',
    explanation: '"Though" at the end of a sentence = however (informal concession).',
    explanation_es: '"Though" al final de la frase = sin embargo (concesión informal).',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'aunque / sin embargo',
  },
  {
    id: 'gf_conn_059',
    sentence: 'The evidence was overwhelming. ___, the jury found him guilty.',
    answer: 'Accordingly',
    options: '["Accordingly","Nevertheless","Conversely","Alternatively"]',
    explanation: '"Accordingly" = therefore / as a result (formal).',
    explanation_es: '"Accordingly" = por lo tanto / en consecuencia (formal).',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'en consecuencia',
  },
  {
    id: 'gf_conn_060',
    sentence: 'You can take the bus. ___, you could walk — it\'s only ten minutes.',
    answer: 'Alternatively',
    options: '["Alternatively","Moreover","Therefore","Nevertheless"]',
    explanation: '"Alternatively" introduces another option.',
    explanation_es: '"Alternatively" introduce otra opción.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'alternativamente / como alternativa',
  },
  {
    id: 'gf_conn_061',
    sentence: '___ the fact that he apologised, she was still angry.',
    answer: 'Despite',
    options: '["Despite","Because of","Due to","Thanks to"]',
    explanation: '"Despite the fact that" = although.',
    explanation_es: '"Despite the fact that" = aunque.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'a pesar de',
  },
  {
    id: 'gf_conn_062',
    sentence: 'The project was a success ___ to the team\'s hard work.',
    answer: 'thanks',
    options: '["thanks","due","owing","according"]',
    explanation: '"Thanks to" = because of (positive cause).',
    explanation_es: '"Thanks to" = gracias a (causa positiva).',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'gracias a',
  },
  {
    id: 'gf_conn_063',
    sentence: 'I enjoy tennis. My sister, ___ the other hand, prefers swimming.',
    answer: 'on',
    options: '["on","in","at","by"]',
    explanation: '"On the other hand" introduces a contrasting point.',
    explanation_es: '"On the other hand" introduce un punto contrastante.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'en',
  },
  {
    id: 'gf_conn_064',
    sentence: 'He apologised. ___, the damage had already been done.',
    answer: 'By that time',
    options: '["By that time","Furthermore","In addition","As well"]',
    explanation: '"By that time" = before that moment (temporal sequence).',
    explanation_es: '"By that time" = para entonces (secuencia temporal).',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'para entonces',
  },
  {
    id: 'gf_conn_065',
    sentence: '___ it may seem difficult, the task is actually straightforward.',
    answer: 'Although',
    options: '["Although","Because","Since","Therefore"]',
    explanation: '"Although" introduces a concession (= even though).',
    explanation_es: '"Although" introduce una concesión (= aunque).',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'aunque',
  },
  {
    id: 'gf_conn_066',
    sentence: 'She didn\'t get the job. ___, she remained positive.',
    answer: 'All the same',
    options: '["All the same","As a result","For this reason","In conclusion"]',
    explanation: '"All the same" = nevertheless / despite that.',
    explanation_es: '"All the same" = aun así / a pesar de eso.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'de todos modos',
  },
  {
    id: 'gf_conn_067',
    sentence: 'The restaurant was fully booked. ___, we found another one nearby.',
    answer: 'Fortunately',
    options: '["Fortunately","Therefore","Moreover","Instead"]',
    explanation: '"Fortunately" = luckily.',
    explanation_es: '"Fortunately" = afortunadamente.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'afortunadamente',
  },
  {
    id: 'gf_conn_068',
    sentence: 'He didn\'t just pass — he came first. ___ other words, he was the best student.',
    answer: 'In',
    options: '["In","On","At","By"]',
    explanation: '"In other words" = to put it differently / that is to say.',
    explanation_es: '"In other words" = en otras palabras / es decir.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'gf_conn_069',
    sentence: 'The weather was terrible. We went to the beach ___ the same.',
    answer: 'all',
    options: '["all","at","in","on"]',
    explanation: '"All the same" = nonetheless / despite that.',
    explanation_es: '"All the same" = aun así / a pesar de todo.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'todo / en absoluto',
  },
  {
    id: 'gf_conn_070',
    sentence: 'The salary is low. ___, the working conditions are excellent.',
    answer: 'On the other hand',
    options: '["On the other hand","As a result","In addition","For example"]',
    explanation: '"On the other hand" presents an opposing view.',
    explanation_es: '"On the other hand" presenta una opinión opuesta.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'por otro lado',
  },
  {
    id: 'gf_conn_071',
    sentence: 'First, preheat the oven. ___, prepare the ingredients.',
    answer: 'Meanwhile',
    options: '["Meanwhile","However","Therefore","Nonetheless"]',
    explanation: '"Meanwhile" = at the same time / during that time.',
    explanation_es: '"Meanwhile" = mientras tanto / durante ese tiempo.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'mientras tanto',
  },
  {
    id: 'gf_conn_072',
    sentence: 'She is very talented. ___, she needs more practice.',
    answer: 'Having said that',
    options: '["Having said that","In addition","Furthermore","Likewise"]',
    explanation: '"Having said that" = however / but (introduces a qualification).',
    explanation_es: '"Having said that" = dicho esto / sin embargo (introduce una matización).',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'dicho esto',
  },
  {
    id: 'gf_conn_073',
    sentence: '___ a consequence of the storm, flights were cancelled.',
    answer: 'As',
    options: '["As","In","By","For"]',
    explanation: '"As a consequence of" = because of / as a result of.',
    explanation_es: '"As a consequence of" = como consecuencia de.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    answer_es: 'como / ya que',
  },
  {
    id: 'gf_conn_074',
    sentence: 'The project has many benefits. ___, it creates jobs and boosts the economy.',
    answer: 'For instance',
    options: '["For instance","However","Nevertheless","Conversely"]',
    explanation: '"For instance" = for example.',
    explanation_es: '"For instance" = por ejemplo.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'por ejemplo',
  },
  {
    id: 'gf_conn_075',
    sentence: 'She spoke very quietly ___ that nobody else could hear.',
    answer: 'so',
    options: '["so","such","in order","because"]',
    explanation: '"So that" = in order that (purpose clause).',
    explanation_es: '"So that" = para que (cláusula de propósito).',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'así que / por lo tanto',
  },
  {
    id: 'gf_conn_076',
    sentence: 'Pollution is increasing. ___, urgent action is needed.',
    answer: 'Hence',
    options: '["Hence","Nevertheless","Conversely","Alternatively"]',
    explanation: '"Hence" = therefore / for this reason (formal).',
    explanation_es: '"Hence" = por lo tanto / por esta razón (formal).',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'de ahí / por lo tanto',
  },
  {
    id: 'gf_conn_077',
    sentence: 'The plan has advantages. ___, there are significant risks.',
    answer: 'That said',
    options: '["That said","Moreover","In addition","Furthermore"]',
    explanation: '"That said" = however / nevertheless (introduces a caveat).',
    explanation_es: '"That said" = dicho esto / sin embargo (introduce una salvedad).',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'dicho esto',
  },
  {
    id: 'gf_conn_078',
    sentence: 'She was late ___ to the traffic jam on the motorway.',
    answer: 'due',
    options: '["due","thanks","owing","according"]',
    explanation: '"Due to" = because of.',
    explanation_es: '"Due to" = debido a.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'debido a',
  },
  {
    id: 'gf_conn_079',
    sentence: '___ to what many people think, sharks rarely attack humans.',
    answer: 'Contrary',
    options: '["Contrary","According","Due","Similar"]',
    explanation: '"Contrary to" = opposite to what is expected.',
    explanation_es: '"Contrary to" = contrariamente a lo esperado.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    answer_es: 'contrariamente',
  },
  {
    id: 'gf_conn_080',
    sentence: 'He lost his job last month. ___ then, he has been looking for work.',
    answer: 'Since',
    options: '["Since","From","After","Until"]',
    explanation: '"Since then" = from that point until now.',
    explanation_es: '"Since then" = desde entonces hasta ahora.',
    cefr_level: 'B1', category: 'connector', difficulty: 1,
    answer_es: 'ya que / desde',
  },
];
