// Cambridge Use of English Part 4 — Key Word Transformation
// Given an original sentence + keyword, rewrite using that keyword
// sentence = target with gap, context_sentence = original, base_word = keyword

export interface KeyWordTransformSeedItem {
  id: string;
  sentence: string;         // Target sentence with ___
  answer: string;            // What fills the gap
  options: string | null;
  explanation: string;
  explanation_es: string;
  cefr_level: string;
  category: string;
  difficulty: number;
  base_word: string;         // The keyword
  context_sentence: string;  // The original sentence
  answer_es?: string;
}

export const KEY_WORD_TRANSFORM_EXERCISES: KeyWordTransformSeedItem[] = [
  // ── B1–B2 (difficulty 1–2) ──
  {
    id: 'kwt_001',
    context_sentence: 'I last saw her three years ago.',
    base_word: 'SINCE',
    sentence: 'It ___ I last saw her.',
    answer: "has been three years since",
    options: null,
    explanation: '"Three years ago" → "It has been three years since..." restructures around SINCE.',
    explanation_es: '"Three years ago" → "It has been three years since..." reestructura con SINCE.',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'hace tres años desde',
  },
  {
    id: 'kwt_002',
    context_sentence: 'It was such a boring film that we left early.',
    base_word: 'SO',
    sentence: 'The film ___ we left early.',
    answer: 'was so boring that',
    options: null,
    explanation: 'such + noun phrase → so + adjective. "Such a boring film" → "so boring".',
    explanation_es: 'such + sintagma nominal → so + adjetivo.',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'era tan aburrida que',
  },
  {
    id: 'kwt_003',
    context_sentence: "They couldn't afford to buy the house.",
    base_word: 'EXPENSIVE',
    sentence: 'The house ___ them to buy.',
    answer: 'was too expensive for',
    options: null,
    explanation: '"Couldn\'t afford" → "too expensive for (someone) to".',
    explanation_es: '"Couldn\'t afford" → "too expensive for (alguien) to".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'era demasiado caro para',
  },
  {
    id: 'kwt_004',
    context_sentence: '"Don\'t touch that!", she said to him.',
    base_word: 'TOLD',
    sentence: 'She ___ touch that.',
    answer: 'told him not to',
    options: null,
    explanation: 'Direct speech → reported speech with "told". Negative imperative → "told sb not to".',
    explanation_es: 'Estilo directo → indirecto con "told". Imperativo negativo → "told sb not to".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'le dijo que no',
  },
  {
    id: 'kwt_005',
    context_sentence: 'I started learning English five years ago.',
    base_word: 'BEEN',
    sentence: 'I ___ English for five years.',
    answer: 'have been learning',
    options: null,
    explanation: '"Started + ago" → present perfect continuous with "for".',
    explanation_es: '"Started + ago" → presente perfecto continuo con "for".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'lleva aprendiendo',
  },
  {
    id: 'kwt_006',
    context_sentence: 'Perhaps she missed the train.',
    base_word: 'MIGHT',
    sentence: 'She ___ the train.',
    answer: 'might have missed',
    options: null,
    explanation: '"Perhaps" + past → modal "might have" + past participle for past possibility.',
    explanation_es: '"Perhaps" + pasado → "might have" + participio para posibilidad pasada.',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'puede que haya perdido',
  },
  {
    id: 'kwt_007',
    context_sentence: "It isn't necessary for you to come tomorrow.",
    base_word: 'NEED',
    sentence: 'You ___ come tomorrow.',
    answer: "don't need to",
    options: null,
    explanation: '"It isn\'t necessary" → "don\'t need to".',
    explanation_es: '"It isn\'t necessary" → "don\'t need to".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'no es necesario que',
  },
  {
    id: 'kwt_008',
    context_sentence: 'He regrets not studying harder.',
    base_word: 'WISHES',
    sentence: 'He ___ harder.',
    answer: 'wishes he had studied',
    options: null,
    explanation: '"Regrets not doing" → "wishes + past perfect" for past regrets.',
    explanation_es: '"Regrets not doing" → "wishes + pluscuamperfecto" para arrepentimientos.',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'desearía haber estudiado',
  },
  {
    id: 'kwt_009',
    context_sentence: 'The last time I went swimming was in June.',
    base_word: 'SINCE',
    sentence: 'I ___ June.',
    answer: "haven't been swimming since",
    options: null,
    explanation: '"The last time" + past → present perfect negative + "since".',
    explanation_es: '"The last time" + pasado → presente perfecto negativo + "since".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'no la he visto desde',
  },
  {
    id: 'kwt_010',
    context_sentence: 'Somebody stole my bicycle yesterday.',
    base_word: 'HAD',
    sentence: 'I ___ yesterday.',
    answer: 'had my bicycle stolen',
    options: null,
    explanation: 'Active → causative passive: "have something done" (unpleasant experience).',
    explanation_es: 'Activa → pasiva causativa: "have something done" (experiencia negativa).',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'me robaron la bicicleta',
  },
  // ── B2 (difficulty 2) ──
  {
    id: 'kwt_011',
    context_sentence: 'I think you should apologise to her.',
    base_word: 'WERE',
    sentence: 'If ___ apologise to her.',
    answer: 'I were you, I would',
    options: null,
    explanation: '"I think you should" → "If I were you, I would" (second conditional for advice).',
    explanation_es: '"I think you should" → "If I were you, I would" (segundo condicional para consejo).',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'yo que tú, yo',
  },
  {
    id: 'kwt_012',
    context_sentence: 'She is too young to drive.',
    base_word: 'ENOUGH',
    sentence: 'She ___ to drive.',
    answer: 'is not old enough',
    options: null,
    explanation: '"Too young" → "not old enough". Adjective + enough (after the adjective).',
    explanation_es: '"Too young" → "not old enough". Adjetivo + enough (después del adjetivo).',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'no tiene edad suficiente',
  },
  {
    id: 'kwt_013',
    context_sentence: "We won't go unless the weather improves.",
    base_word: 'ONLY',
    sentence: 'We will ___ the weather improves.',
    answer: 'only go if',
    options: null,
    explanation: '"Unless" (= if not) → "only if" (positive condition).',
    explanation_es: '"Unless" (= si no) → "only if" (condición positiva).',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'solo voy si',
  },
  {
    id: 'kwt_014',
    context_sentence: 'Nobody has complained about the noise.',
    base_word: 'ANY',
    sentence: 'There ___ about the noise.',
    answer: "haven't been any complaints",
    options: null,
    explanation: '"Nobody has complained" → "There haven\'t been any complaints" (verb → noun).',
    explanation_es: '"Nobody has complained" → "There haven\'t been any complaints" (verbo → sustantivo).',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'preferiría quedarme en casa',
  },
  {
    id: 'kwt_015',
    context_sentence: "I'd prefer to stay at home rather than go out.",
    base_word: 'RATHER',
    sentence: 'I ___ than go out.',
    answer: 'would rather stay at home',
    options: null,
    explanation: '"I\'d prefer to" → "I would rather" + bare infinitive.',
    explanation_es: '"I\'d prefer to" → "I would rather" + infinitivo sin to.',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'se dice que está perdiendo',
  },
  // ── B2–C1 (difficulty 3) ──
  {
    id: 'kwt_016',
    context_sentence: "People say the company is losing money.",
    base_word: 'SAID',
    sentence: 'The company ___ money.',
    answer: 'is said to be losing',
    options: null,
    explanation: '"People say + clause" → passive reporting: "is said to be + -ing".',
    explanation_es: '"People say + oración" → pasiva impersonal: "is said to be + -ing".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'no tenía idea de lo difícil',
  },
  {
    id: 'kwt_017',
    context_sentence: 'She didn\'t realise how difficult the exam would be.',
    base_word: 'IDEA',
    sentence: 'She ___ the exam would be.',
    answer: 'had no idea how difficult',
    options: null,
    explanation: '"Didn\'t realise" → "had no idea".',
    explanation_es: '"Didn\'t realise" → "had no idea".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'puede que haya olvidado',
  },
  {
    id: 'kwt_018',
    context_sentence: "It's possible that he forgot about the meeting.",
    base_word: 'MAY',
    sentence: 'He ___ about the meeting.',
    answer: 'may have forgotten',
    options: null,
    explanation: '"It\'s possible that" + past → "may have" + past participle.',
    explanation_es: '"It\'s possible that" + pasado → "may have" + participio.',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'no puede haber hecho trampa',
  },
  {
    id: 'kwt_019',
    context_sentence: "I'm sure she didn't do it on purpose.",
    base_word: 'HAVE',
    sentence: 'She ___ on purpose.',
    answer: "can't have done it",
    options: null,
    explanation: '"I\'m sure she didn\'t" → "can\'t have" + past participle (certainty about past).',
    explanation_es: '"I\'m sure she didn\'t" → "can\'t have" + participio (certeza sobre el pasado).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'está siendo construido',
  },
  {
    id: 'kwt_020',
    context_sentence: 'They are building a new hospital in the city centre.',
    base_word: 'BEING',
    sentence: 'A new hospital ___ in the city centre.',
    answer: 'is being built',
    options: null,
    explanation: 'Active present continuous → passive present continuous: "is being + past participle".',
    explanation_es: 'Activa presente continuo → pasiva presente continuo: "is being + participio".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'les hicieron reescribir',
  },
  {
    id: 'kwt_021',
    context_sentence: 'The teacher made us rewrite the essay.',
    base_word: 'MADE',
    sentence: 'We ___ the essay.',
    answer: 'were made to rewrite',
    options: null,
    explanation: '"Made us do" (active) → "were made to do" (passive). Note: passive "made" adds "to".',
    explanation_es: '"Made us do" (activa) → "were made to do" (pasiva). Nota: en pasiva "made" lleva "to".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'me impidió salir',
  },
  {
    id: 'kwt_022',
    context_sentence: "I couldn't sleep because the music was so loud.",
    base_word: 'PREVENTED',
    sentence: 'The loud music ___ sleeping.',
    answer: 'prevented me from',
    options: null,
    explanation: '"Couldn\'t sleep because" → "prevented sb from + -ing".',
    explanation_es: '"Couldn\'t sleep because" → "prevented sb from + -ing".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'parece haber sabido',
  },
  {
    id: 'kwt_023',
    context_sentence: "It seems that nobody knew the answer.",
    base_word: 'APPEAR',
    sentence: 'Nobody ___ the answer.',
    answer: 'appears to have known',
    options: null,
    explanation: '"It seems that + past" → "appears to have + past participle".',
    explanation_es: '"It seems that + pasado" → "appears to have + participio".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'si no me lo hubieras dicho, no',
  },
  {
    id: 'kwt_024',
    context_sentence: "I only found out the truth because she told me.",
    base_word: 'WOULD',
    sentence: 'If she ___ have found out the truth.',
    answer: "hadn't told me, I wouldn't",
    options: null,
    explanation: 'Third conditional: "If she hadn\'t told me, I wouldn\'t have found out".',
    explanation_es: 'Tercer condicional: "If she hadn\'t told me, I wouldn\'t have found out".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'permaneció en silencio durante',
  },
  {
    id: 'kwt_025',
    context_sentence: "He didn't say a word during the meeting.",
    base_word: 'REMAINED',
    sentence: 'He ___ the meeting.',
    answer: 'remained silent throughout',
    options: null,
    explanation: '"Didn\'t say a word" → "remained silent". "During" → "throughout".',
    explanation_es: '"Didn\'t say a word" → "remained silent". "During" → "throughout".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'ojalá me lo hubieras dicho',
  },
  {
    id: 'kwt_026',
    context_sentence: "You should have told me earlier.",
    base_word: 'WISH',
    sentence: 'I ___ me earlier.',
    answer: 'wish you had told',
    options: null,
    explanation: '"Should have done" (regret) → "I wish + past perfect".',
    explanation_es: '"Should have done" (arrepentimiento) → "I wish + pluscuamperfecto".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'se cree que se ha ido',
  },
  {
    id: 'kwt_027',
    context_sentence: "They say she left the country last week.",
    base_word: 'BELIEVED',
    sentence: 'She ___ the country last week.',
    answer: 'is believed to have left',
    options: null,
    explanation: '"They say + past" → passive reporting: "is believed to have + pp".',
    explanation_es: '"They say + pasado" → pasiva impersonal: "is believed to have + pp".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'le resulta difícil',
  },
  {
    id: 'kwt_028',
    context_sentence: "I'm not used to getting up early.",
    base_word: 'FIND',
    sentence: 'I ___ up early.',
    answer: 'find it hard getting',
    options: null,
    explanation: '"Not used to" → "find it hard/difficult + -ing".',
    explanation_es: '"Not used to" → "find it hard/difficult + -ing".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'por mucho que lo intente,',
  },
  {
    id: 'kwt_029',
    context_sentence: "It doesn't matter how hard I try, I can't solve it.",
    base_word: 'HOWEVER',
    sentence: '___ I can\'t solve it.',
    answer: 'However hard I try,',
    options: null,
    explanation: '"It doesn\'t matter how" → "However" + adjective/adverb + subject + verb.',
    explanation_es: '"It doesn\'t matter how" → "However" + adj/adv + sujeto + verbo.',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'no puede ser posible',
  },
  {
    id: 'kwt_030',
    context_sentence: "Without your help, I wouldn't have passed.",
    base_word: 'HAD',
    sentence: 'If ___ I wouldn\'t have passed.',
    answer: "it hadn't been for your help,",
    options: null,
    explanation: '"Without" → "If it hadn\'t been for" (third conditional).',
    explanation_es: '"Without" → "If it hadn\'t been for" (tercer condicional).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'no logró terminar',
  },
  // ── More Key Word Transformations ──
  {
    id: 'kwt_031',
    context_sentence: "He runs faster than anyone else in the team.",
    base_word: 'FASTEST',
    sentence: 'He is ___ in the team.',
    answer: 'the fastest runner',
    options: null,
    explanation: 'Comparative → superlative: "faster than anyone" → "the fastest".',
    explanation_es: 'Comparativo → superlativo: "faster than anyone" → "the fastest".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'no ha habido quejas',
  },
  {
    id: 'kwt_032',
    context_sentence: "I'm sure he didn't cheat in the exam.",
    base_word: 'HAVE',
    sentence: 'He ___ in the exam.',
    answer: "can't have cheated",
    options: null,
    explanation: '"I\'m sure he didn\'t" → "can\'t have + pp" (past certainty).',
    explanation_es: '"I\'m sure he didn\'t" → "can\'t have + pp" (certeza pasada).',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'no he ido a nadar desde',
  },
  {
    id: 'kwt_033',
    context_sentence: "They started the meeting without waiting for us.",
    base_word: 'WENT',
    sentence: 'They ___ without waiting for us.',
    answer: 'went ahead with the meeting',
    options: null,
    explanation: '"Started" → "went ahead with" (= proceeded).',
    explanation_es: '"Started" → "went ahead with" (= procedieron).',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'si no fuera por tu ayuda,',
  },
  {
    id: 'kwt_034',
    context_sentence: "The children were so excited that they couldn't sleep.",
    base_word: 'TOO',
    sentence: 'The children were ___ sleep.',
    answer: 'too excited to',
    options: null,
    explanation: '"So + adj + that... couldn\'t" → "too + adj + to".',
    explanation_es: '"So + adj + that... couldn\'t" → "too + adj + to".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'no debería haber gritado',
  },
  {
    id: 'kwt_035',
    context_sentence: "No one in the class is as tall as Mark.",
    base_word: 'TALLEST',
    sentence: 'Mark ___ in the class.',
    answer: 'is the tallest student',
    options: null,
    explanation: '"No one is as... as" → superlative.',
    explanation_es: '"No one is as... as" → superlativo.',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'preferiría que no lo mencionases',
  },
  {
    id: 'kwt_036',
    context_sentence: "He didn't arrive on time because he overslept.",
    base_word: 'RESULT',
    sentence: 'He overslept and, ___ he didn\'t arrive on time.',
    answer: 'as a result,',
    options: null,
    explanation: '"Because" (cause) → "as a result" (consequence).',
    explanation_es: '"Because" (causa) → "as a result" (consecuencia).',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'a pesar de ser rico,',
  },
  {
    id: 'kwt_037',
    context_sentence: "People believe he is innocent.",
    base_word: 'BELIEVED',
    sentence: 'He ___ innocent.',
    answer: 'is believed to be',
    options: null,
    explanation: '"People believe + clause" → passive: "is believed to be".',
    explanation_es: '"People believe + oración" → pasiva: "is believed to be".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'le hicieron firmar',
  },
  {
    id: 'kwt_038',
    context_sentence: "She regrets not going to university.",
    base_word: 'WISHES',
    sentence: 'She ___ to university.',
    answer: 'wishes she had gone',
    options: null,
    explanation: '"Regrets not doing" → "wishes + past perfect".',
    explanation_es: '"Regrets not doing" → "wishes + pluscuamperfecto".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'es sospechoso de haber robado',
  },
  {
    id: 'kwt_039',
    context_sentence: "He hasn't eaten anything all day.",
    base_word: 'NOTHING',
    sentence: 'He has ___ all day.',
    answer: 'had nothing to eat',
    options: null,
    explanation: '"Hasn\'t eaten anything" → "has had nothing to eat".',
    explanation_es: '"Hasn\'t eaten anything" → "has had nothing to eat".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'es el más alto',
  },
  {
    id: 'kwt_040',
    context_sentence: "I didn't expect the film to be so boring.",
    base_word: 'SUCH',
    sentence: 'I didn\'t expect it to be ___ film.',
    answer: 'such a boring',
    options: null,
    explanation: '"So + adjective" → "such a + adjective + noun".',
    explanation_es: '"So + adjetivo" → "such a + adjetivo + sustantivo".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'la última vez que llamó',
  },
  {
    id: 'kwt_041',
    context_sentence: "Everyone thinks the thief escaped through the window.",
    base_word: 'THOUGHT',
    sentence: 'The thief ___ through the window.',
    answer: 'is thought to have escaped',
    options: null,
    explanation: '"Everyone thinks + past" → passive reporting: "is thought to have + pp".',
    explanation_es: '"Everyone thinks + pasado" → pasiva impersonal: "is thought to have + pp".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'no tenía nada que comer',
  },
  {
    id: 'kwt_042',
    context_sentence: "She can't possibly be at home — her car isn't here.",
    base_word: 'BE',
    sentence: 'She ___ at home — her car isn\'t here.',
    answer: "can't possibly be",
    options: null,
    explanation: '"Can\'t possibly be" = strong deduction that something is not the case.',
    explanation_es: '"Can\'t possibly be" = deducción fuerte de que algo no es así.',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'mi consejo es que veas',
  },
  {
    id: 'kwt_043',
    context_sentence: "They forced him to sign the contract.",
    base_word: 'MADE',
    sentence: 'He ___ the contract.',
    answer: 'was made to sign',
    options: null,
    explanation: '"Forced him to" (active) → "was made to" (passive). Note: passive "make" takes "to".',
    explanation_es: '"Forced him to" (activa) → "was made to" (pasiva). Nota: "make" pasivo lleva "to".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'es una tontería / no sirve de nada',
  },
  {
    id: 'kwt_044',
    context_sentence: "I've never tasted such delicious food.",
    base_word: 'MOST',
    sentence: 'This is ___ food I have ever tasted.',
    answer: 'the most delicious',
    options: null,
    explanation: '"Never + such" → superlative: "the most + adj + ever".',
    explanation_es: '"Never + such" → superlativo: "the most + adj + ever".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'prefiere nadar a',
  },
  {
    id: 'kwt_045',
    context_sentence: "He left the house and immediately it started raining.",
    base_word: 'SOONER',
    sentence: 'No ___ it started raining.',
    answer: 'sooner had he left the house than',
    options: null,
    explanation: '"No sooner had... than..." = as soon as (formal, with inversion).',
    explanation_es: '"No sooner had... than..." = en cuanto (formal, con inversión).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'saltó a la fama',
  },
  {
    id: 'kwt_046',
    context_sentence: "She likes swimming more than running.",
    base_word: 'PREFERS',
    sentence: 'She ___ running.',
    answer: 'prefers swimming to',
    options: null,
    explanation: '"Like more than" → "prefer + -ing + TO + -ing".',
    explanation_es: '"Like more than" → "prefer + -ing + TO + -ing".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'no permitió que nadie le molestara',
  },
  {
    id: 'kwt_047',
    context_sentence: "He didn't realise he had made a mistake until later.",
    base_word: 'ONLY',
    sentence: 'It was ___ he realised he had made a mistake.',
    answer: 'only later that',
    options: null,
    explanation: 'Cleft sentence: "It was only later that...".',
    explanation_es: 'Oración hendida: "It was only later that...".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'como resultado,',
  },
  {
    id: 'kwt_048',
    context_sentence: "We didn't manage to finish the project on time.",
    base_word: 'SUCCEED',
    sentence: 'We ___ the project on time.',
    answer: "didn't succeed in finishing",
    options: null,
    explanation: '"Didn\'t manage to" → "didn\'t succeed in + -ing".',
    explanation_es: '"Didn\'t manage to" → "didn\'t succeed in + -ing".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'con toda probabilidad, se ha olvidado',
  },
  {
    id: 'kwt_049',
    context_sentence: "It was wrong of you to shout at him.",
    base_word: 'OUGHT',
    sentence: 'You ___ at him.',
    answer: "ought not to have shouted",
    options: null,
    explanation: '"It was wrong of you to" → "ought not to have + pp".',
    explanation_es: '"It was wrong of you to" → "ought not to have + pp".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'solo después',
  },
  {
    id: 'kwt_050',
    context_sentence: "I can't wait to see you again.",
    base_word: 'FORWARD',
    sentence: 'I\'m ___ you again.',
    answer: 'looking forward to seeing',
    options: null,
    explanation: '"Can\'t wait to" → "looking forward to + -ing".',
    explanation_es: '"Can\'t wait to" → "looking forward to + -ing".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'tan aburrida',
  },
  {
    id: 'kwt_051',
    context_sentence: "She didn't let anyone disturb her.",
    base_word: 'ALLOWED',
    sentence: 'She ___ her.',
    answer: 'allowed nobody to disturb',
    options: null,
    explanation: '"Didn\'t let anyone" → "allowed nobody to".',
    explanation_es: '"Didn\'t let anyone" → "allowed nobody to".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'el corredor más rápido',
  },
  {
    id: 'kwt_052',
    context_sentence: "There's no point in complaining about it.",
    base_word: 'USE',
    sentence: 'It\'s ___ about it.',
    answer: 'no use complaining',
    options: null,
    explanation: '"No point in" → "no use + -ing".',
    explanation_es: '"No point in" → "no use + -ing".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'el más delicioso',
  },
  {
    id: 'kwt_053',
    context_sentence: "He only realised his wallet was missing when he got home.",
    base_word: 'DID',
    sentence: 'Not until he got home ___ his wallet was missing.',
    answer: 'did he realise',
    options: null,
    explanation: '"Not until" at the start → inversion: "did he realise".',
    explanation_es: '"Not until" al inicio → inversión: "did he realise".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'desearía haber ido',
  },
  {
    id: 'kwt_054',
    context_sentence: "They suspect he stole the jewellery.",
    base_word: 'SUSPECTED',
    sentence: 'He ___ the jewellery.',
    answer: 'is suspected of having stolen',
    options: null,
    explanation: '"They suspect + past" → "is suspected of having + pp".',
    explanation_es: '"They suspect + pasado" → "is suspected of having + pp".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'tenía ganas de ver',
  },
  {
    id: 'kwt_055',
    context_sentence: "I think you should see a doctor.",
    base_word: 'ADVICE',
    sentence: 'My ___ a doctor.',
    answer: 'advice is to see',
    options: null,
    explanation: '"I think you should" → "My advice is to".',
    explanation_es: '"I think you should" → "My advice is to".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'apenas había salido de casa cuando',
  },
  {
    id: 'kwt_056',
    context_sentence: "She became famous overnight.",
    base_word: 'ROSE',
    sentence: 'She ___ overnight.',
    answer: 'rose to fame',
    options: null,
    explanation: '"Became famous" → "rose to fame" (collocation).',
    explanation_es: '"Became famous" → "rose to fame" (colocación).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'siguió adelante con la reunión',
  },
  {
    id: 'kwt_057',
    context_sentence: "He's probably forgotten about the meeting.",
    base_word: 'LIKELIHOOD',
    sentence: 'In all ___ about the meeting.',
    answer: 'likelihood, he has forgotten',
    options: null,
    explanation: '"Probably" → "In all likelihood" (formal).',
    explanation_es: '"Probably" → "In all likelihood" (formal).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'no puede haber sido',
  },
  {
    id: 'kwt_058',
    context_sentence: "He hasn't phoned me for weeks.",
    base_word: 'LAST',
    sentence: 'The ___ me was weeks ago.',
    answer: 'last time he phoned',
    options: null,
    explanation: '"Hasn\'t done for" → "The last time... was... ago".',
    explanation_es: '"Hasn\'t done for" → "The last time... was... ago".',
    cefr_level: 'B1', category: 'key_word_transformation', difficulty: 1,
    answer_es: 'no puede haber hecho',
  },
  {
    id: 'kwt_059',
    context_sentence: "Although she's rich, she's very mean.",
    base_word: 'DESPITE',
    sentence: '___ she is very mean.',
    answer: 'Despite being rich,',
    options: null,
    explanation: '"Although + clause" → "Despite + -ing".',
    explanation_es: '"Although + cláusula" → "Despite + -ing".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    answer_es: 'es el pensamiento / lo que cuenta es',
  },
  {
    id: 'kwt_060',
    context_sentence: "I'd prefer you not to mention this to anyone.",
    base_word: 'RATHER',
    sentence: 'I\'d ___ this to anyone.',
    answer: "rather you didn't mention",
    options: null,
    explanation: '"I\'d prefer you not to" → "I\'d rather you didn\'t" (past simple for other people).',
    explanation_es: '"I\'d prefer you not to" → "I\'d rather you didn\'t" (pasado simple para otros).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    answer_es: 'es lo más bonito',
  },
];
