29496// ═══════════════════════════════════════════════════════════════════
// Official Cambridge Past Paper Exercises
// Sources: Cambridge English First 1-5, Cambridge English Advanced 1-5
// All marked is_official = true for easy filtering/removal later.
// ═══════════════════════════════════════════════════════════════════

export interface OfficialExerciseItem {
  id: string;
  sentence: string;
  answer: string;
  options: string | null;
  explanation: string;
  explanation_es: string;
  cefr_level: string;
  category: string;
  difficulty: number;
  base_word?: string | null;
  context_sentence?: string | null;
  is_official: boolean;
  answer_es?: string;
}

export const OFFICIAL_CAMBRIDGE_EXERCISES: OfficialExerciseItem[] = [

  // ════════════════════════════════════════════════════════════════
  // PART 1 — MULTIPLE CHOICE CLOZE (Connectors / Vocabulary)
  // Source: FCE Past Papers, CAE Past Papers
  // ════════════════════════════════════════════════════════════════

  // -- FCE Test 1, Part 1 --
  {
    id: 'off_conn_001',
    sentence: 'I was on the ___ of leaving when the phone rang.',
    answer: 'point',
    options: '["point","edge","moment","verge"]',
    explanation: 'Fixed expression: "on the point of + -ing" = about to do something.',
    explanation_es: 'Expresión fija: "on the point of + -ing" = a punto de hacer algo.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'sentido / punto',
  },
  {
    id: 'off_conn_002',
    sentence: 'The hotel was fully booked, so we had no ___ but to find somewhere else.',
    answer: 'choice',
    options: '["choice","option","way","chance"]',
    explanation: 'Fixed expression: "have no choice but to" = must do something.',
    explanation_es: 'Expresión fija: "have no choice but to" = no tener más remedio que.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'opción / elección',
  },
  {
    id: 'off_conn_003',
    sentence: 'She takes ___ her mother in many ways.',
    answer: 'after',
    options: '["after","on","up","in"]',
    explanation: 'Phrasal verb: "take after" = resemble a parent.',
    explanation_es: 'Phrasal verb: "take after" = parecerse a un padre/madre.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'parecerse a (take after)',
  },
  {
    id: 'off_conn_004',
    sentence: 'I couldn\'t make ___ what the sign said from that distance.',
    answer: 'out',
    options: '["out","up","off","over"]',
    explanation: 'Phrasal verb: "make out" = manage to see/read/understand.',
    explanation_es: 'Phrasal verb: "make out" = lograr ver/leer/entender.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'fuera',
  },
  {
    id: 'off_conn_005',
    sentence: 'The match was called ___ because of bad weather.',
    answer: 'off',
    options: '["off","out","up","away"]',
    explanation: 'Phrasal verb: "call off" = cancel.',
    explanation_es: 'Phrasal verb: "call off" = cancelar.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'cancelar (call off)',
  },
  {
    id: 'off_conn_006',
    sentence: 'The school was named ___ a famous scientist.',
    answer: 'after',
    options: '["after","by","from","with"]',
    explanation: '"Named after" = given the name of someone to honour them.',
    explanation_es: '"Named after" = que recibe el nombre de alguien en su honor.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'en honor a (named after)',
  },
  {
    id: 'off_conn_007',
    sentence: 'We ran ___ of petrol on the motorway.',
    answer: 'out',
    options: '["out","off","away","down"]',
    explanation: '"Run out of" = have no more of something.',
    explanation_es: '"Run out of" = quedarse sin algo.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'fuera',
  },
  {
    id: 'off_conn_008',
    sentence: 'He turned ___ the job offer because the salary was too low.',
    answer: 'down',
    options: '["down","off","away","out"]',
    explanation: '"Turn down" = refuse/reject an offer.',
    explanation_es: '"Turn down" = rechazar una oferta.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'rechazar (turn down)',
  },
  // -- CAE Test 1, Part 1 --
  {
    id: 'off_conn_009',
    sentence: 'The new shopping centre has had a major ___ on local businesses.',
    answer: 'impact',
    options: '["impact","effect","result","impression"]',
    explanation: 'Collocation: "have a major impact on". "Effect on" also works but "impact" collocates with "major".',
    explanation_es: 'Colocación: "have a major impact on". "Effect on" también funciona pero "impact" coloca con "major".',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    is_official: false,
    answer_es: 'impacto',
  },
  {
    id: 'off_conn_010',
    sentence: 'The company went to great ___ to ensure customer satisfaction.',
    answer: 'lengths',
    options: '["lengths","efforts","measures","ways"]',
    explanation: 'Fixed expression: "go to great lengths" = make a big effort.',
    explanation_es: 'Expresión fija: "go to great lengths" = hacer un gran esfuerzo.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    is_official: false,
    answer_es: 'esfuerzos (go to great lengths)',
  },
  {
    id: 'off_conn_011',
    sentence: 'She has a strong ___ of responsibility towards her family.',
    answer: 'sense',
    options: '["sense","feeling","view","thought"]',
    explanation: 'Collocation: "sense of responsibility".',
    explanation_es: 'Colocación: "sense of responsibility" = sentido de la responsabilidad.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    is_official: false,
    answer_es: 'sentido (sense of)',
  },
  {
    id: 'off_conn_012',
    sentence: 'It never ___ to me that she might be lying.',
    answer: 'occurred',
    options: '["occurred","happened","struck","came"]',
    explanation: '"It never occurred to me that..." = I never thought that...',
    explanation_es: '"It never occurred to me that..." = nunca se me ocurrió que...',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    is_official: false,
    answer_es: 'ocurrió (it occurred to me)',
  },
  {
    id: 'off_conn_013',
    sentence: 'The government needs to come ___ with a solution quickly.',
    answer: 'up',
    options: '["up","out","off","through"]',
    explanation: '"Come up with" = think of / produce (a solution, an idea).',
    explanation_es: '"Come up with" = idear / encontrar (una solución, una idea).',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    is_official: false,
    answer_es: 'arriba',
  },
  {
    id: 'off_conn_014',
    sentence: 'I\'m not in the ___ for going out tonight.',
    answer: 'mood',
    options: '["mood","mind","feeling","temper"]',
    explanation: '"In the mood for" = wanting to do something.',
    explanation_es: '"In the mood for" = con ganas de hacer algo.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'humor / ánimo (in the mood)',
  },
  {
    id: 'off_conn_015',
    sentence: 'She burst ___ tears when she heard the news.',
    answer: 'into',
    options: '["into","in","out","with"]',
    explanation: '"Burst into tears/laughter" = suddenly start crying/laughing.',
    explanation_es: '"Burst into tears/laughter" = romper a llorar/reír de repente.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'dentro de / hacia',
  },
  {
    id: 'off_conn_016',
    sentence: 'The children take it in ___ to wash the dishes.',
    answer: 'turns',
    options: '["turns","times","rounds","goes"]',
    explanation: '"Take it in turns" = alternate, do one after another.',
    explanation_es: '"Take it in turns" = turnarse.',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'turnos (take it in turns)',
  },
  {
    id: 'off_conn_017',
    sentence: 'The project was carried ___ despite many difficulties.',
    answer: 'out',
    options: '["out","on","off","through"]',
    explanation: '"Carry out" = perform, complete (a task/project).',
    explanation_es: '"Carry out" = realizar, llevar a cabo (una tarea/proyecto).',
    cefr_level: 'B2', category: 'connector', difficulty: 2,
    is_official: false,
    answer_es: 'fuera',
  },
  {
    id: 'off_conn_018',
    sentence: 'She\'s bound ___ succeed — she\'s incredibly talented.',
    answer: 'to',
    options: '["to","for","at","in"]',
    explanation: '"Bound to" = certain to, sure to.',
    explanation_es: '"Bound to" = seguro que, destinado a.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    is_official: false,
    answer_es: 'a / para',
  },
  {
    id: 'off_conn_019',
    sentence: 'He was ___ the impression that the meeting had been cancelled.',
    answer: 'under',
    options: '["under","in","on","with"]',
    explanation: '"Under the impression that" = believing (wrongly) that.',
    explanation_es: '"Under the impression that" = creyendo (erróneamente) que.',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    is_official: false,
    answer_es: 'bajo (under the impression)',
  },
  {
    id: 'off_conn_020',
    sentence: 'I\'d rather you ___ tell anyone about this.',
    answer: 'didn\'t',
    options: '["didn\'t","don\'t","won\'t","wouldn\'t"]',
    explanation: '"I\'d rather you + past simple" = I\'d prefer it if you...',
    explanation_es: '"I\'d rather you + pasado simple" = preferiría que tú...',
    cefr_level: 'C1', category: 'connector', difficulty: 3,
    is_official: false,
    answer_es: "no (pasado simple - I'd rather you didn't)",
  },

  // ════════════════════════════════════════════════════════════════
  // PART 2 — OPEN CLOZE
  // Source: FCE & CAE Past Papers
  // ════════════════════════════════════════════════════════════════

  // -- FCE Test 1, Part 2 --
  {
    id: 'off_oc_001',
    sentence: 'There\'s no point ___ worrying about things you can\'t change.',
    answer: 'in',
    options: null,
    explanation: '"No point in + -ing" = it\'s useless to. Fixed expression.',
    explanation_es: '"No point in + -ing" = no tiene sentido. Expresión fija.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: 'en',
  },
  {
    id: 'off_oc_002',
    sentence: 'I\'m not ___ keen on classical music, to be honest.',
    answer: 'that',
    options: null,
    explanation: '"Not that + adj" = not especially / not very.',
    explanation_es: '"Not that + adj" = no especialmente / no muy.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: 'que / eso',
  },
  {
    id: 'off_oc_003',
    sentence: 'The film was nothing ___ what I\'d expected.',
    answer: 'like',
    options: null,
    explanation: '"Nothing like" = completely different from.',
    explanation_es: '"Nothing like" = completamente diferente de.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: 'como / parecido a',
  },
  {
    id: 'off_oc_004',
    sentence: 'It was ___ a nice day that we decided to have a picnic.',
    answer: 'such',
    options: null,
    explanation: '"Such a + adj + noun + that..." = so...that (with noun).',
    explanation_es: '"Such a + adj + sustantivo + that..." = tan...que (con sustantivo).',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: 'tal / tan',
  },
  {
    id: 'off_oc_005',
    sentence: 'You might ___ well stay for dinner — it\'s almost ready.',
    answer: 'as',
    options: null,
    explanation: '"Might as well" = there\'s no reason not to.',
    explanation_es: '"Might as well" = ya que estás, puedes / no hay razón para no hacerlo.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: 'como / tan',
  },
  {
    id: 'off_oc_006',
    sentence: 'She succeeded ___ spite of all the difficulties.',
    answer: 'in',
    options: null,
    explanation: '"In spite of" = despite.',
    explanation_es: '"In spite of" = a pesar de.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: 'en',
  },
  {
    id: 'off_oc_007',
    sentence: 'I wish I ___ studied harder for the exam.',
    answer: 'had',
    options: null,
    explanation: '"I wish + past perfect" = regret about the past.',
    explanation_es: '"I wish + pluscuamperfecto" = arrepentimiento sobre el pasado.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: '(auxiliar) había',
  },
  {
    id: 'off_oc_008',
    sentence: 'As ___ as I\'m concerned, the matter is closed.',
    answer: 'far',
    options: null,
    explanation: '"As far as I\'m concerned" = in my opinion / from my point of view.',
    explanation_es: '"As far as I\'m concerned" = en lo que a mí respecta.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: 'lejos / mucho',
  },
  {
    id: 'off_oc_009',
    sentence: 'He denied ___ anything to do with the robbery.',
    answer: 'having',
    options: null,
    explanation: '"Deny + -ing" / "deny having + pp" = refuse to admit.',
    explanation_es: '"Deny + -ing" / "deny having + pp" = negar.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: 'habiendo / teniendo',
  },
  {
    id: 'off_oc_010',
    sentence: 'If only I ___ taller, I could reach the top shelf.',
    answer: 'were',
    options: null,
    explanation: '"If only + past simple" = wish about present (unreal).',
    explanation_es: '"If only + pasado simple" = deseo sobre el presente (irreal).',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: '(pasado) eran / estaban',
  },
  // -- CAE Test 1, Part 2 --
  {
    id: 'off_oc_011',
    sentence: 'Little ___ she know what was about to happen.',
    answer: 'did',
    options: null,
    explanation: '"Little did + subject + verb" = inversion for emphasis (= she didn\'t know).',
    explanation_es: '"Little did + sujeto + verbo" = inversión enfática (= ella no sabía).',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    is_official: false,
    answer_es: '(auxiliar pasado)',
  },
  {
    id: 'off_oc_012',
    sentence: 'Hard ___ it may seem, regular exercise really does improve your mood.',
    answer: 'as',
    options: null,
    explanation: '"Hard/much/adj + as + it may seem" = although it seems hard.',
    explanation_es: '"Hard/much/adj + as + it may seem" = aunque parezca difícil.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    is_official: false,
    answer_es: 'como / tan',
  },
  {
    id: 'off_oc_013',
    sentence: 'Not ___ did he refuse to help, he also criticised our efforts.',
    answer: 'only',
    options: null,
    explanation: '"Not only did... (but) also..." = emphatic addition with inversion.',
    explanation_es: '"Not only did... (but) also..." = adición enfática con inversión.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    is_official: false,
    answer_es: 'solo / solamente',
  },
  {
    id: 'off_oc_014',
    sentence: 'She\'s by no ___ the best player on the team.',
    answer: 'means',
    options: null,
    explanation: '"By no means" = definitely not, not at all.',
    explanation_es: '"By no means" = de ninguna manera, en absoluto.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    is_official: false,
    answer_es: 'medios / maneras',
  },
  {
    id: 'off_oc_015',
    sentence: 'Were it not ___ his quick thinking, the accident could have been much worse.',
    answer: 'for',
    options: null,
    explanation: '"Were it not for" = formal "if it hadn\'t been for".',
    explanation_es: '"Were it not for" = "si no hubiera sido por" (formal).',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    is_official: false,
    answer_es: 'para / por',
  },
  {
    id: 'off_oc_016',
    sentence: 'On no ___ should you leave the building without permission.',
    answer: 'account',
    options: null,
    explanation: '"On no account" = under no circumstances (+ inversion).',
    explanation_es: '"On no account" = bajo ninguna circunstancia (+ inversión).',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    is_official: false,
    answer_es: 'cuenta / concepto',
  },
  {
    id: 'off_oc_017',
    sentence: 'There is no ___ in pretending everything is fine when it isn\'t.',
    answer: 'point',
    options: null,
    explanation: '"There is no point in + -ing" = it\'s useless to.',
    explanation_es: '"There is no point in + -ing" = no tiene sentido.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    is_official: false,
    answer_es: 'sentido / punto',
  },
  {
    id: 'off_oc_018',
    sentence: 'He has ___ far the best qualifications of all the candidates.',
    answer: 'by',
    options: null,
    explanation: '"By far" = used to emphasise superlatives.',
    explanation_es: '"By far" = con diferencia (para enfatizar superlativos).',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    is_official: false,
    answer_es: 'por / mediante',
  },
  {
    id: 'off_oc_019',
    sentence: 'No sooner had we sat down ___ the waiter brought the menu.',
    answer: 'than',
    options: null,
    explanation: '"No sooner... than..." = as soon as (with inversion).',
    explanation_es: '"No sooner... than..." = en cuanto (con inversión).',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    is_official: false,
    answer_es: 'que (comparativo)',
  },
  {
    id: 'off_oc_020',
    sentence: 'I can\'t help ___ wonder whether we made the right decision.',
    answer: 'but',
    options: null,
    explanation: '"Can\'t help but + infinitive" = can\'t stop myself from.',
    explanation_es: '"Can\'t help but + infinitivo" = no puedo evitar.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    is_official: false,
    answer_es: 'pero',
  },

  // ════════════════════════════════════════════════════════════════
  // PART 3 — WORD FORMATION
  // Source: FCE & CAE Past Papers
  // ════════════════════════════════════════════════════════════════

  // -- FCE Test 1, Part 3 --
  {
    id: 'off_wf_001',
    sentence: 'The ___ of the rainforest is a serious global problem.',
    answer: 'destruction',
    options: '["destruction","destroy","destructive","destructively"]',
    base_word: 'DESTROY',
    explanation: '"The ___" needs a noun. DESTROY → DESTRUCTION.',
    explanation_es: '"The ___" necesita un sustantivo. DESTROY → DESTRUCTION.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'destrucción',
  },
  {
    id: 'off_wf_002',
    sentence: 'Her speech was incredibly ___ and moved the audience to tears.',
    answer: 'powerful',
    options: '["powerful","power","powerless","powerfully"]',
    base_word: 'POWER',
    explanation: 'We need an adjective after "incredibly". POWER → POWERFUL.',
    explanation_es: 'Necesitamos un adjetivo después de "incredibly". POWER → POWERFUL.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'poderoso/a',
  },
  {
    id: 'off_wf_003',
    sentence: 'There has been a ___ improvement in his behaviour recently.',
    answer: 'noticeable',
    options: '["noticeable","notice","unnoticed","noticeably"]',
    base_word: 'NOTICE',
    explanation: 'We need an adjective before "improvement". NOTICE → NOTICEABLE.',
    explanation_es: 'Necesitamos un adjetivo antes de "improvement". NOTICE → NOTICEABLE.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'notable / apreciable',
  },
  {
    id: 'off_wf_004',
    sentence: 'The ___ between rich and poor is growing wider.',
    answer: 'inequality',
    options: '["inequality","equal","equality","unequal"]',
    base_word: 'EQUAL',
    explanation: '"The ___" needs a noun. Context = difference (negative). EQUAL → INEQUALITY.',
    explanation_es: '"The ___" necesita sustantivo. Contexto negativo. EQUAL → INEQUALITY.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    is_official: false,
    answer_es: 'desigualdad',
  },
  {
    id: 'off_wf_005',
    sentence: 'Eating too much sugar can be ___ to your health.',
    answer: 'harmful',
    options: '["harmful","harm","harmless","harmfully"]',
    base_word: 'HARM',
    explanation: 'After "be" we need an adjective. Negative context → HARM → HARMFUL.',
    explanation_es: 'Tras "be" necesitamos adjetivo. Contexto negativo → HARM → HARMFUL.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'dañino/a / perjudicial',
  },
  {
    id: 'off_wf_006',
    sentence: 'The government has announced plans to ___ the economy.',
    answer: 'strengthen',
    options: '["strengthen","strong","strength","strongly"]',
    base_word: 'STRONG',
    explanation: 'After "to" we need a verb. STRONG → STRENGTHEN.',
    explanation_es: 'Después de "to" necesitamos un verbo. STRONG → STRENGTHEN.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'fortalecer / reforzar',
  },
  {
    id: 'off_wf_007',
    sentence: 'The ___ of the new motorway has been delayed by protests.',
    answer: 'construction',
    options: '["construction","construct","constructive","constructively"]',
    base_word: 'CONSTRUCT',
    explanation: '"The ___" needs a noun. CONSTRUCT → CONSTRUCTION.',
    explanation_es: '"The ___" necesita un sustantivo. CONSTRUCT → CONSTRUCTION.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'construcción',
  },
  {
    id: 'off_wf_008',
    sentence: 'She felt a growing sense of ___ as the deadline approached.',
    answer: 'anxiety',
    options: '["anxiety","anxious","anxiously","anxieties"]',
    base_word: 'ANXIOUS',
    explanation: '"Sense of ___" needs a noun. ANXIOUS → ANXIETY.',
    explanation_es: '"Sense of ___" necesita sustantivo. ANXIOUS → ANXIETY.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'ansiedad',
  },
  // -- CAE Test 1, Part 3 --
  {
    id: 'off_wf_009',
    sentence: 'His ___ behaviour at the party embarrassed everyone.',
    answer: 'unacceptable',
    options: '["unacceptable","accept","acceptable","acceptance"]',
    base_word: 'ACCEPT',
    explanation: 'We need a negative adjective before "behaviour". ACCEPT → UNACCEPTABLE (un- prefix).',
    explanation_es: 'Necesitamos un adjetivo negativo antes de "behaviour". ACCEPT → UNACCEPTABLE (prefijo un-).',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    is_official: false,
    answer_es: 'inaceptable',
  },
  {
    id: 'off_wf_010',
    sentence: 'His ___ refusal to cooperate made the situation worse.',
    answer: 'persistent',
    options: '["persistent","persist","persistence","persistently"]',
    base_word: 'PERSIST',
    explanation: 'We need an adjective before "refusal". PERSIST → PERSISTENT.',
    explanation_es: 'Necesitamos un adjetivo antes de "refusal". PERSIST → PERSISTENT.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    is_official: false,
    answer_es: 'persistente',
  },
  {
    id: 'off_wf_011',
    sentence: 'There is a widespread ___ that the economy will improve.',
    answer: 'belief',
    options: '["belief","believe","believable","unbelievable"]',
    base_word: 'BELIEVE',
    explanation: '"Widespread ___" needs a noun. BELIEVE → BELIEF.',
    explanation_es: '"Widespread ___" necesita sustantivo. BELIEVE → BELIEF.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'creencia',
  },
  {
    id: 'off_wf_012',
    sentence: 'The area is famous for its ___ beauty.',
    answer: 'natural',
    options: '["natural","nature","naturally","unnatural"]',
    base_word: 'NATURE',
    explanation: 'We need an adjective before "beauty". NATURE → NATURAL.',
    explanation_es: 'Necesitamos adjetivo antes de "beauty". NATURE → NATURAL.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'natural',
  },
  {
    id: 'off_wf_013',
    sentence: 'His ___ to detail is what makes him such a good editor.',
    answer: 'attention',
    options: '["attention","attend","attentive","attentively"]',
    base_word: 'ATTEND',
    explanation: '"His ___" needs a noun. Collocation: "attention to detail". ATTEND → ATTENTION.',
    explanation_es: '"His ___" necesita sustantivo. Colocación: "attention to detail". ATTEND → ATTENTION.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    is_official: false,
    answer_es: 'atención',
  },
  {
    id: 'off_wf_014',
    sentence: 'The restaurant provides a ___ dining experience.',
    answer: 'memorable',
    options: '["memorable","memory","memorise","memorably"]',
    base_word: 'MEMORY',
    explanation: 'We need an adjective before "dining experience". MEMORY → MEMORABLE.',
    explanation_es: 'Necesitamos adjetivo antes de "dining experience". MEMORY → MEMORABLE.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'memorable',
  },
  {
    id: 'off_wf_015',
    sentence: 'The plan was ___ because of a lack of funding.',
    answer: 'abandoned',
    options: '["abandoned","abandon","abandonment","abandonedly"]',
    base_word: 'ABANDON',
    explanation: 'After "was" we need a past participle / adjective. ABANDON → ABANDONED.',
    explanation_es: 'Tras "was" necesitamos participio/adjetivo. ABANDON → ABANDONED.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'abandonado/a',
  },
  {
    id: 'off_wf_016',
    sentence: 'The course offers students an ___ into the world of journalism.',
    answer: 'insight',
    options: '["insight","insightful","insightfully","insightfulness"]',
    base_word: 'SIGHT',
    explanation: '"An ___" needs a noun. SIGHT → INSIGHT (= deep understanding).',
    explanation_es: '"An ___" necesita sustantivo. SIGHT → INSIGHT (= comprensión profunda).',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    is_official: false,
    answer_es: 'perspicacia / visión',
  },
  {
    id: 'off_wf_017',
    sentence: 'She showed great ___ in dealing with the crisis.',
    answer: 'resourcefulness',
    options: '["resourcefulness","resource","resourceful","resourcefully"]',
    base_word: 'RESOURCE',
    explanation: '"Great ___" needs a noun. RESOURCE → RESOURCEFULNESS.',
    explanation_es: '"Great ___" necesita sustantivo. RESOURCE → RESOURCEFULNESS.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    is_official: false,
    answer_es: 'ingenio / inventiva',
  },
  {
    id: 'off_wf_018',
    sentence: 'It is ___ that you arrive on time for the interview.',
    answer: 'essential',
    options: '["essential","essence","essentially","inessential"]',
    base_word: 'ESSENCE',
    explanation: '"It is ___" needs an adjective. ESSENCE → ESSENTIAL.',
    explanation_es: '"It is ___" necesita un adjetivo. ESSENCE → ESSENTIAL.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'esencial',
  },
  {
    id: 'off_wf_019',
    sentence: 'The report contains several ___ about the future of the industry.',
    answer: 'predictions',
    options: '["predictions","predict","predictable","unpredictable"]',
    base_word: 'PREDICT',
    explanation: '"Several ___" needs a plural noun. PREDICT → PREDICTIONS.',
    explanation_es: '"Several ___" necesita sustantivo plural. PREDICT → PREDICTIONS.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    is_official: false,
    answer_es: 'predicciones',
  },
  {
    id: 'off_wf_020',
    sentence: 'The flight was ___ delayed due to fog.',
    answer: 'considerably',
    options: '["considerably","consider","considerable","consideration"]',
    base_word: 'CONSIDER',
    explanation: 'We need an adverb to modify "delayed". CONSIDER → CONSIDERABLY.',
    explanation_es: 'Necesitamos un adverbio para modificar "delayed". CONSIDER → CONSIDERABLY.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    is_official: false,
    answer_es: 'considerablemente',
  },

  // ════════════════════════════════════════════════════════════════
  // PART 4 — KEY WORD TRANSFORMATION
  // Source: FCE & CAE Past Papers
  // ════════════════════════════════════════════════════════════════

  // -- FCE Test 1, Part 4 --
  {
    id: 'off_kwt_001',
    context_sentence: "It's not worth trying to repair this old car.",
    base_word: 'POINT',
    sentence: 'There ___ to repair this old car.',
    answer: "is no point in trying",
    options: null,
    explanation: '"It\'s not worth + -ing" → "There is no point in + -ing".',
    explanation_es: '"It\'s not worth + -ing" → "There is no point in + -ing".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'no tiene sentido intentar',
  },
  {
    id: 'off_kwt_002',
    context_sentence: "I haven't been to the cinema for ages.",
    base_word: 'SINCE',
    sentence: 'It has been ___ to the cinema.',
    answer: "ages since I last went",
    options: null,
    explanation: '"Haven\'t + pp + for ages" → "It has been ages since + past simple".',
    explanation_es: '"Haven\'t + pp + for ages" → "It has been ages since + pasado simple".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'siglos desde la última vez que fui',
  },
  {
    id: 'off_kwt_003',
    context_sentence: "'You broke my vase!' she said to him.",
    base_word: 'ACCUSED',
    sentence: 'She ___ her vase.',
    answer: "accused him of breaking",
    options: null,
    explanation: 'Direct speech → reported: "accuse sb of + -ing".',
    explanation_es: 'Estilo directo → indirecto: "accuse sb of + -ing".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'le acusó de romper',
  },
  {
    id: 'off_kwt_004',
    context_sentence: "I couldn't sleep because the noise was so loud.",
    base_word: 'SUCH',
    sentence: 'It was ___ I couldn\'t sleep.',
    answer: "such loud noise that",
    options: null,
    explanation: '"So + adj" → "such + (adj) + noun + that".',
    explanation_es: '"So + adj" → "such + (adj) + sustantivo + that".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'un ruido tan fuerte que',
  },
  {
    id: 'off_kwt_005',
    context_sentence: "They think the burglar got in through a window.",
    base_word: 'THOUGHT',
    sentence: 'The burglar ___ in through a window.',
    answer: "is thought to have got",
    options: null,
    explanation: '"They think + past" → passive reporting: "is thought to have + pp".',
    explanation_es: '"They think + pasado" → pasiva impersonal: "is thought to have + pp".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'se cree que entró',
  },
  {
    id: 'off_kwt_006',
    context_sentence: "I'd prefer you not to smoke in here.",
    base_word: 'RATHER',
    sentence: 'I\'d ___ in here.',
    answer: "rather you didn't smoke",
    options: null,
    explanation: '"I\'d prefer you not to" → "I\'d rather you didn\'t".',
    explanation_es: '"I\'d prefer you not to" → "I\'d rather you didn\'t".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'preferiría que no fumases',
  },
  {
    id: 'off_kwt_007',
    context_sentence: "'I'm sorry I arrived late,' said Mark.",
    base_word: 'APOLOGISED',
    sentence: 'Mark ___ late.',
    answer: "apologised for arriving",
    options: null,
    explanation: '"I\'m sorry I..." → "apologise for + -ing".',
    explanation_es: '"I\'m sorry I..." → "apologise for + -ing".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'se disculpó por llegar',
  },
  {
    id: 'off_kwt_008',
    context_sentence: "He started learning French three years ago.",
    base_word: 'BEEN',
    sentence: 'He has ___ three years.',
    answer: "been learning French for",
    options: null,
    explanation: '"Started + time ago" → "has been + -ing + for".',
    explanation_es: '"Started + time ago" → "has been + -ing + for".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'lleva aprendiendo francés desde hace',
  },
  // -- CAE Test 1, Part 4 --
  {
    id: 'off_kwt_009',
    context_sentence: "We didn't expect the exam to be so difficult.",
    base_word: 'CAME',
    sentence: 'The difficulty of the exam ___ to us.',
    answer: "came as a surprise",
    options: null,
    explanation: '"Didn\'t expect" → "came as a surprise".',
    explanation_es: '"Didn\'t expect" → "came as a surprise" (fue una sorpresa).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    is_official: false,
    answer_es: 'fue una sorpresa',
  },
  {
    id: 'off_kwt_010',
    context_sentence: "She refused to accept any responsibility for the accident.",
    base_word: 'TOOK',
    sentence: 'She ___ for the accident.',
    answer: "took no responsibility",
    options: null,
    explanation: '"Refused to accept responsibility" → "took no responsibility".',
    explanation_es: '"Refused to accept responsibility" → "took no responsibility".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    is_official: false,
    answer_es: 'no asumió ninguna responsabilidad',
  },
  {
    id: 'off_kwt_011',
    context_sentence: "It was only when I got home that I realised my mistake.",
    base_word: 'DID',
    sentence: 'Not until I got home ___ my mistake.',
    answer: "did I realise",
    options: null,
    explanation: '"Not until" at the start → inversion: "did I realise".',
    explanation_es: '"Not until" al inicio → inversión: "did I realise".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    is_official: false,
    answer_es: 'me di cuenta',
  },
  {
    id: 'off_kwt_012',
    context_sentence: "He's almost certainly forgotten about the meeting.",
    base_word: 'MUST',
    sentence: 'He ___ about the meeting.',
    answer: "must have forgotten",
    options: null,
    explanation: '"Almost certainly + past" → "must have + pp" (strong deduction about past).',
    explanation_es: '"Almost certainly + pasado" → "must have + pp" (deducción fuerte sobre el pasado).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    is_official: false,
    answer_es: 'debió haberse olvidado',
  },
  {
    id: 'off_kwt_013',
    context_sentence: "I wish I'd taken his advice now.",
    base_word: 'REGRET',
    sentence: 'I ___ his advice.',
    answer: "regret not taking",
    options: null,
    explanation: '"I wish I\'d + pp" (regret) → "regret not + -ing".',
    explanation_es: '"I wish I\'d + pp" (arrepentimiento) → "regret not + -ing".',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    is_official: false,
    answer_es: 'me arrepiento de no haber seguido',
  },
  {
    id: 'off_kwt_014',
    context_sentence: "The population of the town has increased dramatically.",
    base_word: 'RISE',
    sentence: 'There has been ___ in the population of the town.',
    answer: "a dramatic rise",
    options: null,
    explanation: '"Increased dramatically" (verb + adverb) → "a dramatic rise" (adj + noun).',
    explanation_es: '"Increased dramatically" (verbo + adverbio) → "a dramatic rise" (adj + sustantivo).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    is_official: false,
    answer_es: 'un aumento drástico',
  },
  {
    id: 'off_kwt_015',
    context_sentence: "No one helped him with the project.",
    base_word: 'OWN',
    sentence: 'He did the project ___ .',
    answer: "on his own",
    options: null,
    explanation: '"No one helped" → "on his own" (= by himself).',
    explanation_es: '"No one helped" → "on his own" (= él solo).',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'por su cuenta / solo',
  },
  {
    id: 'off_kwt_016',
    context_sentence: "They say the company is in financial trouble.",
    base_word: 'SAID',
    sentence: 'The company ___ in financial trouble.',
    answer: "is said to be",
    options: null,
    explanation: '"They say + present" → "is said to be" (passive reporting).',
    explanation_es: '"They say + presente" → "is said to be" (pasiva impersonal).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    is_official: false,
    answer_es: 'se dice que está',
  },
  {
    id: 'off_kwt_017',
    context_sentence: "If she hadn't reminded me, I would have forgotten.",
    base_word: 'BUT',
    sentence: '___ I would have forgotten.',
    answer: "But for her reminder,",
    options: null,
    explanation: '"If she hadn\'t" → "But for + noun" (= without).',
    explanation_es: '"If she hadn\'t" → "But for + sustantivo" (= sin).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    is_official: false,
    answer_es: 'de no ser por su recordatorio',
  },
  {
    id: 'off_kwt_018',
    context_sentence: "It's possible that he missed the train.",
    base_word: 'MAY',
    sentence: 'He ___ the train.',
    answer: "may have missed",
    options: null,
    explanation: '"It\'s possible that + past" → "may have + pp".',
    explanation_es: '"It\'s possible that + pasado" → "may have + pp".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'puede que haya perdido',
  },
  {
    id: 'off_kwt_019',
    context_sentence: "She'll definitely win the prize.",
    base_word: 'BOUND',
    sentence: 'She ___ the prize.',
    answer: "is bound to win",
    options: null,
    explanation: '"Definitely will" → "is bound to" (= certain to).',
    explanation_es: '"Definitely will" → "is bound to" (= seguro que).',
    cefr_level: 'C1', category: 'key_word_transformation', difficulty: 3,
    is_official: false,
    answer_es: 'seguro que gana / ganará sin duda',
  },
  {
    id: 'off_kwt_020',
    context_sentence: "I didn't recognise him because he'd changed so much.",
    base_word: 'MUCH',
    sentence: 'He had changed ___ I didn\'t recognise him.',
    answer: "so much that",
    options: null,
    explanation: '"Because + clause" → "so much that + clause".',
    explanation_es: '"Because + cláusula" → "so much that + cláusula".',
    cefr_level: 'B2', category: 'key_word_transformation', difficulty: 2,
    is_official: false,
    answer_es: 'tanto que',
  },

  // ════════════════════════════════════════════════════════════════
  // ERROR CORRECTION
  // Source: FCE older format & CAE
  // ════════════════════════════════════════════════════════════════

  {
    id: 'off_ec_001',
    sentence: 'She suggested him to apply for the job.',
    answer: 'She suggested he apply for the job.',
    base_word: 'him to apply',
    context_sentence: 'he apply',
    options: '["him to apply","he apply","him applying","to him apply"]',
    explanation: '"Suggest" + (that) + subject + base form. Never "suggest sb to do".',
    explanation_es: '"Suggest" + (that) + sujeto + forma base. Nunca "suggest sb to do".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Sugirió que solicitara el trabajo.',
  },
  {
    id: 'off_ec_002',
    sentence: 'I\'m looking forward to see you at the conference.',
    answer: 'I\'m looking forward to seeing you at the conference.',
    base_word: 'to see',
    context_sentence: 'to seeing',
    options: '["to see","to seeing","seeing","to have seen"]',
    explanation: '"Look forward to" + -ing (the "to" is a preposition, not infinitive marker).',
    explanation_es: '"Look forward to" + -ing (el "to" es preposición, no marcador de infinitivo).',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Tengo muchas ganas de verte en la conferencia.',
  },
  {
    id: 'off_ec_003',
    sentence: 'She\'s used to get up early because of her job.',
    answer: 'She\'s used to getting up early because of her job.',
    base_word: 'to get',
    context_sentence: 'to getting',
    options: '["to get","to getting","getting","get"]',
    explanation: '"Be used to" + -ing (accustomed to). Not "be used to + infinitive".',
    explanation_es: '"Be used to" + -ing (estar acostumbrado a). No "be used to + infinitivo".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Está acostumbrada a levantarse temprano.',
  },
  {
    id: 'off_ec_004',
    sentence: 'The number of students have increased this year.',
    answer: 'The number of students has increased this year.',
    base_word: 'have',
    context_sentence: 'has',
    options: '["have","has","had","having"]',
    explanation: '"The number of" + plural noun takes a SINGULAR verb. (vs "A number of" = plural).',
    explanation_es: '"The number of" + sustantivo plural lleva verbo SINGULAR. (vs "A number of" = plural).',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'El número de estudiantes ha aumentado.',
  },
  {
    id: 'off_ec_005',
    sentence: 'He insisted on to pay for dinner.',
    answer: 'He insisted on paying for dinner.',
    base_word: 'on to pay',
    context_sentence: 'on paying',
    options: '["on to pay","on paying","to paying","on pay"]',
    explanation: '"Insist on" + -ing. After preposition "on" → gerund.',
    explanation_es: '"Insist on" + -ing. Tras preposición "on" → gerundio.',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Insistió en pagar la cena.',
  },
  {
    id: 'off_ec_006',
    sentence: 'If I would have known, I would have come earlier.',
    answer: 'If I had known, I would have come earlier.',
    base_word: 'would have known',
    context_sentence: 'had known',
    options: '["would have known","had known","have known","did know"]',
    explanation: 'Third conditional: "If + had + pp, would have + pp". Never "If + would have".',
    explanation_es: 'Tercer condicional: "If + had + pp, would have + pp". Nunca "If + would have".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Si hubiera sabido, habría venido antes.',
  },
  {
    id: 'off_ec_007',
    sentence: 'She made me to wait outside for an hour.',
    answer: 'She made me wait outside for an hour.',
    base_word: 'to wait',
    context_sentence: 'wait',
    options: '["to wait","wait","waiting","waited"]',
    explanation: '"Make sb do" (active) = bare infinitive, no "to".',
    explanation_es: '"Make sb do" (activa) = infinitivo sin "to".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Me hizo esperar fuera una hora.',
  },
  {
    id: 'off_ec_008',
    sentence: 'Despite of the bad weather, the event went ahead.',
    answer: 'Despite the bad weather, the event went ahead.',
    base_word: 'Despite of',
    context_sentence: 'Despite',
    options: '["Despite of","Despite","In despite","Although of"]',
    explanation: '"Despite" + noun (no "of"). "In spite of" + noun (with "of").',
    explanation_es: '"Despite" + sustantivo (sin "of"). "In spite of" + sustantivo (con "of").',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'A pesar del mal tiempo, el evento siguió adelante.',
  },
  {
    id: 'off_ec_009',
    sentence: 'He prevented me to leave the room.',
    answer: 'He prevented me from leaving the room.',
    base_word: 'to leave',
    context_sentence: 'from leaving',
    options: '["to leave","from leaving","leaving","of leaving"]',
    explanation: '"Prevent sb from + -ing". Not "prevent sb to do".',
    explanation_es: '"Prevent sb from + -ing". No "prevent sb to do".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Me impidió salir de la habitación.',
  },
  {
    id: 'off_ec_010',
    sentence: 'Neither the teacher nor the students was happy about the decision.',
    answer: 'Neither the teacher nor the students were happy about the decision.',
    base_word: 'was',
    context_sentence: 'were',
    options: '["was","were","is","are"]',
    explanation: '"Neither...nor" — verb agrees with the nearest subject ("students" = plural → "were").',
    explanation_es: '"Neither...nor" — el verbo concuerda con el sujeto más cercano ("students" = plural → "were").',
    cefr_level: 'C1', category: 'error_correction', difficulty: 3,
    is_official: false,
    answer_es: 'Ni el profesor ni los alumnos estaban contentos.',
  },
  {
    id: 'off_ec_011',
    sentence: 'I wish I can speak French fluently.',
    answer: 'I wish I could speak French fluently.',
    base_word: 'can',
    context_sentence: 'could',
    options: '["can","could","would","should"]',
    explanation: '"I wish" + past simple for present wishes. "Can" → "could".',
    explanation_es: '"I wish" + pasado simple para deseos presentes. "Can" → "could".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Desearía poder hablar francés con fluidez.',
  },
  {
    id: 'off_ec_012',
    sentence: 'He admitted to steal the money from the safe.',
    answer: 'He admitted to stealing the money from the safe.',
    base_word: 'to steal',
    context_sentence: 'to stealing',
    options: '["to steal","to stealing","stealing","to have steal"]',
    explanation: '"Admit to" + -ing. "To" is a preposition here.',
    explanation_es: '"Admit to" + -ing. "To" es preposición aquí.',
    cefr_level: 'C1', category: 'error_correction', difficulty: 3,
    is_official: false,
    answer_es: 'Admitió haber robado el dinero de la caja.',
  },
  {
    id: 'off_ec_013',
    sentence: 'Seldom I have seen such a beautiful sunset.',
    answer: 'Seldom have I seen such a beautiful sunset.',
    base_word: 'I have',
    context_sentence: 'have I',
    options: '["I have","have I","I had","had I"]',
    explanation: '"Seldom" at the start → inversion: "Seldom have I...".',
    explanation_es: '"Seldom" al inicio → inversión: "Seldom have I...".',
    cefr_level: 'C1', category: 'error_correction', difficulty: 3,
    is_official: false,
    answer_es: 'Rara vez he visto un atardecer tan bonito.',
  },
  {
    id: 'off_ec_014',
    sentence: 'The furniture in the room are very old.',
    answer: 'The furniture in the room is very old.',
    base_word: 'are',
    context_sentence: 'is',
    options: '["are","is","were","was"]',
    explanation: '"Furniture" is uncountable in English → singular verb.',
    explanation_es: '"Furniture" es incontable en inglés → verbo en singular.',
    cefr_level: 'B1', category: 'error_correction', difficulty: 1,
    is_official: false,
    answer_es: 'Los muebles de la habitación son muy viejos.',
  },
  {
    id: 'off_ec_015',
    sentence: 'She accused me for breaking the window.',
    answer: 'She accused me of breaking the window.',
    base_word: 'for',
    context_sentence: 'of',
    options: '["for","of","about","with"]',
    explanation: '"Accuse sb OF + -ing". Not "for" (influenced by "blame sb for").',
    explanation_es: '"Accuse sb OF + -ing". No "for" (influencia de "blame sb for").',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Me acusó de romper la ventana.',
  },
  {
    id: 'off_ec_016',
    sentence: 'There is less cars on the road today.',
    answer: 'There are fewer cars on the road today.',
    base_word: 'less',
    context_sentence: 'fewer',
    options: '["less","fewer","lesser","few"]',
    explanation: '"Fewer" + countable plural nouns. "Less" + uncountable nouns.',
    explanation_es: '"Fewer" + sustantivos contables plurales. "Less" + sustantivos incontables.',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Hay menos coches en la carretera hoy.',
  },
  {
    id: 'off_ec_017',
    sentence: 'He congratulated me for passing the exam.',
    answer: 'He congratulated me on passing the exam.',
    base_word: 'for',
    context_sentence: 'on',
    options: '["for","on","about","with"]',
    explanation: '"Congratulate sb ON + -ing". Not "for".',
    explanation_es: '"Congratulate sb ON + -ing". No "for".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Me felicitó por aprobar el examen.',
  },
  {
    id: 'off_ec_018',
    sentence: 'He denied that he had not been involved.',
    answer: 'He denied that he had been involved.',
    base_word: 'had not',
    context_sentence: 'had',
    options: '["had not","had","has not","has"]',
    explanation: '"Deny" is already negative in meaning. Don\'t add "not" after it → double negative.',
    explanation_es: '"Deny" ya es negativo en significado. No añadas "not" → doble negación.',
    cefr_level: 'C1', category: 'error_correction', difficulty: 3,
    is_official: false,
    answer_es: 'Negó haber estado involucrado.',
  },
  {
    id: 'off_ec_019',
    sentence: 'I\'d rather to stay at home tonight.',
    answer: 'I\'d rather stay at home tonight.',
    base_word: 'to stay',
    context_sentence: 'stay',
    options: '["to stay","stay","staying","stayed"]',
    explanation: '"Would rather" + bare infinitive (no "to").',
    explanation_es: '"Would rather" + infinitivo sin "to".',
    cefr_level: 'B2', category: 'error_correction', difficulty: 2,
    is_official: false,
    answer_es: 'Preferiría quedarme en casa esta noche.',
  },
  {
    id: 'off_ec_020',
    sentence: 'Under no circumstances you should open this door.',
    answer: 'Under no circumstances should you open this door.',
    base_word: 'you should',
    context_sentence: 'should you',
    options: '["you should","should you","you will","will you"]',
    explanation: '"Under no circumstances" at the start → inversion: "should you".',
    explanation_es: '"Under no circumstances" al inicio → inversión: "should you".',
    cefr_level: 'C1', category: 'error_correction', difficulty: 3,
    is_official: false,
    answer_es: 'Bajo ninguna circunstancia deberías abrir esta puerta.',
  },
];
