// Cambridge Use of English Part 2 — Open Cloze
// No options given: the student must write the missing grammar word.
// Covers: articles, prepositions, auxiliaries, pronouns, relative pronouns,
// quantifiers, determiners, conjunctions, modal verbs, phrasal verb particles.
// Inspired by Complete First, Complete Advanced, English Vocabulary in Use.

export interface OpenClozeSeedItem {
  id: string;
  sentence: string;       // Sentence with ___
  answer: string;          // The missing word (1 word)
  options: string | null;  // null — Open Cloze has no options
  explanation: string;
  explanation_es: string;
  cefr_level: string;
  category: string;
  difficulty: number;
  base_word: string | null;
  context_sentence: string | null;
  answer_es?: string;
}

export const OPEN_CLOZE_EXERCISES: OpenClozeSeedItem[] = [
  // ═══════════════════════════════════════
  // ARTICLES (a / an / the / -)
  // ═══════════════════════════════════════
  {
    id: 'oc_001',
    sentence: 'She plays ___ piano beautifully.',
    answer: 'the',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Musical instruments take "the" when talking about playing them: play the piano.',
    explanation_es: 'Los instrumentos musicales llevan "the" al hablar de tocarlos: play the piano.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'el / la / los / las',
  },
  {
    id: 'oc_002',
    sentence: 'What ___ amazing view from the top of the mountain!',
    answer: 'an',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Exclamations with "what" + singular countable noun need an article. "Amazing" starts with a vowel sound → "an".',
    explanation_es: 'Exclamaciones con "what" + sustantivo contable singular necesitan artículo. "Amazing" empieza con vocal → "an".',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'un / una',
  },
  {
    id: 'oc_003',
    sentence: '___ advice she gave me was really useful.',
    answer: 'The',
    options: null, base_word: null, context_sentence: null,
    explanation: '"The" is needed because we refer to specific advice (the advice SHE gave me).',
    explanation_es: '"The" porque nos referimos a un consejo específico (el que ella me dio).',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'el / la / los / las',
  },

  // ═══════════════════════════════════════
  // PREPOSITIONS
  // ═══════════════════════════════════════
  {
    id: 'oc_004',
    sentence: 'She has been working here ___ 2019.',
    answer: 'since',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Since" is used with a specific point in time (2019). "For" is used with a duration.',
    explanation_es: '"Since" se usa con un momento específico (2019). "For" con una duración.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'desde / ya que',
  },
  {
    id: 'oc_005',
    sentence: 'He apologised ___ being late to the meeting.',
    answer: 'for',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: apologise FOR + -ing.',
    explanation_es: 'Colocación fija: apologise FOR + -ing.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'para / por',
  },
  {
    id: 'oc_006',
    sentence: 'The town is famous ___ its medieval castle.',
    answer: 'for',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: famous FOR something.',
    explanation_es: 'Colocación fija: famous FOR algo.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'para / por',
  },
  {
    id: 'oc_007',
    sentence: 'I am not very keen ___ spicy food.',
    answer: 'on',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: keen ON something.',
    explanation_es: 'Colocación fija: keen ON algo.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_008',
    sentence: 'She succeeded ___ passing the exam on her first attempt.',
    answer: 'in',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: succeed IN + -ing.',
    explanation_es: 'Colocación fija: succeed IN + -ing.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_009',
    sentence: 'We are looking forward ___ hearing from you soon.',
    answer: 'to',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Look forward to" — here "to" is a preposition followed by a gerund.',
    explanation_es: '"Look forward to" — aquí "to" es preposición seguida de gerundio.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'a / para',
  },

  // ═══════════════════════════════════════
  // AUXILIARY & MODAL VERBS
  // ═══════════════════════════════════════
  {
    id: 'oc_010',
    sentence: 'You ___ better hurry or you will miss the train.',
    answer: 'had',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Had better" = strong advice / warning. Often contracted to "\'d better".',
    explanation_es: '"Had better" = consejo fuerte / advertencia. A menudo contraído: "\'d better".',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: '(auxiliar) había',
  },
  {
    id: 'oc_011',
    sentence: 'She ___ have left already — her coat is gone.',
    answer: 'must',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Must have + pp" expresses a logical deduction about the past (high certainty).',
    explanation_es: '"Must have + pp" expresa deducción lógica sobre el pasado (alta certeza).',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'deber / tener que',
  },
  {
    id: 'oc_012',
    sentence: 'If I ___ you, I would take the job offer.',
    answer: 'were',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Second conditional: "If I were you" (subjunctive — "were" for all persons).',
    explanation_es: 'Segundo condicional: "If I were you" (subjuntivo — "were" para todas las personas).',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: '(pasado) eran / estaban',
  },
  {
    id: 'oc_013',
    sentence: '___ it not been for your help, I would have failed.',
    answer: 'Had',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Inverted third conditional: "Had it not been for" = "If it had not been for".',
    explanation_es: 'Tercer condicional invertido: "Had it not been for" = "If it had not been for".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: '(auxiliar) había',
  },
  {
    id: 'oc_014',
    sentence: 'You ___ not have told her — it was a secret!',
    answer: 'should',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Should not have + pp" = criticism about a past action.',
    explanation_es: '"Should not have + pp" = crítica sobre una acción pasada.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: '(condicional) debería',
  },

  // ═══════════════════════════════════════
  // RELATIVE PRONOUNS & CONNECTORS
  // ═══════════════════════════════════════
  {
    id: 'oc_015',
    sentence: 'The hotel ___ we stayed was right on the beach.',
    answer: 'where',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Where" is the relative adverb for places. Also acceptable: "in which".',
    explanation_es: '"Where" es el adverbio relativo para lugares. También aceptable: "in which".',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'donde',
  },
  {
    id: 'oc_016',
    sentence: 'That is the man ___ daughter won the competition.',
    answer: 'whose',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Whose" = possessive relative pronoun (the man\'s daughter).',
    explanation_es: '"Whose" = pronombre relativo posesivo (la hija del hombre).',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'de quién',
  },
  {
    id: 'oc_017',
    sentence: 'No matter ___ hard he tries, he never gives up.',
    answer: 'how',
    options: null, base_word: null, context_sentence: null,
    explanation: '"No matter how + adjective/adverb" = regardless of the degree.',
    explanation_es: '"No matter how + adj/adv" = sin importar el grado.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'cómo',
  },

  // ═══════════════════════════════════════
  // QUANTIFIERS & DETERMINERS
  // ═══════════════════════════════════════
  {
    id: 'oc_018',
    sentence: 'There is very ___ we can do about the situation.',
    answer: 'little',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Very little" = almost nothing (with uncountable nouns / abstract meaning).',
    explanation_es: '"Very little" = casi nada (con sustantivos incontables / sentido abstracto).',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'incluso',
  },
  {
    id: 'oc_019',
    sentence: '___ of the students passed the exam — it was too difficult.',
    answer: 'None',
    options: null, base_word: null, context_sentence: null,
    explanation: '"None of" = not one / zero. Followed by "of the + plural noun".',
    explanation_es: '"None of" = ninguno. Seguido de "of the + sustantivo plural".',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'debería (inversión formal)',
  },
  {
    id: 'oc_020',
    sentence: 'He earns twice ___ much as his brother.',
    answer: 'as',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Comparison structure: "twice AS much AS" = el doble que.',
    explanation_es: 'Estructura comparativa: "twice AS much AS" = el doble que.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'como / tan',
  },

  // ═══════════════════════════════════════
  // PRONOUNS & REFERENCE
  // ═══════════════════════════════════════
  {
    id: 'oc_021',
    sentence: 'It was ___ who called the police, not me.',
    answer: 'he',
    options: null, base_word: null, context_sentence: null,
    explanation: 'After "it was" in a cleft sentence, use subject pronoun: "It was he who...".',
    explanation_es: 'Tras "it was" en una oración hendida, pronombre sujeto: "It was he who...".',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'yo mismo/a',
  },
  {
    id: 'oc_022',
    sentence: 'I cut ___ while I was chopping vegetables.',
    answer: 'myself',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Reflexive pronoun: subject and object are the same person → "myself".',
    explanation_es: 'Pronombre reflexivo: sujeto y objeto son la misma persona → "myself".',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'mejor',
  },

  // ═══════════════════════════════════════
  // PHRASAL VERB PARTICLES
  // ═══════════════════════════════════════
  {
    id: 'oc_023',
    sentence: 'Could you look ___ my cat while I am away?',
    answer: 'after',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Look after" = take care of.',
    explanation_es: '"Look after" = cuidar de.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'bien',
  },
  {
    id: 'oc_024',
    sentence: 'I came ___ an old photo album in the attic.',
    answer: 'across',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Come across" = find by chance.',
    explanation_es: '"Come across" = encontrar por casualidad.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'hasta',
  },
  {
    id: 'oc_025',
    sentence: 'The meeting has been put ___ until next week.',
    answer: 'off',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Put off" = postpone.',
    explanation_es: '"Put off" = posponer.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'después de',
  },

  // ═══════════════════════════════════════
  // FIXED EXPRESSIONS & GRAMMAR PATTERNS
  // ═══════════════════════════════════════
  {
    id: 'oc_026',
    sentence: 'There is no point ___ complaining about it now.',
    answer: 'in',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed expression: "There is no point in + -ing" = it\'s useless to.',
    explanation_es: 'Expresión fija: "There is no point in + -ing" = no tiene sentido.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_027',
    sentence: 'He takes ___ his father — they look very similar.',
    answer: 'after',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Take after" = resemble / look like (a family member).',
    explanation_es: '"Take after" = parecerse a (un familiar).',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'después de',
  },
  {
    id: 'oc_028',
    sentence: 'She is ___ used to living on her own that it no longer bothers her.',
    answer: 'so',
    options: null, base_word: null, context_sentence: null,
    explanation: '"So + adjective + that" = result clause. "So used to... that...".',
    explanation_es: '"So + adjetivo + that" = cláusula de resultado.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'así que / por lo tanto',
  },
  {
    id: 'oc_029',
    sentence: '___ the fact that he was ill, he went to work.',
    answer: 'Despite',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Despite the fact that" = although / in spite of the fact that.',
    explanation_es: '"Despite the fact that" = aunque / a pesar de que.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'a pesar de',
  },
  {
    id: 'oc_030',
    sentence: 'By the time we arrived, the film had ___ started.',
    answer: 'already',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Had already + pp" = past perfect emphasising the action was completed before another past event.',
    explanation_es: '"Had already + pp" = pluscuamperfecto enfatizando que la acción ya había ocurrido.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'él (formal, sujeto)',
  },

  // ═══════════════════════════════════════
  // C1 — ADVANCED OPEN CLOZE
  // ═══════════════════════════════════════
  {
    id: 'oc_031',
    sentence: 'Little ___ he know what was about to happen.',
    answer: 'did',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Negative adverb fronting triggers inversion: "Little did he know" = He didn\'t know at all.',
    explanation_es: 'Adverbio negativo al inicio activa inversión: "Little did he know" = No tenía ni idea.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: '(auxiliar pasado)',
  },
  {
    id: 'oc_032',
    sentence: 'Not until she left ___ I realise how much she meant to me.',
    answer: 'did',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Not until..." at the start → inversion in the main clause: "did I realise".',
    explanation_es: '"Not until..." al inicio → inversión en la oración principal: "did I realise".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: '(auxiliar pasado)',
  },
  {
    id: 'oc_033',
    sentence: 'Rarely ___ such a talented musician perform in this town.',
    answer: 'does',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Rarely" at the start → inversion: "Rarely does + subject + verb".',
    explanation_es: '"Rarely" al inicio → inversión: "Rarely does + sujeto + verbo".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: '(auxiliar) hace',
  },
  {
    id: 'oc_034',
    sentence: 'The more you practise, the ___ you will become.',
    answer: 'better',
    options: null, base_word: null, context_sentence: null,
    explanation: '"The more... the better" = double comparative structure.',
    explanation_es: '"The more... the better" = estructura comparativa doble.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'mejor',
  },
  {
    id: 'oc_035',
    sentence: 'Under no circumstances ___ you touch that equipment.',
    answer: 'should',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Under no circumstances" at the start → inversion: "should you" = you must not.',
    explanation_es: '"Under no circumstances" al inicio → inversión: "should you" = no debes.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: '(condicional) debería',
  },
  {
    id: 'oc_036',
    sentence: 'It was not ___ midnight that the guests finally left.',
    answer: 'until',
    options: null, base_word: null, context_sentence: null,
    explanation: '"It was not until + time + that" = emphasising when something happened.',
    explanation_es: '"It was not until + tiempo + that" = enfatizando cuándo ocurrió algo.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: 'hasta',
  },
  {
    id: 'oc_037',
    sentence: 'She acted as ___ nothing had happened.',
    answer: 'if',
    options: null, base_word: null, context_sentence: null,
    explanation: '"As if" + past perfect = unreal comparison about a past event.',
    explanation_es: '"As if" + pluscuamperfecto = comparación irreal sobre un evento pasado.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'si (condicional)',
  },
  {
    id: 'oc_038',
    sentence: 'I would rather you ___ tell anyone about this.',
    answer: "didn't",
    options: null, base_word: null, context_sentence: null,
    explanation: '"Would rather + subject + past simple" for preferences about other people\'s actions.',
    explanation_es: '"Would rather + sujeto + pasado simple" para preferencias sobre acciones de otros.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: 'a pesar de',
  },
  {
    id: 'oc_039',
    sentence: 'It is high time we ___ something about climate change.',
    answer: 'did',
    options: null, base_word: null, context_sentence: null,
    explanation: '"It\'s high time + past simple" = something should have happened already.',
    explanation_es: '"It\'s high time + pasado simple" = algo debería haber pasado ya.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: '(auxiliar pasado)',
  },
  {
    id: 'oc_040',
    sentence: 'Much ___ I admire her work, I disagree with her conclusion.',
    answer: 'as',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Much as" = although / even though (formal concession).',
    explanation_es: '"Much as" = aunque (concesión formal).',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: 'como / tan',
  },

  // ═══════════════════════════════════════
  // MORE PREPOSITIONS & COLLOCATIONS
  // ═══════════════════════════════════════
  {
    id: 'oc_041',
    sentence: 'She was accused ___ stealing money from the company.',
    answer: 'of',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: accuse sb OF + -ing.',
    explanation_es: 'Colocación fija: accuse sb OF + -ing.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'de',
  },
  {
    id: 'oc_042',
    sentence: 'The teacher insisted ___ everyone being on time.',
    answer: 'on',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: insist ON + -ing / noun.',
    explanation_es: 'Colocación fija: insist ON + -ing / sustantivo.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_043',
    sentence: 'I congratulated her ___ passing the exam.',
    answer: 'on',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: congratulate sb ON + -ing.',
    explanation_es: 'Colocación fija: congratulate sb ON + -ing.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_044',
    sentence: 'They blamed the accident ___ the bad weather.',
    answer: 'on',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: blame sth ON sth/sb.',
    explanation_es: 'Colocación fija: blame sth ON sth/sb.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_045',
    sentence: 'He warned me ___ walking alone at night.',
    answer: 'against',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: warn sb AGAINST + -ing = advise not to do.',
    explanation_es: 'Colocación fija: warn sb AGAINST + -ing = aconsejar no hacer.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'contra / en contra de',
  },
  {
    id: 'oc_046',
    sentence: 'We are ___ favour of the new proposal.',
    answer: 'in',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed expression: IN favour of = supporting.',
    explanation_es: 'Expresión fija: IN favour of = a favor de.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_047',
    sentence: 'She is very good ___ dealing with difficult customers.',
    answer: 'at',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: good AT + -ing.',
    explanation_es: 'Colocación fija: good AT + -ing.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'en',
  },
  {
    id: 'oc_048',
    sentence: 'The experiment resulted ___ a major breakthrough.',
    answer: 'in',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: result IN = lead to.',
    explanation_es: 'Colocación fija: result IN = conducir a.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_049',
    sentence: 'I object ___ being treated like a child.',
    answer: 'to',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: object TO + -ing.',
    explanation_es: 'Colocación fija: object TO + -ing.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'a / para',
  },
  {
    id: 'oc_050',
    sentence: 'They prevented us ___ entering the building.',
    answer: 'from',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Fixed collocation: prevent sb FROM + -ing.',
    explanation_es: 'Colocación fija: prevent sb FROM + -ing.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'de / desde',
  },

  // ═══════════════════════════════════════
  // MORE AUXILIARIES, TENSES & STRUCTURES
  // ═══════════════════════════════════════
  {
    id: 'oc_051',
    sentence: 'She ___ rather not discuss it in public.',
    answer: 'would',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Would rather" + bare infinitive = preference.',
    explanation_es: '"Would rather" + infinitivo sin to = preferencia.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: '(condicional) haría',
  },
  {
    id: 'oc_052',
    sentence: 'The car needs ___ be repaired before the trip.',
    answer: 'to',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Need to be + pp" = passive necessity. Also: "needs repairing".',
    explanation_es: '"Need to be + pp" = necesidad pasiva. También: "needs repairing".',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'a / para',
  },
  {
    id: 'oc_053',
    sentence: 'He ___ to be a very famous actor when he was younger.',
    answer: 'used',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Used to" = past habit / state that no longer exists.',
    explanation_es: '"Used to" = hábito / estado pasado que ya no existe.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'acostumbraba / solía',
  },
  {
    id: 'oc_054',
    sentence: 'By this time next year, she ___ have graduated.',
    answer: 'will',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Will have + pp" = future perfect for actions completed before a future point.',
    explanation_es: '"Will have + pp" = futuro perfecto para acciones completadas antes de un punto futuro.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: '(futuro)',
  },
  {
    id: 'oc_055',
    sentence: 'You needn\'t ___ brought your umbrella — it didn\'t rain.',
    answer: 'have',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Needn\'t have + pp" = did something that turned out to be unnecessary.',
    explanation_es: '"Needn\'t have + pp" = hiciste algo que resultó ser innecesario.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: '(auxiliar) haber',
  },
  {
    id: 'oc_056',
    sentence: 'I wish I ___ spoken to her before she left.',
    answer: 'had',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Wish + past perfect" = regret about the past.',
    explanation_es: '"Wish + pluscuamperfecto" = arrepentimiento sobre el pasado.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: '(auxiliar) había',
  },
  {
    id: 'oc_057',
    sentence: 'Supposing you ___ offered the job, would you take it?',
    answer: 'were',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Supposing + past simple" = hypothetical situation, like second conditional.',
    explanation_es: '"Supposing + pasado simple" = situación hipotética, como segundo condicional.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: '(pasado) eran / estaban',
  },
  {
    id: 'oc_058',
    sentence: 'He can\'t ___ been at the party — he was in Paris.',
    answer: 'have',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Can\'t have + pp" = certainty that something didn\'t happen in the past.',
    explanation_es: '"Can\'t have + pp" = certeza de que algo no ocurrió en el pasado.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: '(auxiliar) haber',
  },
  {
    id: 'oc_059',
    sentence: '___ you happen to see Tom, could you give him this?',
    answer: 'Should',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Should" in conditionals = "if by chance". More formal than "if".',
    explanation_es: '"Should" en condicionales = "si por casualidad". Más formal que "if".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: '(condicional) debería',
  },
  {
    id: 'oc_060',
    sentence: 'They are said ___ be the best team in the league.',
    answer: 'to',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Passive reporting structure: "be said TO + infinitive".',
    explanation_es: 'Estructura pasiva impersonal: "be said TO + infinitivo".',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'a / para',
  },

  // ═══════════════════════════════════════
  // MORE PHRASAL VERBS & PARTICLES
  // ═══════════════════════════════════════
  {
    id: 'oc_061',
    sentence: 'The fire brigade managed to put ___ the fire quickly.',
    answer: 'out',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Put out" = extinguish.',
    explanation_es: '"Put out" = apagar (un fuego).',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'fuera',
  },
  {
    id: 'oc_062',
    sentence: 'We need to find ___ what time the shop closes.',
    answer: 'out',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Find out" = discover / learn information.',
    explanation_es: '"Find out" = descubrir / averiguar.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'fuera',
  },
  {
    id: 'oc_063',
    sentence: 'I ran ___ an old friend at the supermarket.',
    answer: 'into',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Run into" = meet by chance.',
    explanation_es: '"Run into" = encontrarse con alguien por casualidad.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'dentro de / hacia',
  },
  {
    id: 'oc_064',
    sentence: 'Could you turn ___ the volume? I can barely hear it.',
    answer: 'up',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Turn up" = increase the volume / intensity.',
    explanation_es: '"Turn up" = subir el volumen / intensidad.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'arriba',
  },
  {
    id: 'oc_065',
    sentence: 'She broke ___ in tears when she heard the news.',
    answer: 'down',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Break down" = lose emotional control / start crying.',
    explanation_es: '"Break down" = perder el control emocional / echarse a llorar.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'abajo',
  },
  {
    id: 'oc_066',
    sentence: 'The plane took ___ twenty minutes late.',
    answer: 'off',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Take off" = leave the ground (aircraft).',
    explanation_es: '"Take off" = despegar (avión).',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'fuera / apagado',
  },
  {
    id: 'oc_067',
    sentence: 'I can\'t make ___ what the sign says from here.',
    answer: 'out',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Make out" = manage to see / read / understand something difficult.',
    explanation_es: '"Make out" = lograr ver / leer / entender algo difícil.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'fuera',
  },
  {
    id: 'oc_068',
    sentence: 'He set ___ on a journey around the world.',
    answer: 'off',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Set off" = start a journey.',
    explanation_es: '"Set off" = emprender un viaje.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'fuera / apagado',
  },

  // ═══════════════════════════════════════
  // MORE CONJUNCTIONS & LINKING
  // ═══════════════════════════════════════
  {
    id: 'oc_069',
    sentence: 'He went to work ___ spite of feeling unwell.',
    answer: 'in',
    options: null, base_word: null, context_sentence: null,
    explanation: '"In spite of" = despite. Always "in spite of", never "in spite".',
    explanation_es: '"In spite of" = a pesar de. Siempre "in spite of", nunca solo "in spite".',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_070',
    sentence: 'She went ahead with the plan ___ though everyone disagreed.',
    answer: 'even',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Even though" = although (with emphasis).',
    explanation_es: '"Even though" = aunque (con énfasis).',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'incluso / ni siquiera',
  },
  {
    id: 'oc_071',
    sentence: '___ long as you study hard, you will pass the exam.',
    answer: 'As',
    options: null, base_word: null, context_sentence: null,
    explanation: '"As long as" = on condition that / provided that.',
    explanation_es: '"As long as" = siempre que / con la condición de que.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'como / ya que',
  },
  {
    id: 'oc_072',
    sentence: 'Take an umbrella ___ case it rains.',
    answer: 'in',
    options: null, base_word: null, context_sentence: null,
    explanation: '"In case" = as a precaution / because it might happen.',
    explanation_es: '"In case" = por si acaso / porque podría pasar.',
    cefr_level: 'B2', category: 'open_cloze', difficulty: 2,
    answer_es: 'en',
  },
  {
    id: 'oc_073',
    sentence: 'He speaks French as ___ as German fluently.',
    answer: 'well',
    options: null, base_word: null, context_sentence: null,
    explanation: '"As well as" = in addition to.',
    explanation_es: '"As well as" = además de.',
    cefr_level: 'B1', category: 'open_cloze', difficulty: 1,
    answer_es: 'bien',
  },

  // ═══════════════════════════════════════
  // MORE ADVANCED GRAMMAR (C1)
  // ═══════════════════════════════════════
  {
    id: 'oc_074',
    sentence: 'Only ___ she left did I realise my mistake.',
    answer: 'after',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Only after + clause" at the start → inversion in main clause.',
    explanation_es: '"Only after + cláusula" al inicio → inversión en la oración principal.',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: 'después de',
  },
  {
    id: 'oc_075',
    sentence: 'Scarcely had she arrived ___ the phone rang.',
    answer: 'when',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Scarcely had... when..." = as soon as (formal). Also: "hardly... when...".',
    explanation_es: '"Scarcely had... when..." = en cuanto (formal). También: "hardly... when...".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: 'cuando',
  },
  {
    id: 'oc_076',
    sentence: 'So impressive ___ his speech that everyone applauded.',
    answer: 'was',
    options: null, base_word: null, context_sentence: null,
    explanation: '"So + adjective" at the start → inversion: "So impressive was...".',
    explanation_es: '"So + adjetivo" al inicio → inversión: "So impressive was...".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: '(pasado) era / estaba',
  },
  {
    id: 'oc_077',
    sentence: 'Were she ___ agree, we could start the project immediately.',
    answer: 'to',
    options: null, base_word: null, context_sentence: null,
    explanation: 'Inverted conditional: "Were she to agree" = "If she agreed/were to agree".',
    explanation_es: 'Condicional invertido: "Were she to agree" = "If she agreed/were to agree".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: 'a / para',
  },
  {
    id: 'oc_078',
    sentence: 'At no time ___ the company aware of the problem.',
    answer: 'was',
    options: null, base_word: null, context_sentence: null,
    explanation: '"At no time" at the start → inversion: "At no time was the company...".',
    explanation_es: '"At no time" al inicio → inversión: "At no time was the company...".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: '(pasado) era / estaba',
  },
  {
    id: 'oc_079',
    sentence: 'Only by working together ___ we solve this problem.',
    answer: 'can',
    options: null, base_word: null, context_sentence: null,
    explanation: '"Only by + -ing" at the start → inversion: "can we".',
    explanation_es: '"Only by + -ing" al inicio → inversión: "can we".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: 'poder',
  },
  {
    id: 'oc_080',
    sentence: 'No sooner had I sat down ___ the doorbell rang.',
    answer: 'than',
    options: null, base_word: null, context_sentence: null,
    explanation: '"No sooner... than..." = as soon as. Always paired with "than".',
    explanation_es: '"No sooner... than..." = en cuanto. Siempre con "than".',
    cefr_level: 'C1', category: 'open_cloze', difficulty: 3,
    answer_es: 'que (comparativo)',
  },
];
