// Ejercicios de "rellenar la partícula" para phrasal verbs.
// El verbo se mantiene y se oculta la PARTÍCULA (up/down/on/off/out/in...),
// que es lo que fija el significado. Es el ejercicio más eficaz para
// interiorizar phrasal verbs. Reutiliza la infraestructura de gap_fill
// (mismo formato que los seeds Cambridge). Categoría: 'phrasal_particle'.
import type { GapFillSeedItem } from './gapFillSeed';

export const PHRASAL_VERB_PARTICLES: GapFillSeedItem[] = [
  // ── A2 (difficulty 1) ──
  { id: 'pv_part_001', sentence: "It's cold — put ___ your coat.", answer: 'on',
    options: '["on","off","up","in"]',
    explanation: '"Put on" means to dress in clothing.',
    explanation_es: '"Put on" = ponerse (ropa).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'ponerse (ropa)' },
  { id: 'pv_part_002', sentence: 'Turn ___ the lights before you go to bed.', answer: 'off',
    options: '["off","on","up","out"]',
    explanation: '"Turn off" means to switch something off.',
    explanation_es: '"Turn off" = apagar.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'apagar' },
  { id: 'pv_part_003', sentence: "It's dark in here. Can you turn ___ the light?", answer: 'on',
    options: '["on","off","down","out"]',
    explanation: '"Turn on" means to switch something on.',
    explanation_es: '"Turn on" = encender.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'encender' },
  { id: 'pv_part_004', sentence: "I'll pick you ___ after work.", answer: 'up',
    options: '["up","out","on","off"]',
    explanation: '"Pick up" here means to collect someone.',
    explanation_es: '"Pick up" = recoger (a alguien).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'recoger (a alguien)' },
  { id: 'pv_part_005', sentence: 'I grew ___ in a small town.', answer: 'up',
    options: '["up","on","out","over"]',
    explanation: '"Grow up" means to become an adult / spend your childhood.',
    explanation_es: '"Grow up" = crecer / criarse.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'criarse' },
  { id: 'pv_part_006', sentence: 'I wake ___ at seven every morning.', answer: 'up',
    options: '["up","on","out","off"]',
    explanation: '"Wake up" means to stop sleeping.',
    explanation_es: '"Wake up" = despertarse.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'despertarse' },
  { id: 'pv_part_007', sentence: 'Please sit ___ and make yourself comfortable.', answer: 'down',
    options: '["down","up","in","on"]',
    explanation: '"Sit down" means to take a seat.',
    explanation_es: '"Sit down" = sentarse.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'sentarse' },
  { id: 'pv_part_008', sentence: 'Hurry ___! We are going to miss the train.', answer: 'up',
    options: '["up","on","out","off"]',
    explanation: '"Hurry up" means to be quick.',
    explanation_es: '"Hurry up" = darse prisa.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'darse prisa' },
  { id: 'pv_part_009', sentence: 'Come ___ and have a seat.', answer: 'in',
    options: '["in","on","up","over"]',
    explanation: '"Come in" means to enter.',
    explanation_es: '"Come in" = entrar / pasar.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'entrar' },
  { id: 'pv_part_010', sentence: 'The plane took ___ right on time.', answer: 'off',
    options: '["off","up","out","over"]',
    explanation: '"Take off" (for planes) means to leave the ground.',
    explanation_es: '"Take off" (aviones) = despegar.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'despegar' },
  { id: 'pv_part_011', sentence: 'Can I try ___ these shoes before I buy them?', answer: 'on',
    options: '["on","up","out","in"]',
    explanation: '"Try on" means to test clothing for fit.',
    explanation_es: '"Try on" = probarse (ropa).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'probarse (ropa)' },
  { id: 'pv_part_012', sentence: 'She looks ___ her little brother after school.', answer: 'after',
    options: '["after","up","out","for"]',
    explanation: '"Look after" means to take care of someone.',
    explanation_es: '"Look after" = cuidar (de).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'cuidar (de)' },

  // ── B1 (difficulty 2) ──
  { id: 'pv_part_013', sentence: "We've run ___ of coffee again.", answer: 'out',
    options: '["out","off","up","down"]',
    explanation: '"Run out (of)" means to have no more of something.',
    explanation_es: '"Run out of" = quedarse sin.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'quedarse sin' },
  { id: 'pv_part_014', sentence: "Don't give ___ — you're almost there!", answer: 'up',
    options: '["up","in","out","off"]',
    explanation: '"Give up" means to stop trying / surrender.',
    explanation_es: '"Give up" = rendirse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'rendirse' },
  { id: 'pv_part_015', sentence: 'My car broke ___ on the motorway.', answer: 'down',
    options: '["down","up","off","out"]',
    explanation: '"Break down" (for vehicles/machines) means to stop working.',
    explanation_es: '"Break down" = averiarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'averiarse' },
  { id: 'pv_part_016', sentence: 'Can you turn ___ the volume? It is too loud.', answer: 'down',
    options: '["down","off","up","out"]',
    explanation: '"Turn down" means to lower the volume.',
    explanation_es: '"Turn down" = bajar (el volumen).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'bajar (volumen)' },
  { id: 'pv_part_017', sentence: 'The fire alarm went ___ during the meeting.', answer: 'off',
    options: '["off","on","up","out"]',
    explanation: '"Go off" means (for an alarm) to start sounding.',
    explanation_es: '"Go off" = sonar (una alarma).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'sonar (alarma)' },
  { id: 'pv_part_018', sentence: "I can't figure ___ how this machine works.", answer: 'out',
    options: '["out","up","on","in"]',
    explanation: '"Figure out" means to understand / solve something.',
    explanation_es: '"Figure out" = averiguar / resolver.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'averiguar' },
  { id: 'pv_part_019', sentence: "Look ___ the word if you don't know what it means.", answer: 'up',
    options: '["up","out","on","into"]',
    explanation: '"Look up" means to search for information.',
    explanation_es: '"Look up" = buscar (información).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'buscar (información)' },
  { id: 'pv_part_020', sentence: 'His grandfather passed ___ last winter.', answer: 'away',
    options: '["away","out","on","off"]',
    explanation: '"Pass away" is a polite way to say "die".',
    explanation_es: '"Pass away" = fallecer.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'fallecer' },
  { id: 'pv_part_021', sentence: "I'll deal ___ this problem tomorrow.", answer: 'with',
    options: '["with","in","out","on"]',
    explanation: '"Deal with" means to handle or take care of something.',
    explanation_es: '"Deal with" = ocuparse de / lidiar con.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'ocuparse de' },
  { id: 'pv_part_022', sentence: 'Just carry ___ with your work, I will wait.', answer: 'on',
    options: '["on","out","up","over"]',
    explanation: '"Carry on" means to continue.',
    explanation_es: '"Carry on" = seguir / continuar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'continuar' },
  { id: 'pv_part_023', sentence: 'I need to find ___ what really happened.', answer: 'out',
    options: '["out","up","off","in"]',
    explanation: '"Find out" means to discover information.',
    explanation_es: '"Find out" = descubrir / enterarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'descubrir' },
  { id: 'pv_part_024', sentence: 'Calm ___, everything is going to be fine.', answer: 'down',
    options: '["down","up","off","out"]',
    explanation: '"Calm down" means to relax / stop being upset.',
    explanation_es: '"Calm down" = calmarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'calmarse' },
  { id: 'pv_part_025', sentence: "Don't worry, it will all work ___ in the end.", answer: 'out',
    options: '["out","up","off","on"]',
    explanation: '"Work out" here means to end well / be resolved.',
    explanation_es: '"Work out" = salir bien / resolverse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'salir bien' },
  { id: 'pv_part_026', sentence: 'He never showed ___ for the interview.', answer: 'up',
    options: '["up","out","on","off"]',
    explanation: '"Show up" means to arrive / appear.',
    explanation_es: '"Show up" = presentarse / aparecer.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'presentarse' },
  { id: 'pv_part_027', sentence: 'How are you getting ___ in your new job?', answer: 'on',
    options: '["on","up","off","out"]',
    explanation: '"Get on" here means to progress / manage.',
    explanation_es: '"Get on" = ir / progresar (¿cómo te va?).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'ir / progresar' },
  { id: 'pv_part_028', sentence: "Stop putting ___ your homework and do it now.", answer: 'off',
    options: '["off","out","up","down"]',
    explanation: '"Put off" means to postpone / delay.',
    explanation_es: '"Put off" = aplazar / posponer.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'posponer' },
  { id: 'pv_part_029', sentence: 'Please don\'t bring ___ that subject at dinner.', answer: 'up',
    options: '["up","out","on","in"]',
    explanation: '"Bring up" means to mention / raise a topic.',
    explanation_es: '"Bring up" = mencionar / sacar (un tema).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'sacar (un tema)' },
  { id: 'pv_part_030', sentence: 'The doctor told me to cut ___ on sugar.', answer: 'down',
    options: '["down","off","out","up"]',
    explanation: '"Cut down (on)" means to reduce.',
    explanation_es: '"Cut down on" = reducir.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'reducir' },
  { id: 'pv_part_031', sentence: 'We usually hang ___ at the café on Fridays.', answer: 'out',
    options: '["out","up","on","over"]',
    explanation: '"Hang out" means to spend time relaxing (with friends).',
    explanation_es: '"Hang out" = pasar el rato / quedar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'pasar el rato' },
  { id: 'pv_part_032', sentence: 'They set ___ a new business last year.', answer: 'up',
    options: '["up","out","on","in"]',
    explanation: '"Set up" means to establish / create.',
    explanation_es: '"Set up" = montar / crear.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'montar / crear' },

  // ── B2 (difficulty 3) — partículas dobles ──
  { id: 'pv_part_033', sentence: 'I look ___ to seeing you next week.', answer: 'forward',
    options: '["forward","up","out","after"]',
    explanation: '"Look forward to" means to be excited about a future event.',
    explanation_es: '"Look forward to" = tener ganas de / esperar con ilusión.',
    cefr_level: 'B2', category: 'phrasal_particle', difficulty: 3, answer_es: 'tener ganas de' },
  { id: 'pv_part_034', sentence: 'She came ___ with a brilliant idea.', answer: 'up',
    options: '["up","out","on","over"]',
    explanation: '"Come up with" means to think of / produce an idea.',
    explanation_es: '"Come up with" = ocurrírsele (una idea).',
    cefr_level: 'B2', category: 'phrasal_particle', difficulty: 3, answer_es: 'ocurrírsele (una idea)' },
  { id: 'pv_part_035', sentence: "I can't put ___ with this noise any longer.", answer: 'up',
    options: '["up","out","off","on"]',
    explanation: '"Put up with" means to tolerate something unpleasant.',
    explanation_es: '"Put up with" = aguantar / soportar.',
    cefr_level: 'B2', category: 'phrasal_particle', difficulty: 3, answer_es: 'aguantar' },
  { id: 'pv_part_036', sentence: 'The thief got ___ with the stolen money.', answer: 'away',
    options: '["away","off","out","over"]',
    explanation: '"Get away with" means to escape punishment for something.',
    explanation_es: '"Get away with" = salir impune / salirse con la suya.',
    cefr_level: 'B2', category: 'phrasal_particle', difficulty: 3, answer_es: 'salir impune' },
];
