// Ejercicios de "rellenar la partícula" para phrasal verbs.
// El verbo se mantiene y se oculta la PARTÍCULA (up/down/on/off/out/in...),
// que es lo que fija el significado. Es el ejercicio más eficaz para
// interiorizar phrasal verbs. Reutiliza la infraestructura de gap_fill
// (mismo formato que los seeds Cambridge). Categoría: 'phrasal_particle'.
import type { GapFillSeedItem } from './gapFillSeed';

export const PHRASAL_VERB_PARTICLES: GapFillSeedItem[] = [
  // ── A2 (difficulty 1) ──
  { id: 'pv_part_001', sentence: "It's cold — put ___ your coat.", answer: 'on',
    options: '["on","off","up","in"]',
    explanation: '"Put on" means to dress in clothing.',
    explanation_es: '"Put on" = ponerse (ropa).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'ponerse (ropa)' },
  { id: 'pv_part_002', sentence: 'Turn ___ the lights before you go to bed.', answer: 'off',
    options: '["off","on","up","out"]',
    explanation: '"Turn off" means to switch something off.',
    explanation_es: '"Turn off" = apagar.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'apagar' },
  { id: 'pv_part_003', sentence: "It's dark in here. Can you turn ___ the light?", answer: 'on',
    options: '["on","off","down","out"]',
    explanation: '"Turn on" means to switch something on.',
    explanation_es: '"Turn on" = encender.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'encender' },
  { id: 'pv_part_004', sentence: "I'll pick you ___ after work.", answer: 'up',
    options: '["up","out","on","off"]',
    explanation: '"Pick up" here means to collect someone.',
    explanation_es: '"Pick up" = recoger (a alguien).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'recoger (a alguien)' },
  { id: 'pv_part_005', sentence: 'I grew ___ in a small town.', answer: 'up',
    options: '["up","on","out","over"]',
    explanation: '"Grow up" means to become an adult / spend your childhood.',
    explanation_es: '"Grow up" = crecer / criarse.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'criarse' },
  { id: 'pv_part_006', sentence: 'I wake ___ at seven every morning.', answer: 'up',
    options: '["up","on","out","off"]',
    explanation: '"Wake up" means to stop sleeping.',
    explanation_es: '"Wake up" = despertarse.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'despertarse' },
  { id: 'pv_part_007', sentence: 'Please sit ___ and make yourself comfortable.', answer: 'down',
    options: '["down","up","in","on"]',
    explanation: '"Sit down" means to take a seat.',
    explanation_es: '"Sit down" = sentarse.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'sentarse' },
  { id: 'pv_part_008', sentence: 'Hurry ___! We are going to miss the train.', answer: 'up',
    options: '["up","on","out","off"]',
    explanation: '"Hurry up" means to be quick.',
    explanation_es: '"Hurry up" = darse prisa.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'darse prisa' },
  { id: 'pv_part_009', sentence: 'Come ___ and have a seat.', answer: 'in',
    options: '["in","on","up","over"]',
    explanation: '"Come in" means to enter.',
    explanation_es: '"Come in" = entrar / pasar.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'entrar' },
  { id: 'pv_part_010', sentence: 'The plane took ___ right on time.', answer: 'off',
    options: '["off","up","out","over"]',
    explanation: '"Take off" (for planes) means to leave the ground.',
    explanation_es: '"Take off" (aviones) = despegar.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'despegar' },
  { id: 'pv_part_011', sentence: 'Can I try ___ these shoes before I buy them?', answer: 'on',
    options: '["on","up","out","in"]',
    explanation: '"Try on" means to test clothing for fit.',
    explanation_es: '"Try on" = probarse (ropa).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'probarse (ropa)' },
  { id: 'pv_part_012', sentence: 'She looks ___ her little brother after school.', answer: 'after',
    options: '["after","up","out","for"]',
    explanation: '"Look after" means to take care of someone.',
    explanation_es: '"Look after" = cuidar (de).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'cuidar (de)' },

  // ── B1 (difficulty 2) ──
  { id: 'pv_part_013', sentence: "We've run ___ of coffee again.", answer: 'out',
    options: '["out","off","up","down"]',
    explanation: '"Run out (of)" means to have no more of something.',
    explanation_es: '"Run out of" = quedarse sin.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'quedarse sin' },
  { id: 'pv_part_014', sentence: "Don't give ___ — you're almost there!", answer: 'up',
    options: '["up","in","out","off"]',
    explanation: '"Give up" means to stop trying / surrender.',
    explanation_es: '"Give up" = rendirse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'rendirse' },
  { id: 'pv_part_015', sentence: 'My car broke ___ on the motorway.', answer: 'down',
    options: '["down","up","off","out"]',
    explanation: '"Break down" (for vehicles/machines) means to stop working.',
    explanation_es: '"Break down" = averiarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'averiarse' },
  { id: 'pv_part_016', sentence: 'Can you turn ___ the volume? It is too loud.', answer: 'down',
    options: '["down","off","up","out"]',
    explanation: '"Turn down" means to lower the volume.',
    explanation_es: '"Turn down" = bajar (el volumen).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'bajar (volumen)' },
  { id: 'pv_part_017', sentence: 'The fire alarm went ___ during the meeting.', answer: 'off',
    options: '["off","on","up","out"]',
    explanation: '"Go off" means (for an alarm) to start sounding.',
    explanation_es: '"Go off" = sonar (una alarma).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'sonar (alarma)' },
  { id: 'pv_part_018', sentence: "I can't figure ___ how this machine works.", answer: 'out',
    options: '["out","up","on","in"]',
    explanation: '"Figure out" means to understand / solve something.',
    explanation_es: '"Figure out" = averiguar / resolver.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'averiguar' },
  { id: 'pv_part_019', sentence: "Look ___ the word if you don't know what it means.", answer: 'up',
    options: '["up","out","on","into"]',
    explanation: '"Look up" means to search for information.',
    explanation_es: '"Look up" = buscar (información).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'buscar (información)' },
  { id: 'pv_part_020', sentence: 'His grandfather passed ___ last winter.', answer: 'away',
    options: '["away","out","on","off"]',
    explanation: '"Pass away" is a polite way to say "die".',
    explanation_es: '"Pass away" = fallecer.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'fallecer' },
  { id: 'pv_part_021', sentence: "I'll deal ___ this problem tomorrow.", answer: 'with',
    options: '["with","in","out","on"]',
    explanation: '"Deal with" means to handle or take care of something.',
    explanation_es: '"Deal with" = ocuparse de / lidiar con.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'ocuparse de' },
  { id: 'pv_part_022', sentence: 'Just carry ___ with your work, I will wait.', answer: 'on',
    options: '["on","out","up","over"]',
    explanation: '"Carry on" means to continue.',
    explanation_es: '"Carry on" = seguir / continuar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'continuar' },
  { id: 'pv_part_023', sentence: 'I need to find ___ what really happened.', answer: 'out',
    options: '["out","up","off","in"]',
    explanation: '"Find out" means to discover information.',
    explanation_es: '"Find out" = descubrir / enterarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'descubrir' },
  { id: 'pv_part_024', sentence: 'Calm ___, everything is going to be fine.', answer: 'down',
    options: '["down","up","off","out"]',
    explanation: '"Calm down" means to relax / stop being upset.',
    explanation_es: '"Calm down" = calmarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'calmarse' },
  { id: 'pv_part_025', sentence: "Don't worry, it will all work ___ in the end.", answer: 'out',
    options: '["out","up","off","on"]',
    explanation: '"Work out" here means to end well / be resolved.',
    explanation_es: '"Work out" = salir bien / resolverse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'salir bien' },
  { id: 'pv_part_026', sentence: 'He never showed ___ for the interview.', answer: 'up',
    options: '["up","out","on","off"]',
    explanation: '"Show up" means to arrive / appear.',
    explanation_es: '"Show up" = presentarse / aparecer.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'presentarse' },
  { id: 'pv_part_027', sentence: 'How are you getting ___ in your new job?', answer: 'on',
    options: '["on","up","off","out"]',
    explanation: '"Get on" here means to progress / manage.',
    explanation_es: '"Get on" = ir / progresar (¿cómo te va?).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'ir / progresar' },
  { id: 'pv_part_028', sentence: "Stop putting ___ your homework and do it now.", answer: 'off',
    options: '["off","out","up","down"]',
    explanation: '"Put off" means to postpone / delay.',
    explanation_es: '"Put off" = aplazar / posponer.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'posponer' },
  { id: 'pv_part_029', sentence: 'Please don\'t bring ___ that subject at dinner.', answer: 'up',
    options: '["up","out","on","in"]',
    explanation: '"Bring up" means to mention / raise a topic.',
    explanation_es: '"Bring up" = mencionar / sacar (un tema).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'sacar (un tema)' },
  { id: 'pv_part_030', sentence: 'The doctor told me to cut ___ on sugar.', answer: 'down',
    options: '["down","off","out","up"]',
    explanation: '"Cut down (on)" means to reduce.',
    explanation_es: '"Cut down on" = reducir.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'reducir' },
  { id: 'pv_part_031', sentence: 'We usually hang ___ at the café on Fridays.', answer: 'out',
    options: '["out","up","on","over"]',
    explanation: '"Hang out" means to spend time relaxing (with friends).',
    explanation_es: '"Hang out" = pasar el rato / quedar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'pasar el rato' },
  { id: 'pv_part_032', sentence: 'They set ___ a new business last year.', answer: 'up',
    options: '["up","out","on","in"]',
    explanation: '"Set up" means to establish / create.',
    explanation_es: '"Set up" = montar / crear.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'montar / crear' },

  // ── B2 (difficulty 3) — partículas dobles ──
  { id: 'pv_part_033', sentence: 'I look ___ to seeing you next week.', answer: 'forward',
    options: '["forward","up","out","after"]',
    explanation: '"Look forward to" means to be excited about a future event.',
    explanation_es: '"Look forward to" = tener ganas de / esperar con ilusión.',
    cefr_level: 'B2', category: 'phrasal_particle', difficulty: 3, answer_es: 'tener ganas de' },
  { id: 'pv_part_034', sentence: 'She came ___ with a brilliant idea.', answer: 'up',
    options: '["up","out","on","over"]',
    explanation: '"Come up with" means to think of / produce an idea.',
    explanation_es: '"Come up with" = ocurrírsele (una idea).',
    cefr_level: 'B2', category: 'phrasal_particle', difficulty: 3, answer_es: 'ocurrírsele (una idea)' },
  { id: 'pv_part_035', sentence: "I can't put ___ with this noise any longer.", answer: 'up',
    options: '["up","out","off","on"]',
    explanation: '"Put up with" means to tolerate something unpleasant.',
    explanation_es: '"Put up with" = aguantar / soportar.',
    cefr_level: 'B2', category: 'phrasal_particle', difficulty: 3, answer_es: 'aguantar' },
  { id: 'pv_part_036', sentence: 'The thief got ___ with the stolen money.', answer: 'away',
    options: '["away","off","out","over"]',
    explanation: '"Get away with" means to escape punishment for something.',
    explanation_es: '"Get away with" = salir impune / salirse con la suya.',
    cefr_level: 'B2', category: 'phrasal_particle', difficulty: 3, answer_es: 'salir impune' },

  // ── Ampliación (37-80) ──
  { id: 'pv_part_037', sentence: 'Please come ___ soon, we will miss you.', answer: 'back',
    options: '["back","in","up","over"]', explanation: '"Come back" means to return.',
    explanation_es: '"Come back" = volver / regresar.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'volver' },
  { id: 'pv_part_038', sentence: "Let's go ___ for dinner tonight.", answer: 'out',
    options: '["out","off","up","in"]', explanation: '"Go out" means to leave home socially.',
    explanation_es: '"Go out" = salir (de fiesta/cita).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'salir' },
  { id: 'pv_part_039', sentence: 'She pointed ___ a mistake in my essay.', answer: 'out',
    options: '["out","up","off","in"]', explanation: '"Point out" means to draw attention to something.',
    explanation_es: '"Point out" = señalar / hacer notar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'señalar' },
  { id: 'pv_part_040', sentence: 'He made ___ a silly excuse.', answer: 'up',
    options: '["up","out","on","off"]', explanation: '"Make up" here means to invent.',
    explanation_es: '"Make up" = inventar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'inventar' },
  { id: 'pv_part_041', sentence: 'A big company took ___ the small firm.', answer: 'over',
    options: '["over","up","on","out"]', explanation: '"Take over" means to take control.',
    explanation_es: '"Take over" = tomar el control.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'tomar el control' },
  { id: 'pv_part_042', sentence: 'Her new album comes ___ next Friday.', answer: 'out',
    options: '["out","up","off","in"]', explanation: '"Come out" here means to be released/published.',
    explanation_es: '"Come out" = salir (una publicación).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'salir (publicación)' },
  { id: 'pv_part_043', sentence: 'We got ___ home very late last night.', answer: 'back',
    options: '["back","out","in","off"]', explanation: '"Get back" means to return.',
    explanation_es: '"Get back" = volver.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'volver' },
  { id: 'pv_part_044', sentence: 'The team took ___ a new challenge.', answer: 'on',
    options: '["on","up","over","out"]', explanation: '"Take on" means to accept a responsibility.',
    explanation_es: '"Take on" = asumir.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'asumir' },
  { id: 'pv_part_045', sentence: "Get ___ of here, it's dangerous!", answer: 'out',
    options: '["out","off","up","in"]', explanation: '"Get out" means to leave / escape.',
    explanation_es: '"Get out" = salir / escapar.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'salir' },
  { id: 'pv_part_046', sentence: 'She let ___ a loud scream.', answer: 'out',
    options: '["out","off","up","in"]', explanation: '"Let out" means to release a sound.',
    explanation_es: '"Let out" = soltar (un grito).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'soltar' },
  { id: 'pv_part_047', sentence: "Get ___ the car, we're leaving now.", answer: 'in',
    options: '["in","on","up","out"]', explanation: '"Get in" means to enter (a car).',
    explanation_es: '"Get in" = subirse / entrar (a un coche).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'subirse (al coche)' },
  { id: 'pv_part_048', sentence: "It's time to move ___ from the past.", answer: 'on',
    options: '["on","up","out","over"]', explanation: '"Move on" means to leave the past behind.',
    explanation_es: '"Move on" = pasar página / seguir adelante.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'pasar página' },
  { id: 'pv_part_049', sentence: "Sorry I'm late, I was held ___ in traffic.", answer: 'up',
    options: '["up","on","out","off"]', explanation: '"Hold up" means to delay.',
    explanation_es: '"Hold up" = retrasar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'retrasar' },
  { id: 'pv_part_050', sentence: 'The company brought ___ new safety rules.', answer: 'in',
    options: '["in","out","up","on"]', explanation: '"Bring in" means to introduce.',
    explanation_es: '"Bring in" = introducir.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'introducir' },
  { id: 'pv_part_051', sentence: 'He finally opened ___ about his feelings.', answer: 'up',
    options: '["up","out","on","in"]', explanation: '"Open up" means to share your emotions.',
    explanation_es: '"Open up" = abrirse (emocionalmente).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'abrirse' },
  { id: 'pv_part_052', sentence: 'Everyone stood ___ when she entered.', answer: 'up',
    options: '["up","on","out","over"]', explanation: '"Stand up" means to rise to your feet.',
    explanation_es: '"Stand up" = levantarse / ponerse de pie.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'levantarse' },
  { id: 'pv_part_053', sentence: 'She kept ___ talking for hours.', answer: 'on',
    options: '["on","up","out","off"]', explanation: '"Keep on" means to continue (persistently).',
    explanation_es: '"Keep on" = seguir (haciendo algo).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'seguir' },
  { id: 'pv_part_054', sentence: 'The police will look ___ the matter.', answer: 'into',
    options: '["into","up","out","after"]', explanation: '"Look into" means to investigate.',
    explanation_es: '"Look into" = investigar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'investigar' },
  { id: 'pv_part_055', sentence: 'In the story, the prince turned ___ a frog.', answer: 'into',
    options: '["into","up","out","over"]', explanation: '"Turn into" means to transform.',
    explanation_es: '"Turn into" = convertirse en.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'convertirse en' },
  { id: 'pv_part_056', sentence: 'He pulled ___ of the competition at the last minute.', answer: 'out',
    options: '["out","up","off","in"]', explanation: '"Pull out" means to withdraw.',
    explanation_es: '"Pull out" = retirarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'retirarse' },
  { id: 'pv_part_057', sentence: 'We took a wrong turn and ended ___ getting lost.', answer: 'up',
    options: '["up","out","on","off"]', explanation: '"End up" means to finish in a situation.',
    explanation_es: '"End up" = acabar / terminar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'acabar' },
  { id: 'pv_part_058', sentence: 'They broke ___ after two years together.', answer: 'up',
    options: '["up","off","out","down"]', explanation: '"Break up" means to end a relationship.',
    explanation_es: '"Break up" = romper (una pareja).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'romper (pareja)' },
  { id: 'pv_part_059', sentence: 'Stress can build ___ over time.', answer: 'up',
    options: '["up","on","out","over"]', explanation: '"Build up" means to accumulate gradually.',
    explanation_es: '"Build up" = acumularse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'acumularse' },
  { id: 'pv_part_060', sentence: 'The storm cut ___ the power to the whole town.', answer: 'off',
    options: '["off","out","up","down"]', explanation: '"Cut off" means to disconnect a supply.',
    explanation_es: '"Cut off" = cortar (el suministro).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'cortar (suministro)' },
  { id: 'pv_part_061', sentence: "She's going ___ a really hard time right now.", answer: 'through',
    options: '["through","up","out","over"]', explanation: '"Go through" means to experience something difficult.',
    explanation_es: '"Go through" = pasar por (una experiencia).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'pasar por' },
  { id: 'pv_part_062', sentence: 'Could you pass ___ this message to her?', answer: 'on',
    options: '["on","out","up","off"]', explanation: '"Pass on" means to relay/convey something.',
    explanation_es: '"Pass on" = transmitir / dar (un mensaje).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'transmitir' },
  { id: 'pv_part_063', sentence: 'The company brought ___ a new model this year.', answer: 'out',
    options: '["out","up","on","in"]', explanation: '"Bring out" means to release/launch a product.',
    explanation_es: '"Bring out" = lanzar / sacar (al mercado).',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'lanzar' },
  { id: 'pv_part_064', sentence: "He moved ___ of his parents' house last month.", answer: 'out',
    options: '["out","up","off","in"]', explanation: '"Move out" means to leave a home.',
    explanation_es: '"Move out" = irse (de una vivienda).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'irse (de casa)' },
  { id: 'pv_part_065', sentence: 'I take ___ everything I said, I was wrong.', answer: 'back',
    options: '["back","up","out","off"]', explanation: '"Take back" means to retract what you said.',
    explanation_es: '"Take back" = retractarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'retractarse' },
  { id: 'pv_part_066', sentence: 'The thief was forced to hand ___ the money.', answer: 'over',
    options: '["over","up","out","in"]', explanation: '"Hand over" means to give something (often reluctantly).',
    explanation_es: '"Hand over" = entregar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'entregar' },
  { id: 'pv_part_067', sentence: 'He finally turned ___ an hour late.', answer: 'up',
    options: '["up","out","on","off"]', explanation: '"Turn up" means to arrive/appear.',
    explanation_es: '"Turn up" = aparecer / presentarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'aparecer' },
  { id: 'pv_part_068', sentence: 'She got ___ the train and walked home.', answer: 'off',
    options: '["off","on","up","in"]', explanation: '"Get off" means to leave a bus/train.',
    explanation_es: '"Get off" = bajarse (de un transporte).',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'bajarse' },
  { id: 'pv_part_069', sentence: 'The judge threw ___ the case for lack of evidence.', answer: 'out',
    options: '["out","off","up","away"]', explanation: '"Throw out" here means to reject/dismiss.',
    explanation_es: '"Throw out" = descartar / desestimar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'descartar' },
  { id: 'pv_part_070', sentence: "Don't worry, we'll get ___ this together.", answer: 'through',
    options: '["through","up","out","over"]', explanation: '"Get through" here means to survive/overcome.',
    explanation_es: '"Get through" = superar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'superar' },
  { id: 'pv_part_071', sentence: 'Be careful on the ice or you might fall ___.', answer: 'down',
    options: '["down","off","out","over"]', explanation: '"Fall down" means to fall to the ground.',
    explanation_es: '"Fall down" = caerse.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'caerse' },
  { id: 'pv_part_072', sentence: 'She moved ___ to a senior position.', answer: 'up',
    options: '["up","out","on","over"]', explanation: '"Move up" means to advance/get promoted.',
    explanation_es: '"Move up" = ascender.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'ascender' },
  { id: 'pv_part_073', sentence: 'They had to shut ___ the factory for good.', answer: 'down',
    options: '["down","off","up","out"]', explanation: '"Shut down" means to close/stop operating.',
    explanation_es: '"Shut down" = cerrar / apagar.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'cerrar / apagar' },
  { id: 'pv_part_074', sentence: 'A fire broke ___ in the kitchen.', answer: 'out',
    options: '["out","up","off","down"]', explanation: '"Break out" means (fire/war) to start suddenly.',
    explanation_es: '"Break out" = estallar / declararse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'estallar' },
  { id: 'pv_part_075', sentence: "It's hard to keep ___ with all the news.", answer: 'up',
    options: '["up","on","out","off"]', explanation: '"Keep up (with)" means to stay at the same level / up to date.',
    explanation_es: '"Keep up" = seguir el ritmo / estar al día.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'seguir el ritmo' },
  { id: 'pv_part_076', sentence: 'Please give ___ the book you borrowed.', answer: 'back',
    options: '["back","up","in","out"]', explanation: '"Give back" means to return something.',
    explanation_es: '"Give back" = devolver.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'devolver' },
  { id: 'pv_part_077', sentence: "Slow ___, you're driving too fast!", answer: 'down',
    options: '["down","up","off","out"]', explanation: '"Slow down" means to reduce speed.',
    explanation_es: '"Slow down" = reducir la velocidad.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'reducir la velocidad' },
  { id: 'pv_part_078', sentence: 'Write ___ your ideas before you forget them.', answer: 'down',
    options: '["down","up","out","in"]', explanation: '"Write down" means to note something on paper.',
    explanation_es: '"Write down" = anotar / apuntar.',
    cefr_level: 'A2', category: 'phrasal_particle', difficulty: 1, answer_es: 'anotar' },
  { id: 'pv_part_079', sentence: 'The couple split ___ after ten years.', answer: 'up',
    options: '["up","out","off","down"]', explanation: '"Split up" means to separate/break up.',
    explanation_es: '"Split up" = separarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'separarse' },
  { id: 'pv_part_080', sentence: 'She spoke ___ against the unfair law.', answer: 'out',
    options: '["out","up","off","on"]', explanation: '"Speak out" means to state your opinion publicly.',
    explanation_es: '"Speak out" = alzar la voz / pronunciarse.',
    cefr_level: 'B1', category: 'phrasal_particle', difficulty: 2, answer_es: 'alzar la voz' },
];
