// Cambridge Use of English Part 3 — Word Formation
// Given a base word, transform it to fit the sentence gap

export interface WordFormationSeedItem {
  id: string;
  sentence: string;
  answer: string;
  options: string | null;
  explanation: string;
  explanation_es: string;
  cefr_level: string;
  category: string;
  difficulty: number;
  base_word: string;
  answer_es?: string;
}

export const WORD_FORMATION_EXERCISES: WordFormationSeedItem[] = [
  // ── B1 (difficulty 1) ──
  {
    id: 'wf_001',
    sentence: 'The experiment was a great ___.',
    answer: 'success',
    options: '["success","successful","succession","successive"]',
    base_word: 'SUCCEED',
    explanation: 'We need a noun after "a great". SUCCEED → SUCCESS (noun).',
    explanation_es: 'Necesitamos un sustantivo tras "a great". SUCCEED → SUCCESS.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'éxito',
  },
  {
    id: 'wf_002',
    sentence: 'She is an extremely ___ person.',
    answer: 'creative',
    options: '["creative","creation","create","creator"]',
    base_word: 'CREATE',
    explanation: 'We need an adjective to describe "person". CREATE → CREATIVE.',
    explanation_es: 'Necesitamos un adjetivo para describir "person". CREATE → CREATIVE.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'explicación',
  },
  {
    id: 'wf_003',
    sentence: 'His ___ of the problem was excellent.',
    answer: 'explanation',
    options: '["explanation","explanatory","explain","explainable"]',
    base_word: 'EXPLAIN',
    explanation: '"His ___" requires a noun. EXPLAIN → EXPLANATION.',
    explanation_es: '"His ___" requiere un sustantivo. EXPLAIN → EXPLANATION.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'decisión',
  },
  {
    id: 'wf_004',
    sentence: 'The children were very ___ during the trip.',
    answer: 'excited',
    options: '["excited","exciting","excitement","excitedly"]',
    base_word: 'EXCITE',
    explanation: 'We need an adjective describing how the children felt. EXCITE → EXCITED (-ed for feelings).',
    explanation_es: 'Necesitamos un adjetivo sobre cómo se sentían. EXCITE → EXCITED (-ed para sentimientos).',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'felizmente',
  },
  {
    id: 'wf_005',
    sentence: 'The ___ of the new bridge took two years.',
    answer: 'construction',
    options: '["construction","constructive","construct","constructor"]',
    base_word: 'CONSTRUCT',
    explanation: '"The ___" needs a noun. CONSTRUCT → CONSTRUCTION.',
    explanation_es: '"The ___" necesita un sustantivo. CONSTRUCT → CONSTRUCTION.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'construcción',
  },
  {
    id: 'wf_006',
    sentence: 'It is ___ to wear a seatbelt.',
    answer: 'necessary',
    options: '["necessary","necessarily","necessity","necessitate"]',
    base_word: 'NECESSITY',
    explanation: 'After "It is" we need an adjective. NECESSITY → NECESSARY.',
    explanation_es: 'Tras "It is" necesitamos un adjetivo. NECESSITY → NECESSARY.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'belleza / hermosura',
  },
  {
    id: 'wf_007',
    sentence: 'She smiled ___ at the camera.',
    answer: 'happily',
    options: '["happily","happy","happiness","unhappy"]',
    base_word: 'HAPPY',
    explanation: 'We need an adverb to modify "smiled". HAPPY → HAPPILY.',
    explanation_es: 'Necesitamos un adverbio para modificar "smiled". HAPPY → HAPPILY.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'relación',
  },
  {
    id: 'wf_008',
    sentence: 'He made an important ___ yesterday.',
    answer: 'decision',
    options: '["decision","decisive","decide","decidedly"]',
    base_word: 'DECIDE',
    explanation: '"An important ___" requires a noun. DECIDE → DECISION.',
    explanation_es: '"An important ___" requiere un sustantivo. DECIDE → DECISION.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'reducción',
  },
  {
    id: 'wf_009',
    sentence: 'The sunset was absolutely ___.',
    answer: 'beautiful',
    options: '["beautiful","beauty","beautifully","beautify"]',
    base_word: 'BEAUTY',
    explanation: 'After "was absolutely" we need an adjective. BEAUTY → BEAUTIFUL.',
    explanation_es: 'Tras "was absolutely" necesitamos un adjetivo. BEAUTY → BEAUTIFUL.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'mejora / mejoramiento',
  },
  {
    id: 'wf_010',
    sentence: 'There has been a significant ___ in technology.',
    answer: 'improvement',
    options: '["improvement","improve","improved","improving"]',
    base_word: 'IMPROVE',
    explanation: '"A significant ___" needs a noun. IMPROVE → IMPROVEMENT.',
    explanation_es: '"A significant ___" necesita un sustantivo. IMPROVE → IMPROVEMENT.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'contribución',
  },
  // ── B2 (difficulty 2) ──
  {
    id: 'wf_011',
    sentence: 'The company made several ___ changes last year.',
    answer: 'significant',
    options: '["significant","significance","signify","significantly"]',
    base_word: 'SIGNIFY',
    explanation: 'We need an adjective before "changes". SIGNIFY → SIGNIFICANT.',
    explanation_es: 'Necesitamos un adjetivo antes de "changes". SIGNIFY → SIGNIFICANT.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'fiable / de confianza',
  },
  {
    id: 'wf_012',
    sentence: 'His behaviour was completely ___.',
    answer: 'unacceptable',
    options: '["unacceptable","acceptable","acceptance","accept"]',
    base_word: 'ACCEPT',
    explanation: 'Context says negative ("completely ___" after bad behaviour). ACCEPT → UNACCEPTABLE (prefix un- + suffix -able).',
    explanation_es: 'El contexto es negativo. ACCEPT → UNACCEPTABLE (prefijo un- + sufijo -able).',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'inaceptable',
  },
  {
    id: 'wf_013',
    sentence: 'She has a natural ___ for languages.',
    answer: 'ability',
    options: '["ability","able","ably","unable"]',
    base_word: 'ABLE',
    explanation: '"A natural ___" needs a noun. ABLE → ABILITY.',
    explanation_es: '"A natural ___" necesita un sustantivo. ABLE → ABILITY.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'habilidad / capacidad',
  },
  {
    id: 'wf_014',
    sentence: 'The instructions were ___ unclear.',
    answer: 'incredibly',
    options: '["incredibly","incredible","incredibility","incredulous"]',
    base_word: 'INCREDIBLE',
    explanation: 'We need an adverb to modify "unclear". INCREDIBLE → INCREDIBLY.',
    explanation_es: 'Necesitamos un adverbio para modificar "unclear". INCREDIBLE → INCREDIBLY.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'significativo/a',
  },
  {
    id: 'wf_015',
    sentence: 'The ___ of the rainforest is a global concern.',
    answer: 'destruction',
    options: '["destruction","destructive","destroy","indestructible"]',
    base_word: 'DESTROY',
    explanation: '"The ___" needs a noun. DESTROY → DESTRUCTION.',
    explanation_es: '"The ___" necesita un sustantivo. DESTROY → DESTRUCTION.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'destrucción',
  },
  {
    id: 'wf_016',
    sentence: 'He is a very ___ worker and always meets deadlines.',
    answer: 'reliable',
    options: '["reliable","rely","reliance","reliably"]',
    base_word: 'RELY',
    explanation: 'We need an adjective describing "worker". RELY → RELIABLE.',
    explanation_es: 'Necesitamos un adjetivo para describir "worker". RELY → RELIABLE.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'investigación',
  },
  {
    id: 'wf_017',
    sentence: 'The police are carrying out an ___ into the robbery.',
    answer: 'investigation',
    options: '["investigation","investigate","investigative","investigator"]',
    base_word: 'INVESTIGATE',
    explanation: '"An ___" needs a noun. INVESTIGATE → INVESTIGATION.',
    explanation_es: '"An ___" necesita un sustantivo. INVESTIGATE → INVESTIGATION.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'profundamente',
  },
  {
    id: 'wf_018',
    sentence: 'She looked at him ___ when he said that.',
    answer: 'angrily',
    options: '["angrily","angry","anger","angered"]',
    base_word: 'ANGER',
    explanation: 'We need an adverb to modify "looked". ANGER → ANGRILY.',
    explanation_es: 'Necesitamos un adverbio para modificar "looked". ANGER → ANGRILY.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'interpretación',
  },
  {
    id: 'wf_019',
    sentence: 'There is no ___ explanation for what happened.',
    answer: 'scientific',
    options: '["scientific","science","scientist","scientifically"]',
    base_word: 'SCIENCE',
    explanation: 'We need an adjective before "explanation". SCIENCE → SCIENTIFIC.',
    explanation_es: 'Necesitamos un adjetivo antes de "explanation". SCIENCE → SCIENTIFIC.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'infranqueable / intransitable',
  },
  {
    id: 'wf_020',
    sentence: 'The flight was cancelled due to ___ weather conditions.',
    answer: 'unfavourable',
    options: '["unfavourable","favourable","favour","favourably"]',
    base_word: 'FAVOUR',
    explanation: 'Context is negative (cancellation). FAVOUR → UNFAVOURABLE (un- + -able).',
    explanation_es: 'El contexto es negativo (cancelación). FAVOUR → UNFAVOURABLE (un- + -able).',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'emocionalmente',
  },
  // ── B2–C1 (difficulty 3) ──
  {
    id: 'wf_021',
    sentence: 'The politician denied any ___ in the scandal.',
    answer: 'involvement',
    options: '["involvement","involve","involved","involving"]',
    base_word: 'INVOLVE',
    explanation: '"Any ___" needs a noun. INVOLVE → INVOLVEMENT.',
    explanation_es: '"Any ___" necesita un sustantivo. INVOLVE → INVOLVEMENT.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'aterrador/a',
  },
  {
    id: 'wf_022',
    sentence: 'The essay lacked ___ and was hard to follow.',
    answer: 'coherence',
    options: '["coherence","coherent","coherently","incoherent"]',
    base_word: 'COHERE',
    explanation: '"Lacked ___" needs a noun. COHERE → COHERENCE.',
    explanation_es: '"Lacked ___" necesita un sustantivo. COHERE → COHERENCE.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'brillantemente',
  },
  {
    id: 'wf_023',
    sentence: 'She spoke ___ about her childhood experiences.',
    answer: 'emotionally',
    options: '["emotionally","emotional","emotion","emotive"]',
    base_word: 'EMOTION',
    explanation: 'We need an adverb modifying "spoke". EMOTION → EMOTIONALLY.',
    explanation_es: 'Necesitamos un adverbio que modifique "spoke". EMOTION → EMOTIONALLY.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'ilegal',
  },
  {
    id: 'wf_024',
    sentence: 'His ___ to detail is remarkable.',
    answer: 'attention',
    options: '["attention","attentive","attend","attentively"]',
    base_word: 'ATTEND',
    explanation: '"His ___" needs a noun. ATTEND → ATTENTION.',
    explanation_es: '"His ___" necesita un sustantivo. ATTEND → ATTENTION.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'atención',
  },
  {
    id: 'wf_025',
    sentence: 'Many people find it ___ to speak in public.',
    answer: 'frightening',
    options: '["frightening","frightened","fright","frighten"]',
    base_word: 'FRIGHT',
    explanation: 'We need an adjective describing the activity. FRIGHT → FRIGHTENING (-ing for things that cause fear).',
    explanation_es: 'Necesitamos un adjetivo sobre la actividad. FRIGHT → FRIGHTENING (-ing para cosas que causan miedo).',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'necesario/a',
  },
  {
    id: 'wf_026',
    sentence: 'The company announced a series of ___.',
    answer: 'redundancies',
    options: '["redundancies","redundant","redundancy","redundantly"]',
    base_word: 'REDUNDANT',
    explanation: '"A series of ___" requires a plural noun. REDUNDANT → REDUNDANCIES.',
    explanation_es: '"A series of ___" requiere un sustantivo plural. REDUNDANT → REDUNDANCIES.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'detallado/a',
  },
  {
    id: 'wf_027',
    sentence: 'The results were ___ disappointing.',
    answer: 'deeply',
    options: '["deeply","deep","depth","deepen"]',
    base_word: 'DEEP',
    explanation: 'We need an adverb to intensify "disappointing". DEEP → DEEPLY.',
    explanation_es: 'Necesitamos un adverbio para intensificar "disappointing". DEEP → DEEPLY.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'coherencia',
  },
  {
    id: 'wf_028',
    sentence: 'His ___ as a surgeon is well known.',
    answer: 'expertise',
    options: '["expertise","expert","expertly","inexpert"]',
    base_word: 'EXPERT',
    explanation: '"His ___" needs a noun. EXPERT → EXPERTISE.',
    explanation_es: '"His ___" necesita un sustantivo. EXPERT → EXPERTISE.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'desfavorable',
  },
  {
    id: 'wf_029',
    sentence: 'The government must take ___ action on climate change.',
    answer: 'decisive',
    options: '["decisive","decide","decision","indecisive"]',
    base_word: 'DECIDE',
    explanation: 'We need an adjective before "action". DECIDE → DECISIVE.',
    explanation_es: 'Necesitamos un adjetivo antes de "action". DECIDE → DECISIVE.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'deshonestidad',
  },
  {
    id: 'wf_030',
    sentence: 'The museum has an ___ collection of paintings.',
    answer: 'impressive',
    options: '["impressive","impress","impression","impressively"]',
    base_word: 'IMPRESS',
    explanation: 'We need an adjective before "collection". IMPRESS → IMPRESSIVE.',
    explanation_es: 'Necesitamos un adjetivo antes de "collection". IMPRESS → IMPRESSIVE.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'impresionante',
  },
  // ── More Word Formation (negative prefixes, suffixes, C1) ──
  {
    id: 'wf_031',
    sentence: 'His ___ to the project was invaluable.',
    answer: 'contribution',
    options: '["contribution","contribute","contributing","contributor"]',
    base_word: 'CONTRIBUTE',
    explanation: '"His ___" needs a noun. CONTRIBUTE → CONTRIBUTION.',
    explanation_es: '"His ___" necesita un sustantivo. CONTRIBUTE → CONTRIBUTION.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'habilidad / capacidad',
  },
  {
    id: 'wf_032',
    sentence: 'It would be ___ to leave without saying goodbye.',
    answer: 'impolite',
    options: '["impolite","polite","politely","politeness"]',
    base_word: 'POLITE',
    explanation: 'Context is negative (leaving without saying goodbye). POLITE → IMPOLITE (prefix im-).',
    explanation_es: 'El contexto es negativo. POLITE → IMPOLITE (prefijo im-).',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'enojado/a / con enfado',
  },
  {
    id: 'wf_033',
    sentence: 'The ___ of the new drug has not yet been confirmed.',
    answer: 'effectiveness',
    options: '["effectiveness","effective","effectively","ineffective"]',
    base_word: 'EFFECT',
    explanation: '"The ___" needs a noun. EFFECT → EFFECTIVENESS.',
    explanation_es: '"The ___" necesita un sustantivo. EFFECT → EFFECTIVENESS.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'efectividad / eficacia',
  },
  {
    id: 'wf_034',
    sentence: 'She handled the situation very ___.',
    answer: 'professionally',
    options: '["professionally","professional","profession","unprofessional"]',
    base_word: 'PROFESSION',
    explanation: 'We need an adverb modifying "handled". PROFESSION → PROFESSIONALLY.',
    explanation_es: 'Necesitamos un adverbio que modifique "handled". PROFESSION → PROFESSIONALLY.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'completo/a / exhaustivo/a',
  },
  {
    id: 'wf_035',
    sentence: 'There was a sudden ___ in the price of oil.',
    answer: 'reduction',
    options: '["reduction","reduce","reduced","reducible"]',
    base_word: 'REDUCE',
    explanation: '"A sudden ___" needs a noun. REDUCE → REDUCTION.',
    explanation_es: '"A sudden ___" necesita un sustantivo. REDUCE → REDUCTION.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'descuidado/a / en mal estado',
  },
  {
    id: 'wf_036',
    sentence: 'The children showed great ___ when they heard the news.',
    answer: 'enthusiasm',
    options: '["enthusiasm","enthusiastic","enthusiastically","enthusiast"]',
    base_word: 'ENTHUSIASTIC',
    explanation: '"Great ___" needs a noun. ENTHUSIASTIC → ENTHUSIASM.',
    explanation_es: '"Great ___" necesita un sustantivo. ENTHUSIASTIC → ENTHUSIASM.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'confidencial',
  },
  {
    id: 'wf_037',
    sentence: 'The food in the restaurant was ___ bad.',
    answer: 'surprisingly',
    options: '["surprisingly","surprised","surprising","surprise"]',
    base_word: 'SURPRISE',
    explanation: 'We need an adverb to modify "bad". SURPRISE → SURPRISINGLY.',
    explanation_es: 'Necesitamos un adverbio para modificar "bad". SURPRISE → SURPRISINGLY.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'decisivo/a',
  },
  {
    id: 'wf_038',
    sentence: 'It is ___ to drive without wearing a seatbelt.',
    answer: 'illegal',
    options: '["illegal","legal","legally","legality"]',
    base_word: 'LEGAL',
    explanation: 'Context is negative (driving without seatbelt). LEGAL → ILLEGAL (prefix il-).',
    explanation_es: 'Contexto negativo (conducir sin cinturón). LEGAL → ILLEGAL (prefijo il-).',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'insatisfacción',
  },
  {
    id: 'wf_039',
    sentence: 'She expressed her ___ with the new arrangements.',
    answer: 'dissatisfaction',
    options: '["dissatisfaction","satisfaction","satisfactory","dissatisfied"]',
    base_word: 'SATISFY',
    explanation: 'Context is negative ("her ___ with"). SATISFY → DISSATISFACTION (dis- + noun).',
    explanation_es: 'Contexto negativo. SATISFY → DISSATISFACTION (dis- + sustantivo).',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'redundancias / despidos',
  },
  {
    id: 'wf_040',
    sentence: 'The old building is in a state of complete ___.',
    answer: 'disrepair',
    options: '["disrepair","repair","repairable","irreparable"]',
    base_word: 'REPAIR',
    explanation: '"State of ___" needs a noun. Negative context → REPAIR → DISREPAIR.',
    explanation_es: '"State of ___" necesita sustantivo. Contexto negativo → REPAIR → DISREPAIR.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'implicación / participación',
  },
  {
    id: 'wf_041',
    sentence: 'She gave a ___ performance in the play.',
    answer: 'memorable',
    options: '["memorable","memory","memorise","memorably"]',
    base_word: 'MEMORY',
    explanation: 'We need an adjective before "performance". MEMORY → MEMORABLE.',
    explanation_es: 'Necesitamos un adjetivo antes de "performance". MEMORY → MEMORABLE.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'memorable',
  },
  {
    id: 'wf_042',
    sentence: 'He acted ___ and everyone trusted him.',
    answer: 'honestly',
    options: '["honestly","honest","honesty","dishonest"]',
    base_word: 'HONEST',
    explanation: 'We need an adverb modifying "acted". HONEST → HONESTLY.',
    explanation_es: 'Necesitamos un adverbio que modifique "acted". HONEST → HONESTLY.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'modernizar',
  },
  {
    id: 'wf_043',
    sentence: 'The ___ between the two countries has improved.',
    answer: 'relationship',
    options: '["relationship","relate","related","relative"]',
    base_word: 'RELATE',
    explanation: '"The ___" needs a noun. RELATE → RELATIONSHIP.',
    explanation_es: '"The ___" necesita un sustantivo. RELATE → RELATIONSHIP.',
    cefr_level: 'B1', category: 'word_formation', difficulty: 1,
    answer_es: 'entusiasmo',
  },
  {
    id: 'wf_044',
    sentence: 'This book provides a ___ introduction to physics.',
    answer: 'comprehensive',
    options: '["comprehensive","comprehend","comprehension","comprehensively"]',
    base_word: 'COMPREHEND',
    explanation: 'We need an adjective before "introduction". COMPREHEND → COMPREHENSIVE.',
    explanation_es: 'Necesitamos un adjetivo antes de "introduction". COMPREHEND → COMPREHENSIVE.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'increíblemente',
  },
  {
    id: 'wf_045',
    sentence: 'The witness gave a ___ account of the incident.',
    answer: 'detailed',
    options: '["detailed","detail","details","detailing"]',
    base_word: 'DETAIL',
    explanation: 'We need an adjective before "account". DETAIL → DETAILED.',
    explanation_es: 'Necesitamos un adjetivo antes de "account". DETAIL → DETAILED.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'aislado/a',
  },
  {
    id: 'wf_046',
    sentence: 'His ___ of the situation was completely wrong.',
    answer: 'interpretation',
    options: '["interpretation","interpret","interpretive","interpreter"]',
    base_word: 'INTERPRET',
    explanation: '"His ___" needs a noun. INTERPRET → INTERPRETATION.',
    explanation_es: '"His ___" necesita un sustantivo. INTERPRET → INTERPRETATION.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'emocionado/a',
  },
  {
    id: 'wf_047',
    sentence: 'The road was ___ after the heavy rain.',
    answer: 'impassable',
    options: '["impassable","passable","passage","passing"]',
    base_word: 'PASS',
    explanation: 'Negative context (after heavy rain → can\'t use it). PASS → IMPASSABLE.',
    explanation_es: 'Contexto negativo (tras lluvia fuerte). PASS → IMPASSABLE.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'sorprendentemente',
  },
  {
    id: 'wf_048',
    sentence: 'We need to ___ the system to make it more efficient.',
    answer: 'modernise',
    options: '["modernise","modern","modernity","modernisation"]',
    base_word: 'MODERN',
    explanation: 'After "need to" we need a verb. MODERN → MODERNISE.',
    explanation_es: 'Después de "need to" necesitamos un verbo. MODERN → MODERNISE.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'debilidades',
  },
  {
    id: 'wf_049',
    sentence: 'She showed remarkable ___ during the crisis.',
    answer: 'leadership',
    options: '["leadership","leader","lead","leading"]',
    base_word: 'LEAD',
    explanation: '"Remarkable ___" needs a noun. LEAD → LEADERSHIP.',
    explanation_es: '"Remarkable ___" necesita un sustantivo. LEAD → LEADERSHIP.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'eliminar',
  },
  {
    id: 'wf_050',
    sentence: 'The contract is ___ binding on both parties.',
    answer: 'legally',
    options: '["legally","legal","legality","legalise"]',
    base_word: 'LEGAL',
    explanation: 'We need an adverb to modify "binding". LEGAL → LEGALLY.',
    explanation_es: 'Necesitamos un adverbio para modificar "binding". LEGAL → LEGALLY.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'maleducado/a / descortés',
  },
  {
    id: 'wf_051',
    sentence: 'The politician\'s ___ shocked everyone.',
    answer: 'dishonesty',
    options: '["dishonesty","honest","honesty","dishonest"]',
    base_word: 'HONEST',
    explanation: 'Negative context (shocked). Needs a noun. HONEST → DISHONESTY.',
    explanation_es: 'Contexto negativo (impactó). Necesita sustantivo. HONEST → DISHONESTY.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'pericia / experiencia',
  },
  {
    id: 'wf_052',
    sentence: 'The team played ___ and deserved to win.',
    answer: 'brilliantly',
    options: '["brilliantly","brilliant","brilliance","brightness"]',
    base_word: 'BRILLIANT',
    explanation: 'We need an adverb modifying "played". BRILLIANT → BRILLIANTLY.',
    explanation_es: 'Necesitamos un adverbio que modifique "played". BRILLIANT → BRILLIANTLY.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'brillantemente',
  },
  {
    id: 'wf_053',
    sentence: 'There is a growing ___ that the economy will recover soon.',
    answer: 'belief',
    options: '["belief","believe","believable","unbelievable"]',
    base_word: 'BELIEVE',
    explanation: '"A growing ___" needs a noun. BELIEVE → BELIEF.',
    explanation_es: '"A growing ___" necesita un sustantivo. BELIEVE → BELIEF.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'creencia',
  },
  {
    id: 'wf_054',
    sentence: 'This information is strictly ___.',
    answer: 'confidential',
    options: '["confidential","confide","confidence","confidently"]',
    base_word: 'CONFIDE',
    explanation: 'After "is strictly" we need an adjective. CONFIDE → CONFIDENTIAL.',
    explanation_es: 'Después de "is strictly" necesitamos adjetivo. CONFIDE → CONFIDENTIAL.',
    cefr_level: 'C1', category: 'word_formation', difficulty: 3,
    answer_es: 'confidencial',
  },
  {
    id: 'wf_055',
    sentence: 'The storm caused widespread ___.',
    answer: 'destruction',
    options: '["destruction","destroy","destructive","indestructible"]',
    base_word: 'DESTROY',
    explanation: '"Widespread ___" needs a noun. DESTROY → DESTRUCTION.',
    explanation_es: '"Widespread ___" necesita un sustantivo. DESTROY → DESTRUCTION.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'destrucción',
  },
  {
    id: 'wf_056',
    sentence: 'The new law aims to ___ discrimination in the workplace.',
    answer: 'eliminate',
    options: '["eliminate","elimination","eliminating","eliminatory"]',
    base_word: 'ELIMINATION',
    explanation: 'After "aims to" we need a verb. ELIMINATION → ELIMINATE.',
    explanation_es: 'Después de "aims to" necesitamos un verbo. ELIMINATION → ELIMINATE.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'eliminar',
  },
  {
    id: 'wf_057',
    sentence: 'Her ___ to finish the marathon was admirable.',
    answer: 'determination',
    options: '["determination","determine","determined","determinedly"]',
    base_word: 'DETERMINE',
    explanation: '"Her ___" needs a noun. DETERMINE → DETERMINATION.',
    explanation_es: '"Her ___" necesita un sustantivo. DETERMINE → DETERMINATION.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'determinación',
  },
  {
    id: 'wf_058',
    sentence: 'The house was in an ___ location, far from any neighbours.',
    answer: 'isolated',
    options: '["isolated","isolate","isolation","isolating"]',
    base_word: 'ISOLATE',
    explanation: 'We need an adjective before "location". ISOLATE → ISOLATED.',
    explanation_es: 'Necesitamos un adjetivo antes de "location". ISOLATE → ISOLATED.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'aislado/a',
  },
  {
    id: 'wf_059',
    sentence: 'The report highlighted several ___ in the current system.',
    answer: 'weaknesses',
    options: '["weaknesses","weak","weaken","weakly"]',
    base_word: 'WEAK',
    explanation: '"Several ___" needs a plural noun. WEAK → WEAKNESSES.',
    explanation_es: '"Several ___" necesita un sustantivo plural. WEAK → WEAKNESSES.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'debilidades',
  },
  {
    id: 'wf_060',
    sentence: 'The discovery was of great ___ importance.',
    answer: 'scientific',
    options: '["scientific","science","scientist","scientifically"]',
    base_word: 'SCIENCE',
    explanation: 'We need an adjective before "importance". SCIENCE → SCIENTIFIC.',
    explanation_es: 'Necesitamos un adjetivo antes de "importance". SCIENCE → SCIENTIFIC.',
    cefr_level: 'B2', category: 'word_formation', difficulty: 2,
    answer_es: 'científico/a',
  },
];
